### ISSUE TITLE
Exception (warning) with ksort

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#100]
From: Gernot Ploiner
Old Link: https://forge.typo3.org/issues/79704
Details:
It appears, when there exists no CE or no backend_layout.
And debug mode must be turned on.
![ksort](https://user-images.githubusercontent.com/1930849/35531224-a51d79a8-0536-11e8-9583-e5ae0e06c435.jpg)

**Comment by xaloga** [comment]
I was able to reproduce this error if no Mask Content Element was present while I tried to generate a Page Template. 
Creating a dummy Mask Content Element does the job as workaround.

I've had a quick look in the StorageRepository, the $json["tt_content"] never gets touched in the function add if a Page Template is created first.
Adding a simple if($json["tt_content"]) in the function sortJson fixed the behavior in my tests and should have no negative impact as far i can tell.
