### ISSUE TITLE
related content

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#103]
From: Jan Viehweger
Old Link: https://forge.typo3.org/issues/79649
Details:
i try to create a related content functionality without luck.

i have a mask element (key item) which contains a "selectbox" (key related). the foreign_table field is set to tt_content and the foreign_table_where is set to AND tt_content.CType="mask_item" AND tt_content.uid != ###THIS_UID###

all possible entries are shown correctly in the item's backend form, no problem.
but when trying to save the item record, all uid's of the selected related items are stored in the tx_mask_related field but are not rendered as selected.

using the same principle with another table (e.g. pages), everything works as expected.

**Comment by nhovratov** [comment]
This works in current version
