### ISSUE TITLE
PHP Warnings

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#104]
From: Gernot Ploiner
Old Link: https://forge.typo3.org/issues/79095
Details:
The following 3 warnings are in the TYPO3-Log in the Backend.
To reproduce: Clear all cache in the Installtool and load the websites home page.

Core: Error handler (BE): PHP Warning: implode(): Invalid arguments passed in /html/typo3/typo3conf/ext/mask/Classes/CodeGenerator/TcaCodeGenerator.php line 494

Core: Error handler (BE): PHP Warning: implode(): Invalid arguments passed in /html/typo3/typo3conf/ext/mask/Classes/CodeGenerator/TcaCodeGenerator.php line 493

Core: Error handler (BE): PHP Warning: implode(): Invalid arguments passed in /html/typo3/typo3conf/ext/mask/Classes/CodeGenerator/TcaCodeGenerator.php line 492

**Comment by Redsmith24** [comment]
I changed `implode(",", $fields);` to `implode(",", (array) $fields);` in the three Lines to make sure that the Variable is an Array. So the Warnings disappeared.

**Comment by Gernott** [comment]
Thank you.
Fixed in commit 9654a958ea7f033b6bdb44b443213a0c9206326f
