### ISSUE TITLE
Make it possible to create mask elements with gridelements drag-in wizzard

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#110]
From: Tobias Pfender
Old link: https://forge.typo3.org/issues/75437
Details:
Currently it isn't possibily to drop mask elements from the gridelements drag-in wizzard to page columns.
I use
TYPO3 7.6.4
mask 1.1.4
gridelements 7.0.5

**Comment by Coders-Care** [comment]
SInce both extensions are part of the Coders.Care project, we should be able to tackle that issue now, shouldn't we? ;-)

**Comment by Gernott** [comment]
Let's talk about this at the UX week in april?

**Comment by christian-forgacs** [comment]
+1 🙈

**Comment by nhovratov** [comment]
There is a patch right now pending in TYPO3 core to add drag and drop for content elements. This will supersede the custom gridelements solution and will work for all kinds of content elements.
