### ISSUE TITLE
Add mask icon to content element

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#111]
From: Tim Tilch
Old Link: https://forge.typo3.org/issues/82302
Details:
For now a content element of type mask has the icon for content element of type text.
You could change it to the same icon as in the admin tools
<img width="267" alt="bildschirmfoto 2017-09-05 um 13 20 17" src="https://user-images.githubusercontent.com/1930849/35625403-8a66d4d0-0692-11e8-9653-538bd2929903.png">

**Comment by butu** [comment]
This will be integrated in the new mask version 4.0.0
