### ISSUE TITLE
Remove ce_ from previewimage filename

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#114]
Preview images must have the filename like ce_[elementkey].png
The original idea was to difference them with the prefix from the backend-layout images. but this is not a good idea, because all other filenames don't use this prefix. So simply remove the prefix to the filename [elementkey].png

**Comment by fjacobi** [comment]
Will there be a temporary fallback for that?

**Comment by Gernott** [comment]
No, I don't think this is neccessary. There should be a good upgrade instruction :-)
