### ISSUE TITLE
Header-label in nested content is wrong

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#117]
The error occurs, when using a contentelement with the TYPO3-regular header-field with an own label, and a second field with nested content.
When using this Mask-element, the header has the given label - fine. After adding a subcontent in the nested field (e.g. the 'text' element), then the label is the same one as given in the parent (Mask-)element.

See also:
https://forge.typo3.org/issues/78593
https://forge.typo3.org/issues/76562

**Comment by nhovratov** [comment]
Does not occur anymore
