### ISSUE TITLE
FileReferences missing in content elements

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#118]
From: Manfred Mirsch
Old link: https://forge.typo3.org/issues/77230
Details:
I created two mask content elements:
1. Am element "tile" having "image" as one of the fields for usage as content elements
2. An element "tiles" having one element of type "content" allowing "tile" as element

I inserted a content element on a page of type tiles and inserted some subcontent elements of type tile.

The data-array of subcontent elements do not have the filereference objects assigned.

In code I foud, that the method \MASK\Mask\Helper\InlineHelper->addFilesToData does not handle this special case.

The variable $table has in this case "tx_mask_tiles" as value which doesnt work here.
$storage has "tt_content" as only element, so line 78 will allways fail:
#78 if ($storage[$table]["tca"]) {

also $fieldHelper->getFormType($fieldKey, "", $table) will allways result in "String" as the table "tx_mask_tiles" is not existing in $GLOBALS["TCA"].

Ia am adding a patch, that works for my problem, but did not test, if it interferes, when subcontent is inserted via repeating of elements.
---------------
A further discussion about tihs is available here: https://forge.typo3.org/issues/77230

**Comment by butu** [comment]
Fixed in one of the latest commits :)

**Comment by DTM-TYPO3** [comment]
I think I might have the same problem Manfred is describing above. But it doesn´t work with mask 3.3.3 (I´m using TYPO3 8.7.24) eather.
I created a marker-element with title, description and image (file) which can be added to a parent map-element with some display options and checkboxes.
When I add a marker element as stand-alone element, the file reference is correctly set into an array. When I create a map-element and add a child-element (marker with image), the image is stored as string not as file-reference array.
What am I doing wrong or how can I fix this issue?

Thanks in advance,
Stefanie
