### ISSUE TITLE
Localisation not properly working (?)

### ISSUE THREAD

**Issue by hakuh** [Gernott/mask#121]
Working with TYPO3 8.7.10 and have problems with MASK 3.0.2 while translating nested Content Elements (although 'Localize Records when Content Element is localized' is enabled): In the backend I can see nested Content Elements if Localization Mode 'Keep the value or data from original language' is enabled, but not in the frontend. If Localization Mode 'Create Copy' is enabled, I can see nested Content Elements neither in backend nor in the frontend. Mask with e.g inline Richtext are working fine when i translate them.

**Comment by hakuh** [comment]
After 12 hours testing I found now a problem with my TYPO3 installation ... there are no problems with the localization using Mask.

**Comment by opaque01** [comment]
What was the problem?
