### ISSUE TITLE
Title of field is missing as a content manager in a workspace

### ISSUE THREAD

**Issue by TFaehrmann** [Gernott/mask#124]
When creating a new content element in an workspace as a content manager, the own created fields have no titles.

After saving the element the titles appear.
![mask_title_missing_bug](https://user-images.githubusercontent.com/25763366/36155595-10b98252-10d5-11e8-89c4-ef48e6e74bf1.JPG)

**Comment by nannione** [comment]
I confirm this behaviour. Occurs also if i create a mask element in a folder > field labels are wrong or missing.

Before saving:

![bildschirmfoto 2018-08-09 um 09 28 35](https://user-images.githubusercontent.com/7661543/43887554-1e5ced5a-9bb7-11e8-8df3-ff14ff9e9872.png)

After saving:

![bildschirmfoto 2018-08-09 um 09 28 48](https://user-images.githubusercontent.com/7661543/43887565-24d0d9d0-9bb7-11e8-806a-3a867684cfd9.png)

**Comment by Norcoen** [comment]
any idea on WHY that happens?

**Comment by nhovratov** [comment]
This works on current version (new in workspace, new in list module and new in element).
