### ISSUE TITLE
Can't preview mask content IRRE fields in workspace

### ISSUE THREAD

**Issue by rfoucard** [Gernott/mask#126]
In TYPO3 7LTS and 6.2, when I am in a workspace, if I change the value of a IRRE field in a mask content, the old value is previewed, I must publish the content to see the new value. But if I add a new item in the workspace, the new item is visible on the workspace preview. The problem seems to exist only when I change the value of a live existing item.

**The issues has been rejected in the forge today, the answer was "This is a core Issue. TYPO3 7.6 has some problems with workspaces."**

But I'm sorry to insist : I did exactly the same test with a not mask content and IRRE field before sending the issue, and there is no problem at all, with TYPO3 6.2, TYPO3 7LTS and TYPO3 8lts.

In addition, I did the same test today with an 8LTS version and here are the errors I get when I try to modify an IRRE item of mask content:

2: SQL error:'' Incorrect integer value:'' for column'' l10n_parent' at row 1'' (tx_mask_accordeon: NEW5a8d4aa988a79008952330)
1: Could not be edited in offline workspace in the branch where found (failure state:' Online record was not in versionized branch!'). Auto-creation of version failed!

So in the 6.2 (mask version 1.1.4) and 7LTS version (mask version 2.1.1), we can save the modification but the preview don't show the modifications, we have to publish to see them. In 8LTS (mask version 3.0.2), we can't save the modifications, and we get error messages.

Did we misconfigure the IRRE fields in our mask content?

Thank you in advance for your answers.
Rachel Foucard

**Comment by TFaehrmann** [comment]
Similar problem in Typo3 8. When I change an existing value in a mask element it wont show up in the preview when iam in a workspace.

In my case I can save a mask element without problems.

**Comment by opaque01** [comment]
Same problem here, no preview of nested CEs in a draft workspace.
TYPO3 8.7.20, Mask 3.3.2

**Comment by medarob** [comment]
I have the same problem in TYPO3 7.6.31 and MASK 2.1.1

When I edit a mask IRRE element in the workspace the changes are saved but the preview and the Backend shows older stuff. Submiting the changes without any review is not a real option...

It would be nice if someone could look into this matter.

**Comment by nhovratov** [comment]
This seems to work fine on current version. If you still encounter this error please reopen this issue, thanks!

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hi all,

I have the same issue, but NOT with repeating elements.

Problem: Can't preview changes in the backend when I'm in workspace.

Info:

- Backend template is a copy of the frontend template.
- Only happens with non repeating fields. Changes in reapeating fields are shown.
- Live-mode is okay
- Frontend is okay.
- When I jump into the content element to edit it, the changes are shown.

With <f:debug> I can see that the initial record is delivered but not the workspace record. Can you give me a hint what could be wrong?

TYPO3 9.5.23 and Mask 4.1.3
