### ISSUE TITLE
Support sitepackage structure

### ISSUE THREAD

**Issue by pixelbrackets** [Gernott/mask#127]
Hey Gernot, we discussed this with Jo Hasenau  and Kay Strobach at the T3CMD18.

Mask currently saves all generated files into a "fileadmin" folder. This is discouraged by the core. Instead all template files should be stored in a sitepackage, which is a simple wrapper extension for the configuration of a TYPO3 installation (since any folders like "fileadmin" should contain user uploads only).

This means, that is should be configurable that the generated files should be stored in an extension path. Of course following the official conventions for filenames etc.. 

Maybe you have some notes about the structure we scribbled.

**Comment by butu** [comment]
This is already possible since several versions. You can freely configure the path of your mask templates and the mask.json in the extension settings. There is no need to put the files in fileadmin.

**Comment by IchHabRecht** [comment]
I still recommend to use the mask_export extension to store all templates and generated configuration in an own extension. TBH I don't see any advantage to use mask with an own extension as you would still need in any other system.

**Comment by Gernott** [comment]
So, there is no issue or change request here. The discussion here is more part of the ticket #128. So we will close this one :)

**Comment by chris246** [comment]
Hi,

an idea for resolving that (at least partially):
Allow setting the path for the templates inside the Template instead of the Extension configuration.
