### ISSUE TITLE
Restructure configuration to allow removing EXT:mask on production but still enable rebuilding / adding new elements later

### ISSUE THREAD

**Issue by pixelbrackets** [Gernott/mask#128]
Regarding #127 we also talked about the need to store the mask configuration into a file which could be stored inside such a sitepackage and be used later by a mask to restart building content elements. 

Basically the same method as in the [extension builder](https://extensions.typo3.org/extension/extension_builder/) → it stores its own configuration into `Configuration/ExtensionBuilder/settings.yaml` and everytime the extension is opened again in the extension builder it loads this file first. Then the integrator may click whatever he wants to add, then the configuration and all generated files are overwritten again.

Advantage: EXT:mask could be installed in the dev system only, but the configuration is saved. The integrator could even decide to remove the configuration at some point.

**Comment by butu** [comment]
We are thinking about this. At the moment this is already possible via the extension mask_export. :)

**Comment by IchHabRecht** [comment]
Currently I don't see any way to use EXT:mask in dev systems only. If you don't save generated configuration, this will not be available in any other system. You can already define the location of the mask.json file and you are currently able to load multiple ones by changing this configuration in the extension manager settings. For even more comfort you could have a look at the pull request #40 (I like the idea but not the patch ;-) )

**Comment by chris246** [comment]
Hi,

an idea for resolving that (at least partially):
Allow setting the path for the templates inside the Template instead of the Extension configuration.

(Moved from #127)

**Comment by nhovratov** [comment]
This is exactly what EXT:mask_export does. Maybe this extension will someday be merged into mask.
