### ISSUE TITLE
Streamline license

### ISSUE THREAD

**Issue by pixelbrackets** [Gernott/mask#129]
The [license file](https://github.com/Gernott/mask/blob/master/LICENSE) uses GPL3, the [composer file](https://github.com/Gernott/mask/blob/master/composer.json) the deprecated value `GPL-2.0+`.

Either uses "GPL3", "GPL3 or later", or "GPL2 or later" in the complete project.

Also see https://typo3.org/typo3-cms/overview/licenses/

**Comment by pixelbrackets** [comment]
Please note: 

https://typo3.org/typo3-cms/overview/licenses/
> Extensions are essentially modifications of the original source code and therefore still fall under the GNU General Public License version 2.

**Comment by Gernott** [comment]
Thank you. Done.
