### ISSUE TITLE
Layout is broken when editing a long label

### ISSUE THREAD

**Issue by instruccionesaldorso** [Gernott/mask#137]
Using latest version EXT:mask 3.1.0.
When you're editing through the Mask module a label from a .xlf file in a field (and even in the case that the label was already defined and detected by Mask), the layout is broken because the label could be longer than the right part of the content area in the module (see screenshot attached)
![2018 03 16 12-46-28](https://user-images.githubusercontent.com/10220356/37519206-8a5a4082-2918-11e8-9e38-4a5645659409.jpeg)

**Comment by butu** [comment]
CSS in Backend module is kind of messy, so I had to set a fixed px value for max-width of field titles. But nevertheless this should prevent broken layouts :)
