### ISSUE TITLE
Two roots and not working

### ISSUE THREAD

**Issue by plojewski** [Gernott/mask#139]
Hi there,
I've got 2 pages with selected "Use as Root Page". When I add mask element with repeating:

1. on the first page works fine
2. on the second not

When I try to debug this mask in /content template:
<f:debug>{data.tx_mask_slider}</f:debug>
it says empty array.

Mask > 3.0

**Comment by Gernott** [comment]
I don't think this is a Mask Problem. We use it very often the same way.
It looks like you need support ;)
Have you included the TS-Template on both pages?

**Comment by plojewski** [comment]
Yes, TSes are the same. Mask works because I'm trying to add some html outside each:
`
    <div class="slider">
        <div class="inner">
            <f:debug>{data.tx_mask_slider}</f:debug>
<h1>test</h1>
            <f:for each="{data.tx_mask_slider}" as="data_item">
                <div class="item">
                    <div class="caption">
                        <f:if condition="{data_item.tx_mask_slider_title}">
                            <div class="line"><h2><f:format.raw>{data_item.tx_mask_slider_title}</f:format.raw></h2></div>
                        </f:if>
                        <f:if condition="{data_item.tx_mask_slider_subtitle}">
                            <div class="line"><h3><f:format.raw>{data_item.tx_mask_slider_subtitle}</f:format.raw></h3></div>
                        </f:if>
                        <f:if condition="{data_item.tx_mask_slider_text}">
                            <div class="line"><p><f:format.raw>{data_item.tx_mask_slider_text}</f:format.raw></p></div>
                        </f:if>
                    </div>
                    <div class="img">
                        <f:link.page pageUid="{data_item.tx_mask_slider_link}">
                            <f:if condition="{data_item.tx_mask_slider_image}">
                                <f:for each="{data_item.tx_mask_slider_image}" as="file">
                                    <f:image image="{file}" alt="{file.alternative}" title="{file.title}" width="940c" height="360c" />
                                </f:for>
                            </f:if>
                        </f:link.page>
                    </div>
                </div>
            </f:for>
        </div>
    </div>
`

and it shows, but nothing inside <f:for each="{data.tx_mask_slider}" as="data_item">
In BE it shows items properly.

**Comment by plojewski** [comment]
OK, you're right. Some my ts problem for this tree.
