### ISSUE TITLE
mask for TYPO3 9.x

### ISSUE THREAD

**Issue by luberti** [Gernott/mask#146]
Sorry to use this space, but I cannot find this information anywhere: are you planning to port mask to TYPO3 9.x ? If yes, are you planning to proceed only after TYPO3 9 becomes LTS? TIA for the answer

**Comment by Gernott** [comment]
Yes, we plan at least a version for TYPO3 9 LTS. But we don't have a detailed plan or supporter at the moment. If interested, contact us via webprofil.at
