### ISSUE TITLE
Set content template file via TypoScript?

### ISSUE THREAD

**Issue by ursbraem** [Gernott/mask#15]
As with temp.mask.page, I would like (or rather, need) to define a custom template location for temp.mask.content items in TypoScript.

That's possible, isn't it? 

I expected something like
```
content < temp.mask.content
content.select.where = colPos=1
content.settings.file = path/to/content-template.html
```
but that doesn't work, obviously. 

I saw there is some PHP related to that in `Resources/Private/Mask/setup.ts` (`settings.file = ###PATH###`) but I'm not sure if that's it... 

Following that lead, I tried setting tried `mask.tt_content.mask_elementkey.settings.file = path/to/elementtemplate.html`, no luck either.

I know this isn't stackoverflow, but I'd really appreciate hint. I feel like I'm missing a basic puzzle piece...

**Comment by Gernott** [comment]
Fluid styled content is not fully compatible yet, because mask v1.x supports also TYPO3 6.2.
I'm not sure what you need. Mask delivers an own HTML Template for each Contentelement...?
Look at /fileadmin/templates/content/*

If you wish a new feature or found a bug, please report it on forge: https://forge.typo3.org/projects/extension-mask

If you use TYPO3 7, use styles.content.get instead of temp.mask.content. Our snippet is only good for TYPO3 6.2, because content for all languages is not respected by styles.contet.get there.

**Comment by ursbraem** [comment]
If it turns out to be a feature, I'll report it on forge.
But let me clarify first, I think i haven't described it clear enough:

- I planned not to use css_styled_content nor fluid_styled_content - just basic TYPO3 plus fluid plus mask. So I disabled both of them. Can I also disable the mask static.ts if it turns out I don't need it? Would the backend stuff still work fully?

- Mask delivers the HTML template, yes. But how do I vary that template if I want to reuse "mask" content from one page on another? Like in news: Latest view, List view, Detail view.  That's the thing I'm looking for

- Last AND least, another reason for my request was that I'd like to split up the location where the generated templates from mask are stored, and where the ones I customize are stored. -> maybe that will become a feature request?

thanks....

**Comment by ursbraem** [comment]
After a lot of pondering, I rewrote the question...

**Comment by ursbraem** [comment]
Ok, I'm closing this. I've found out the following:

- Mask doesn't overwrite the templates in /content when you edit an element, so that's fine
- On the above mentionned SO post, I learned how to read the content and parse it with fluid

like this:

```
lib.test = CONTENT
lib.test {
  table = tt_content
  # language uid -1 (all) not supported in TYPO3 7.6
  select.languageField = sys_language_uid
  select.selectFields = bodytext,image,header,header_link
  select.where = colPos = 1
  renderObj = FLUIDTEMPLATE
  renderObj {
    file = path/to/my/fluid/template.html
    dataProcessing {
      // https://docs.typo3.org/typo3cms/TyposcriptReference/ContentObjects/Fluidtemplate/Index.html
      // available data processors: SplitProcessor, CommaSeparatedValueProcessor, FilesProcessor, DatabaseQueryProcessor, GalleryProcessor
     // prep images
      10 = TYPO3\CMS\Frontend\DataProcessing\FilesProcessor
      10.references.fieldName = image
    }
   // if you need a setting, e.g. for a condition
    settings {
      type = some_setting
    }
  }
}
```

So I disabled the mask static TS template and think I'll do all the content rendering with "Bordmittels".
Please let me know if you think that's a bad Idea and why.

PS: did I say I'm very grateful for mask? Its' super important to be able to quickly create and modify backend ... masks.. Thanks!

**Comment by fjacobi** [comment]
I had a similar case where I had to present content depending on its page/colPos and I used Fluid sections for that.

**Comment by Gernott** [comment]
Thank you for your informations. It looks very very interesting. We will respect it in Mask 2.x and/or in our manual. Mask 2.x is no longer compatible with TYPO3 6.2 - so we can use more modern things ;)
Thanks for your feedback!

**Comment by ursbraem** [comment]
If I can be of any help, also with documentation, let me know!

**Comment by ursbraem** [comment]
PS: I've made a little boilerplate, mostly for internal use, that follows this approach (fsc with TS, mask "hand-rendered"): https://bitbucket.org/stubr/typo3-boilerplate/src/
