### ISSUE TITLE
Mask Element Header fields

### ISSUE THREAD

**Issue by KaiBroenstrup** [Gernott/mask#150]
I cant see the normal Typo3 Header fields in my mask element.
How can i turn that on?

**Comment by Gernott** [comment]
Simply add the header field to your element.
This is not a Support forum. Please use Stackoverflow, Slack, typo3.net, ... for free support or find more info at mask.webprofil.at for payed support.

**Comment by kitzberger** [comment]
@Gernott, would be great to be able to reuse the whole 'header' palette. Like it's possible to reuse a single field. Just a thought ;-)
