### ISSUE TITLE
Patch for select renderType selectMultipleSideBySide for enabling the filter wizard

### ISSUE THREAD

**Issue by sg-paul-ilea** [Gernott/mask#152]
I've wrote a patch, allowing the enabling of the filter textfield for renderType:selectMultipleSideBySide select fields.
[addSelectRenderTypeMultipleSideBySideFilterConfiguration.diff.zip](https://github.com/Gernott/mask/files/2115495/addSelectRenderTypeMultipleSideBySideFilterConfiguration.diff.zip)

**Comment by sgalinski** [comment]
@sg-paul-ilea Please create a real pull request. :-)
