### ISSUE TITLE
Patch for extending the l10n_mode configuration to all field types

### ISSUE THREAD

**Issue by sg-paul-ilea** [Gernott/mask#153]
I've wrote a patch that allows the user to specify the l10n_mode for all field types. I've also changed the "copy" option to Default("") since it's been removed since typo3 v8.
[addL10NModeConfigurationOptionsForAllFieldTypes.diff.zip](https://github.com/Gernott/mask/files/2115518/addL10NModeConfigurationOptionsForAllFieldTypes.diff.zip)

**Comment by sgalinski** [comment]
@sg-paul-ilea Please create a real pull request. :-)
