### ISSUE TITLE
Useful error message if mask.json could not be rendered

### ISSUE THREAD

**Issue by josefglatz** [Gernott/mask#156]
Could an error like the following one

```
[ TYPO3\CMS\Core\Error\Exception ] Warning: array_keys() expects parameter 1 to be array, null given in
/home/myfancyserver/web/htdocs/app/releases/20180625173954/web/typo3conf/ext/mask/Classes/CodeGenerator/SqlCodeGenerator.php line 144 
```

be catched? Or maybe it is possible to check the syntax of mask.json?

**Comment by Gernott** [comment]
A JSON-check is not planned. Would you like to write any? Or sponsor this feature?
In both cases, we would need a short concept (where to build in, what does it do in detail,...)

**Comment by Findus23** [comment]
Shouldn't a simple check for [`json_last_error()`](https://secure.php.net/manual/de/function.json-last-error.php) be enough to detect if the json failed to parse?

**Comment by nhovratov** [comment]
![Screenshot_2020-09-26 TYPO3 Exception](https://user-images.githubusercontent.com/19343425/94342990-5ed0fd80-0015-11eb-9828-0fdd7b3eaf0f.png)

In current TYPO3 version a syntax error will look like this thanks to symfony polyfills. I think this should be enough.
