### ISSUE TITLE
Repeating elements and language fallback

### ISSUE THREAD

**Issue by beyring** [Gernott/mask#158]
Hi, 

we are having a problem with repeating elements and langauge fallback:

we are working with sys_language_mode = content_fallback; 1,0

The mask content element fallback to language with uid=1 is working correct, but the repeating elements of that content element do not show up in the data object.

Can we solve this changing any configuration or is this an issue inside of mask extension?

Thanks in advance and best from munich,
Ben

**Comment by mkuehnel** [comment]
I have the same Problem with repeating elements (and only with repeating elements)
Is there any solution or is it a bug? Any chance to get this solved in future versions?

Best regards
Mortiz

**Comment by butu** [comment]
Content fallback for repeating elements isn't a trivial thing unfortunately, and hasn't been tackled yet.

You can PR a solution or sponsor this new feature :)

**Comment by dogawaf** [comment]
Hello. 

An idea of what needs to be done in order to fix this issue?
I would be able to start a PR, but I don't know where to start.

**Comment by Teisi** [comment]
I have fixed this - please try and test:
https://github.com/Hauer-Heinrich/mask/tree/v3.3.4

simple changed:
Classes/Helper/InlineHelper.php
line:246 and 258 - from $sysLangUid to $data['sys_language_uid']

**Comment by ikonplant** [comment]
The patch of @Teisi is resolving the issue for me.
TYPO3 8.7.27, mask v3.3.3

@Gernott @butu Could you recheck that and fix it in the mask?

**Comment by opaque01** [comment]
Does this also work in the current mask version or is it already implemented in the current MASK version?
