### ISSUE TITLE
Mask Does not support CE and automatically ce disappeared.

### ISSUE THREAD

**Issue by manishjaingit** [Gernott/mask#16]
In my current project I have this setup : 
Typo3 CMS 7.6 LTS
mask 1.1.2
and basic pre installed extension.

when i create content from the Mast backend plugin, i can create it and use it to show in frontend as well, but after a time i again edit the content and create new i have seen the old one was automatically removed itself,. or some times file does not found in content directory or some times whole keyfield got missed. i have tried to encontered the issue but doesnot succeeds , can anyone having same issue. and resolved it? i am no longer able to use Mask for template mapping.

**Comment by butu** [comment]
Well, that's hard to debug. We can't reproduce this phenomenon. Could you grant us access to your installation, or a dev environment where we could test this? Contact me via mail if possible: bb[at]webprofil[dot]at

**Comment by graurus** [comment]
Have you used keys from previously CE?
If yes, then you have to redo the CE(or fields) with unique keys.

**Comment by manishjaingit** [comment]
no, i have used new key with each records,

Danke :)
Best Regards,
*Manish Jain <http://in.linkedin.com/pub/manish-jain/51/112/b96/en>*
TYPO3 Project management and Development (PHP5 / TYPO3, Fluid, Flux,
extBase)
