### ISSUE TITLE
Error output in FE by creating new element "Link"

### ISSUE THREAD

**Issue by angeloprevitali** [Gernott/mask#160]
If you create a new MASK element and if you add a new CE element called "link" the output in the FE is wrong, if you use a target=_blank and a title in the link.

The output is like this:
`<a href="https://www.mywebsite.ch" title="My title of the link" target="_blank">https://www.mywebsite.ch _blank - "My title of the link"</a>`

I saw that this bug was also already in older versons the the new one 3.2.0.

Is there a solution or is it really a bug?

Thank for help.

**Comment by Gernott** [comment]
Is your linkfield inside of a f:link.typolink?

**Comment by angeloprevitali** [comment]
I created this one marked:

![mask1](https://user-images.githubusercontent.com/17588253/43253328-ff7aa3b6-90c4-11e8-9ccf-41396661f7ab.png)

and get the following FLUID code to implement 

`<f:if condition="{data.header_link}">
<f:link.typolink parameter="{data.header_link}">{data.header_link}</f:link.typolink><br />
</f:if>`

This generates the following HTML output
`<a href="https://www.mywebsite.ch" title="My title of the link" target="_blank">https://www.mywebsite.ch _blank - "My title of the link"</a>`

**Comment by Gernott** [comment]
Perfect, it works as expected. It shows the value of the field as linktext.
You need Fluid to change the Linktext to something different. Have a look at f:uri

**Comment by angeloprevitali** [comment]
Well, I don't know exactly if this really works like it should be. I am wondering because in the BE of the MASK the autogenerated FLUID Code gets me exactly this wrong FLUID code as proposal that gets me the wrong HTML output in the FE. Is that really correct what it generates?

![mask2](https://user-images.githubusercontent.com/17588253/43254344-7b3e99f6-90c7-11e8-9680-dfa670605b71.png)

**Comment by Gernott** [comment]
Mask offers only an example code. Adapt the code for your needs. It is not a wrong Fluid code - it is simply not what you need for your project.
Perhaps you have a better general Fluid snippet for Mask. Feel free to make a Pull request with a correction.

**Comment by angeloprevitali** [comment]
Thx for your quick response. Now it is clear for me. 

Best regards,
Angelo
