### ISSUE TITLE
Folder for mask.json should be created

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#164]
Reproduce:
1) change the storage folder for the mask.json to a not existing folder
2) create a contentelement
3) save it. You get an exception.

Possible solutions:
- check, if the folder from the mask.json exists, as be done for the frontend folders (also check all other folders?)
- auto-create the folder on saving in the Mask BE-module
- don't allow to work in the Mask BE-module, when it is not possible to save

**Comment by butu** [comment]
There is now a big warning that not all folders / files are existing. With one button you can create them all. :)
