### ISSUE TITLE
Fieldtype Content doesn't work

### ISSUE THREAD

**Issue by Balindil** [Gernott/mask#170]
I am trying to use the field type "Content". But even if I use the standard fluid template:
```html
<f:if condition="{data.tx_mask_inhalte}">
    <f:for each="{data.tx_mask_inhalte}" as="data_item">
        <f:cObject typoscriptObjectPath="lib.tx_mask.content">{data_item.uid}</f:cObject><br />
    </f:for>
</f:if>
```
I don't get any output in the frontend except the `<br />`

**Comment by butu** [comment]
Have you included the mask typoscript template?

**Comment by Balindil** [comment]
Yes, I have created several other elements with masks and they all work.

**Comment by Balindil** [comment]
Shame on me. I just see that I didn't include the tyoscript template. Strangely enough, the other mask elements still worked.

**Comment by butu** [comment]
Yeah, the other elements work, because they don't need special typoscript. The Fluid Template for rendering content needs lib.tx_mask.content, which is included in the mask typoscript template :)
