### ISSUE TITLE
Using Repeating element throws error: There is no entry in the $TCA array for the table ...

### ISSUE THREAD

**Issue by chris246** [Gernott/mask#171]
Hi,

when using repeating elements, my TYPO3  (version 7.6.31) installation logs an error: 

Core: Exception handler (WEB): Uncaught TYPO3 Exception:  #1283790586: There is no entry in the $TCA array for the table  "tx_mask_accordion_elements". This means that the function  enableFields() is called with an invalid table name as argument. \|  InvalidArgumentException thrown in file  [...]/typo3_src-7.6.31/typo3/sysext/frontend/Classes/Page/PageRepository.php  in line 1203. Requested URL:  [...]

I've already tried to re-create the mask content element and deleted the old field definitions from the database using the install tool.

Kind regards,
Christoph

**Comment by chris246** [comment]
No problem :)
In the meantime, we migrated to TYPO3v8, there it works.
As TYPO3v7 is now EOL, I think we can close this.

**Comment by butu** [comment]
Cool, Thank you! :)
