### ISSUE TITLE
Link Wizard options get lost after saving

### ISSUE THREAD

**Issue by webdev2027** [Gernott/mask#174]
Hello.

Insert a link-element and set options like validation -> Deactivate FIle: YES   Mail: YES   Page: YES   Folder: YES   URL:  NO, or size of link wizard .. see screenshot.

After saving, all adjustments are gone. Only required is still true.?!

Choose:
![bildschirmfoto 2018-09-14 um 08 14 59](https://user-images.githubusercontent.com/5501876/45533129-e2d13780-b7f6-11e8-80a4-320d30c4c4f4.png)
Saving:
![bildschirmfoto 2018-09-14 um 08 19 50](https://user-images.githubusercontent.com/5501876/45533157-f8def800-b7f6-11e8-9cf0-299b224ac152.png)

**Comment by Max-LAB** [comment]
I also can confirm this error on Typo3 8.7.7 Mask version 3.1.0 I tried to change a Wizard width and height. Change is applied after I click save. When I come back to extension, and change for example Title field, width and height will return to default values w: 500 h: 300

**Comment by butu** [comment]
Thank you for your input! This is now fixed in master! :)
