### ISSUE TITLE
typo3 9.5.0 doesn't render mask content elements

### ISSUE THREAD

**Issue by marian-bcdm** [Gernott/mask#179]
Testing typo3 9.5.0 and mask 4.0.0.

By default mask created folders in EXT:yoursitepackage/Resources... (previous version went to fileadmin directly).

Issue: after creating new mask content element file apears in the default folder, but typo3 doesn't see it (there is no "mask-element" item listed among other kinds of content to choose). And also mask extension doesn't list it. 

When I manually change the default folder to fileadmin path, mask lists this element, mask-elements option appear in the items selection tabs when creating new content element, but then i can't save my new mask item it as it returns an error:
2: SQL error: 'Unknown column 'tx_mask_new' in 'field list'' (tt_content:NEW5bbba19224321764998739).

Is there anything special to do about the newest version of mask installation/configuration with the newest typo3? My previous project (typo3 8.7.15 and mask 3.3.1. worked just fine without any extra adjustments).

**Comment by butu** [comment]
Could you post your mask.json?

**Comment by marian-bcdm** [comment]
I am sorry, I didn't make any commits as it was for first time testing, and the original mask.json is gone, but I think this is what you receive with the default installation without any adjustments. 

Later on I uninstalled Mask and installed it again, directing the folders to my typo3conf/ext folder before accepting folders creation message, and this time creating content elements looks to be working, But now I am trying to execute pagetemplates with mask and still can't get it. Hopefully will have some result soon.

I wrote my message as it was little confusing - previous versions (typo3 8.7.15 and mask 3.3.1. ) was ready to use right out of the box (cool) but was placing mask folders in fileadmin (not so cool). Right now out of the box installation doesn't work, and I had to try many times where to place the folders remembering to do it right after installation and before accepting folders creation. Could be more helpul if more details on the topic were given in the installation manual. I would gladly help to write it, but I still trying to figure out what way should be considered as good practice and I don't know if I am doing the thing right or wrong. New Typo3 and new Mask are both really fresh, and it needs some extra time to test them well. Btw I am testing at the same time also new Bootstrap package and in this case Fluid Styled Content should be placed before it, and Mask after, otherwise front end renders extra errors.

**Comment by Typine3** [comment]
I have a similar issue - upgraded an 8.7 project with mask elements to 9.5.0 yesterday, upgraded mask from 3.3.2 to 4.0.0 today and now nothing is working like before! Is there an upgrade process? I already found out that I have to copy mask.json from typo3conf to the sitepackage directory, but my .html Frontend Templates are not recognized, though located in the configured directories, and a newly created element doesn't produce a .html Template in the configured directory...Would be thankful for an idea - up to now I found this a really great extension!
![fehlermask](https://user-images.githubusercontent.com/42004143/46864287-334dac00-ce1a-11e8-8cba-4fab0c4e2eb9.jpg)

**Comment by Typine3** [comment]
Meanwhile I realized that mask doesn't seem to recognize that the configured directories are within a layout extension (in my case named cb_proto8). I saw that when I pressed the button "Create missing directories" it created "EXT:cb_proto8" as a directory directly in the project directory (in the same layer as fileadmin, typo3_src, typo3conf... usw) which is really strange!

**Comment by Typine3** [comment]
Lösung: Bei der Konfiguration von Mask durfte ich nirgends "EXT:name_layout_extension/..." schreiben, sondern musste den Pfad so angeben: "typo3conf/ext/name_layout_extension/..." usw.
Jetzt geht alles. Da ist der vorbelegte Wert in den Konfigurationsfeldern irreführend.

**Comment by butu** [comment]
Merged! :)
