### ISSUE TITLE
Nested content element isn't rendering internal links / order of elements won't be updates V3.3.2

### ISSUE THREAD

**Issue by angeloprevitali** [Gernott/mask#182]
If you create a new MASK element with a repeat element, a title and a rte element the two folling things are wrong:

1. The single elements can not be ordered anymore after saving once
2. The nested content elements daes not renders internal links. it gets the default t3:// links in the fe.

MASK version: 3.3.2
TYPO3 Version: 8.7.19
PHP: 7.1

**Comment by faltrock-abone** [comment]
I fixed sorting in #181, and the fix is small enough that it could be backported to 3.3.x. 

In the meantime you could name your fields so they will sort alphabetically in the order you want. Like f01_text, f02_author instead of author, text. I know it's clunky, but it works.

**Comment by butu** [comment]
PR #181 is merged on master! :)
