### ISSUE TITLE
Mask fields not included in backend search function

### ISSUE THREAD

**Issue by Schweriner** [Gernott/mask#191]
I've got a TYPO3 8 LTS System using Mask 3.3.2. 

When using the search function of the backend, it does not find Mask CEs which contain matching contents to the search string.
Maybe Mask should add new fields to the 'searchfields' of tt_contents TCA?
https://docs.typo3.org/typo3cms/TCAReference/Ctrl/Index.html#searchfields

**Comment by s-thierock** [comment]
Is nobody missing this feature?
In my customer training sessions, I always have to say, "You can search for content elements here, except ...".
