### ISSUE TITLE
Double relations when using records in repeating elements

### ISSUE THREAD

**Issue by AstCommodore** [Gernott/mask#199]
First of all, thank you for this wonderful extension!

I've got an ugly bug when using the record type as sub-element in repeating Mask elements:

I use two Mask elements with repeatings

- tx_mask_panel
- tx_mask_flexbox

Both elements use the record type for their childs to insert tt_content. So the field tx_mask_record_parent in tt_content is filled with the uid of the Mask child.

If you have a tx_mask_panel child with uid 10 and a tx_mask_flexbox child with the same uid and you insert a tt_content record in both Mask elements/childs, the field tx_mask_record_parent is set twice with uid=10.

The result will be Mask childs with two tt_content records, the two different tables (for the Mask elements) are mixed up!

=> Mask doesn't differ between different parent tables/elements in field tx_mask_record_parent.

**Comment by nhovratov** [comment]
Easy solution is simply to not allow content fields with same key. Otherwise renaming them to make them different would result in breaking changes..
