### ISSUE TITLE
Backend: In the List-view are all created Content Elements with "[No title]" labelled.

### ISSUE THREAD

**Issue by 8bamo** [Gernott/mask#200]
Is there a way to display the Titles ?

**Comment by butu** [comment]
You have to use the header field in mask. In the content element create a field, use the header field and let  the editor fill that field :)

**Comment by jonaseberle** [comment]
The List Module shows the column `tt_content.header` by default as title.

![image](https://user-images.githubusercontent.com/1678001/89999424-0f19bb00-dc8f-11ea-8988-09338c4514ce.png)


@butu could you explain a bit how it is possible to make mask elements that show this column to the editor?

Is there a special field type?

![image](https://user-images.githubusercontent.com/1678001/89999335-f3161980-dc8e-11ea-9ebe-5e2e2afec3da.png)


So far we exported mask elements and re-added the palette "header" in TCA then. 
Wouldn't it make sense if https://github.com/Gernott/mask/blob/7c75e7f6b80e055617ce8314850871ddfc5ba2c6/Classes/CodeGenerator/TcaCodeGenerator.php#L121 would add the default tt_content palette "header" already?

Your answer suggests that there is another solution?

**Comment by jonaseberle** [comment]
Sorry, I was silly... I found it.

Add a text field and choose existing field -> "header".

![image](https://user-images.githubusercontent.com/1678001/90000633-b77c4f00-dc90-11ea-8817-45dda50bcff4.png)
