### ISSUE TITLE
Problems with MASK repeating elements in workspaces 

### ISSUE THREAD

**Issue by kklefenz** [Gernott/mask#201]
After a migration to TYPO3 9.5.1, I have problems with MASK 4.0.0 in relation with Workspaces. If I edit content elements (content, string and text fields) in a repeating field, the elements are displayed multiple times in the preview, the original version and edited ones. I could bypass it by adjusting the database query in InlineHelper, so it doesn't include elements with pid=-1. Don't know if this is the correct way to fix it, but it works for me. The backend however is displaying (before and after this fix) only the unedited version. Other (Mask and not Mask) elements work with Workspaces as intended.

**Comment by butu** [comment]
Thank you for your bug report. I think this is the same problem as in #199. Therefore I will close this ticket and continue with the other one :)
