### ISSUE TITLE
It's not possible to link to a nested Element / "repeating item"

### ISSUE THREAD

**Issue by wtdesign** [Gernott/mask#202]
If you create a MASK item with the "repeatability" option, you can not link to the desired repeat item. You only can link to the complete MASK item.

**Comment by wtdesign** [comment]
Usually you can put links in normal content elements. You can then link to a page, an external URL, an email address and "content items". Content items is the magic key.

From a normal content item, I can link to a complete MASK element, but not to a repeating part of a MASK element. So I want to link in a part of the MASK item (content item), but it's not possible.

If I manually set IDs with fluid, it is possible to set these links using external URLs. For an editor, however, this is impossible because he does not know it. That makes it more caring.

**Comment by nhovratov** [comment]
You need to setup a linkhandler if you want to refer to another table (like repeating elements are): https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ApiOverview/LinkBrowser/Linkhandler/Index.html

**Comment by matthaa** [comment]
Hi,
i would like reopen this issue since this is exactly my question too. Linkhandler is not working although there is a database table for the repeating element, e.g. "tx_mask_element". 
This code doesn't show any record in the linkbrowser:
```
TCEMAIN.linkHandler.mask {
    handler = TYPO3\CMS\Backend\LinkHandler\RecordLinkHandler
    label = LLL:EXT:extension/Resources/Private/Language/locallang.xlf:link.customTab
    configuration {
        table = tx_mask_element
    }
}
Probably because repeating elements use IRRE technique. 
Do you have any hint? Thanks a lot,
Matthias

**Comment by nhovratov** [comment]
@matthaa It could be because Mask Repeating tables are always set to TCA ctrl `hideTable` true. Try to override this to false and they should appear.

**Comment by matthaa** [comment]
Great, that works. Thank you!
