### ISSUE TITLE
Static $json in StorageRepository prevents configuration overrides by extension ext_localconf.php

### ISSUE THREAD

**Issue by the-coding-owl** [Gernott/mask#207]
Is there a reason why the variable that holds the mask json configuration is static in the `StorageRepository`?
At least for me this prevents a configuration of the configuration path in my site package extension.

I've got the following scenario:

In `LocalConfiguration.php` the configuration is set to `EXT:yoursitepackage/Resources/Private/Mask/mask.json`. So far I thought, whatever, I can change that in my `ext_localconf.php` to `'EXT:' . $extKey . '/Configuration/Mask/mask.json'`. Now at some point in execution, the `StorageRepository` gets initialized with data from the `LocalConfiguration.php` and the static `$json` variable becomes an empty array because of the `load()` function. This is now bad, because later the `StorageRepository` would get initialized with the correct extConf, but the `load()` function jumps over the check for `self::$json === null`, because it is an empty array now.

I see two solutions here:

1) Make StorageRepository a Singleton and remove the static from $json. The class is mainly working with the static $json and the respective JSON file, so why not?

2) Make the check in `load()` check for `empty` instead of `=== null`. This way, the JSON configuration could be loaded, after a previous load with bad configuration data failed.

**Comment by kaystrobach** [comment]
Call Path:

```
ext_localconf.php:8 -> $storageRepository = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('MASK\\Mask\\Domain\\Repository\\StorageRepository');
ext_localconf.php:12 -> $configuration = $storageRepository->load();
Classes/Domain/Repository/StorageRepository.php:99 -> self::$json = json_decode(file_get_contents($file), true);
```

Struggeld about the same problem, as we tried to set the path the the json file via ext_localconf.php

I wonder why the reository is initiated in the ext_localconf already and not with the hook providing the overrides.

**Comment by IchHabRecht** [comment]
Hi @the-coding-owl 

> 1. Make StorageRepository a Singleton and remove the static from $json. The class is mainly working with the static $json and the respective JSON file, so why not?

This wouldn't change anything as the singleton would still load the very first json file. IMHO the whole configuration setting should be moved outside the ext_localconf.php and should be initialized within an own hook (e.g. after all configuration was fetched by the core).

**Comment by nhovratov** [comment]
Yep, or if you don't want to edit the settings in the backend extension configurations you can still use AdditionalConfiguration.php
