### ISSUE TITLE
Mask 4.1.0 with Typo3 9  Not all fields are created in database after saving

### ISSUE THREAD

**Issue by ronnyboenisch** [Gernott/mask#209]
Mask 4.1.0 and Typo3 9 
After saving a content element, some fields were not created in the database. I had to cretaed them directly in the database.
Affected 2 Richtext fields so far.

**Comment by edekowalski** [comment]
Dear Ronny, please go to Installtool an make a Database Compare.

**Comment by butu** [comment]
I could not recreate this behaviour. Can you? Would you mind sending me your mask.json?

**Comment by ronnyboenisch** [comment]
@edekowalski I I had already tried this that day, but without success.
@butu I have changed the content element in the meantime and unfortunately don't have the old mask.json anymore.  The error occurred with fields at nesting depth 3, but I can't reproduce it anymore.
