### ISSUE TITLE
mask exception

### ISSUE THREAD

**Issue by pt-webprofil** [Gernott/mask#210]
<img width="1157" alt="bildschirmfoto 2018-12-13 um 14 39 54" src="https://user-images.githubusercontent.com/34335026/49942255-151d2e80-fee5-11e8-8310-da4cf31f1d46.png">

**Comment by gerchomat** [comment]
Bump, same issue here

**Comment by gerchomat** [comment]
The error happens if i edit an existing element and add them an existing field.
In my case i have an repeater with string, richtext and image and want to add them an toggle switch.

TYPO3 9.5.5
Mask 4.1.0

**Comment by pf-informatik** [comment]
Same here (same versions, same way to reproduce).

An additional side effect: The mask element you wanted to edit is deleted from mask.json as soon as you see that exception.

A "workaround" if you cannot disable PHP warnings in php.ini: go to Settings/Configuration Presets/Debug settings and switch to LIVE. With this you set the PHP logLevel to a lower level where warnings are ignored/not displayed.
After that you can edit and save the mask element. You may change back the debug settings.

**Comment by PPP01** [comment]
Same error here. After reading that it seems to work with the workaround (disable PHP warnings) I did a very simple fix and it works pretty fine (AFAIK)

**Comment by Gernott** [comment]
Merged, thank you :)
