### ISSUE TITLE
E_USER_DEPRECATED Warning in TYPO3 9

### ISSUE THREAD

**Issue by CDRO** [Gernott/mask#215]
It seems that TYPO3 9 has a really strong opinion about using deprecated functionality and does almost not allow you to disable the deprecation warnings if not setting `displayErrors` to `0`. This is clearly no issue of mask, **but** it points out things that should be solved in the near future.

And here comes my issue: in `ext_localconf.php` there is a call to `$sysPage->getRootLine` which should be replaced by `RootlineUtility`.

I've prepared  a bugfix for this and will start a PR asap.

Best Regards
Tizian

**Comment by nhovratov** [comment]
This can be closed, thanks.
