### ISSUE TITLE
lib.tx_mask.content and translation

### ISSUE THREAD

**Issue by plojewski** [Gernott/mask#218]
Hi,
I use Typo3 7.6.31 and Mask 2.1.1.
I've got repeating element and template:

`
                        <f:if condition="{data_item.tx_mask_content}">
                                <f:for each="{data_item.tx_mask_content}" as="data_item_item">
                                    <f:cObject typoscriptObjectPath="lib.tx_mask.content">{data_item_item.uid}</f:cObject>
                                </f:for>
                        </f:if>
`

When I add some Content element in default language, <f:debug>{data_item.tx_mask_bar_content}</f:debug> returns array with elements and it's ok.
But when I add Mask on translated page, Content elements added to this has different sys_language_uid (than whole Mask instance) and <f:debug>{data_item.tx_mask_bar_content}</f:debug> returns NULL.

Have you any idea how to fix it?

**Comment by jonaseberle** [comment]
I just got the same in an 8.7 instance I adopted so I cannot be sure if the language config is really correct.

When I select "All" for the language of the inline elements they get selected.

**Comment by nhovratov** [comment]
Seems to work on current version.
