### ISSUE TITLE
mask, gridelements, colpos and backendlayouts

### ISSUE THREAD

**Issue by tsurfer84** [Gernott/mask#219]
Hello there,

big problem using EXT:gridelements and EXT:mask parallel and dealing with nested content.
Just by changing the backendlayout, all content that is nested in a mask-contentelement loses its "mask-nested-content"-column, which is by standard 999. Afterwards, the inside-contentelement just is at colpos -2 (error: not allowed) and won't be displayed.

To reproduce do the following:
- install gridelements and mask
- create two ore more different backendlayouts
- use a mask-contentelement, in which you can nest any further content
- create further contentelement in mask-mother-element and save
- have a look at the column-dropdown of the nested contentelement. it points to "mask-nested-content"
- change the backendlyout of the page, in which both contentelements are in
- have a look oncemore at the dropdown of the nested-contentelement. it now points to colpos -2 and displays an error.

Without EXT:gridelements, all is fine.

What is happening here, how can I solve the problem?

Thanks a lot in advance!

**Comment by Bunnyfield** [comment]
Since Gridelements checks the available columns and moves elements to the "unused" column (-2) when columns are missing, you've got two workaround in this case:

Add a column 999 to your page backend layouts and make it invisible for editors

Anything else would IMHO require a change either in Gridelements or in Mask or maybe even both.
Should be discussed before though.

**Comment by tsurfer84** [comment]
Thanks Jo!

This works fine, but unfortunately it displays col #999 in backend. 
If disabled, it still appears as a red column for editors with hint "no edit access".

Any other solutions?

**Comment by Bunnyfield** [comment]
That's the only workaround so far that can help you until there is a real fix.

**Comment by tsurfer84** [comment]
Thank you, I can live with that!
