### ISSUE TITLE
Help text for editors

### ISSUE THREAD

**Issue by chris246** [Gernott/mask#220]
To improve usability for backend editors using mask content elements, it would be very nice if help texts could be provided by the creator of a content element (=administrator/integrator).

Currently, there is only the possibility to add a placeholder to some inputs.

I have two ideas for this:
1. Add a new attribute help_text on input elements that hooks with TYPO3's context sensitive tool tip texts and is editable using the Mask backend module.
2. Allow adding non-input elements (description element) using the Mask backend module, that are visible only in the backend when using the mask element and can contain multiple lines of text (maybe using RTE for filling it).

**Comment by fjacobi** [comment]
Perhaps the integration of the new description option is already enough?
https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.4/Feature-85410-AllowTCADescriptionProperty.html

**Comment by chris246** [comment]
This doesn't look bad, but as I understand it, this is a feature only for TYPO3 v9.

This description would then be definable when creating/editing a mask element?

**Comment by fjacobi** [comment]
Well, developing new features for the old lts seems kinda "wasted". 
Without an existing TCA solution, mask would have to change quite a lot, wich seems like a lot of effort for a target group that is becoming smaller every month.

**Comment by chris246** [comment]
Ok, that makes sense.

**Comment by butu** [comment]
I added the possibility to set a tca description for fields in master. Will be released with the next version :)
