### ISSUE TITLE
Selectbox and radio button do not work.

### ISSUE THREAD

**Issue by lenjka01** [Gernott/mask#221]
I'm trying to create an extension where I can select with a Selctbox about 20 options.
For this I create a select box with a new field in the database. 

If I then select and save an option, nothing will be written to the database: the variable is NULL. 
After saving the contenelement, the first option is displayed again.

**Comment by afle** [comment]
Something similar here. But we noticed, that using a select box values are written to the database (format "option1,option2,option3". But it's not being read when opening the contentelement included the select box.
So you do not see, which option was selected and if you save the contentelement without selecting the option again, the appropriated database field will be emptied.

Testet versions: 3.3.0 and 3.3.3.

**Comment by butu** [comment]
Could you post your mask.json, because I cannot reproduce this bug. I created a selectbox and also a radiobutton field, but both of them work as expectet. Thank you :)

**Comment by afle** [comment]
Here you can find the mask.json:
[mask.zip](https://github.com/Gernott/mask/files/3033712/mask.zip)

Thanks!

**Comment by butu** [comment]
Hi, 
you always need to set label and value for each option. Unfortunately mask does not validate wrong inputs in the options field at the moment.

So instead of 

```
Institute
Ecology
Genetics
Human Evolution
Primatology
```

you have to write

```
Institute,inst
Ecology,eco
Genetics,gen
Human Evolution,evo
Primatology,prim
```

Does this fix your problem?

**Comment by lenjka01** [comment]
OMG. Yes it does. Thank you very much.

**Comment by afle** [comment]
Thanks a lot... It works!

**Comment by Gernott** [comment]
Great! We are glad to have helped you. But Support is expensive. If you want to help us making Mask better, more userfriendly and fixing Bugs, feel free to sponsor your prefered amount. Simply contact us directly.
