### ISSUE TITLE
error in latest master 9.5

### ISSUE THREAD

**Issue by matin73** [Gernott/mask#222]
(1/1) Error

Call to undefined method TYPO3\CMS\Frontend\Page\PageRepository::getRootLine()
in /home/xxxx/typo3conf/ext/mask/Classes/Domain/Repository/BackendLayoutRepository.php line 130

            return $backend_layout_next_level;
        } else { // If backend_layout and backend_layout_next_level is not set on current page, check backend_layout_next_level on rootline
            $sysPage = GeneralUtility::makeInstance(PageRepository::class);
            try {
                $rootline = $sysPage->getRootLine($pid, '');
            } catch (\RuntimeException $ex) {
                $rootline = [];
            }
            foreach ($rootline as $page) {

at MASK\Mask\Domain\Repository\BackendLayoutRepository->findIdentifierByPid(16)
in /home/xxxxxxxx/typo3conf/ext/mask/Classes/Helper/InlineHelper.php line 147

            // if the table is pages, then load the pid
            if (isset($data['uid'])) {

                // find the backendlayout by the pid
                $backendLayoutIdentifier = $this->backendLayoutRepository->findIdentifierByPid($data['uid']);

                // if a backendlayout was found, then load its elements
                if ($backendLayoutIdentifier) {
                    $element = $this->storageRepository->loadElement(

**Comment by nhovratov** [comment]
This is resolved. Can be closed.
