### ISSUE TITLE
container system for mask

### ISSUE THREAD

**Issue by tsurfer84** [Gernott/mask#224]
Is it possible to have for future functionality in the backend view a container system like in flux and gridelements also in mask? this would extremely increase usability in the backend.
this would be interesting especially for nested content, e.g. creating a slider with slides insde or an accordion element with further content elements inside.
I know that mask can nest content, but in terms of usability the given backend view is not so comfortable, e.g. one cannot drag nested content out ouf a mask content or drop content from outside into a mask content element to be nested. is such a functionality planned? I would ask you to add that to the wish list ;)

**Comment by Gernott** [comment]
Mask is only using TYPO3-core features. Grids are not possible with TYPO3 yet. So no, I'm sorry, this is not possible or planned.
Remember the Extension mask_export - it wouldn't be possible to deinstall Mask, if there is functionality in it.
