### ISSUE TITLE
Wrong sequence of HTML tags

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#226]
After creating and saving a contentelement, the sequence of the HTML (Fluid) Tags in the generated HTML file is different from the sequence of the fields in the contentelement.

**Comment by medarob** [comment]
I created an IRRE element with some boxes and noticed that they are sorted by ID and not by the sequence I choose in the backend. Even if I place the first created element at the bottom it is rendered first in the code.

![grafik](https://user-images.githubusercontent.com/33951787/75874114-63339000-5e11-11ea-8492-3190eacaad90.png)

Is this the same issue you described here?
