### ISSUE TITLE
mask breaks tt_content.assets

### ISSUE THREAD

**Issue by smichaelsen** [Gernott/mask#230]
When rendering a tt_content element with the FLUIDTEMPLATE cObj mask automacially tries to resolve the file reference fields:

https://github.com/Gernott/mask/blob/master/Classes/Fluid/FluidTemplateContentObject.php#L74

However it looks only for relations for the pages table (hardcoded) and by that breaks tt_content.assets.

Either add support for tt_content at that place or check for `if ($this->cObj->table === 'pages')` first.

**Comment by nhovratov** [comment]
Can you give a code example of the rendering of tt_content with FLUIDTEMPLATE?
