### ISSUE TITLE
it is not possible to use Mask 4.1 for T3 9 in our own Project

### ISSUE THREAD

**Issue by ds-adm** [Gernott/mask#231]
Hello,
it is not possible to use Mask 4.1 for T3 9 in our own Project.

I think the issue are, the path to the frontend Templates T3 could not found see it on the screenshot on the attached File.
![Unbenannt](https://user-images.githubusercontent.com/32568373/55972813-82b74c80-5c84-11e9-913d-61d7d5e25a58.PNG)

And on this screenshot here, im not found the path to the frontend Templates
![Unbenannt 2](https://user-images.githubusercontent.com/32568373/55973098-26086180-5c85-11e9-99e0-3b4b658c21f1.PNG)
with the Object Browser.

Please fix this issue, thanks.

**Comment by nitori** [comment]
The frontend template paths are not configured in TypoScript. What you see is perfectly normal. If you want to inspect the configured template paths, you have to go to the "Configuration" Module, select `$GLOBALS['TYPO3_CONF_VARS']` in the drop down at the top, and then navigate to "EXTENSIONS" -> "mask".

Make sure you have the mask static typoscript added in your template.

**Comment by ds-adm** [comment]
Yes i have included the mask static typoscript in my template.
I found the path Extensions -> mask put there are no path to the Fronend Template  for a test i use the original path from mask, this option are the same ! I dont know what's runing wrong

**Comment by zenoussi** [comment]
Same Problem!

**Comment by nom10s** [comment]
I have the same problem with Mask 4.1.0 on TYPO3 9.5.5, but with a very similar installation (also Mask 4.1.0 on TYPO3 9.5.5) the problem does not occur.

It's astonishing that it says "The following paths were checked:", where no paths are listed in the error message, but on the other hand it says further below:

"at TYPO3\CMS\Frontend\ContentObject\FluidTemplateContentObject->render(array('templateRootPaths.' => array('EXT:mask_project/Resources/Private/Mask/Frontend/Templates/'), 'partialRootPaths.' => array('EXT:mask_project/Resources/Private/Mask/Frontend/Partials/'), 'layoutRootPaths.' => array('EXT:mask_project/Resources/Private/Mask/Frontend/Layouts/'), 'dataProcessing.' => array('MASK\\Mask\\DataProcessing\\MaskProcessor'), 'templateName' => 'Accordion.html'))"

which seems quite correct to me.

Should I contribute more data?

Kind regards
Stefan

**Comment by nom10s** [comment]
The following adjustment brought me success: instead of "EXT:mask_project/Resources/Private/Mask/Frontend/Templates/" etc. use "typo3conf/ext/mask_project/Resources/Private/Mask/Frontend/Templates/". cf. screenshot
![Bildschirmfoto 2019-05-03 um 11 32 59](https://user-images.githubusercontent.com/31162974/57129633-4e244580-6d97-11e9-98c2-71a197bcdc87.png)

**Comment by Gernott** [comment]
EXT paths works only, when you have a working extensions and it is installed.
We changed the default paths to typo3conf/ext/... - so your described problem does not exist by default.
