### ISSUE TITLE
little issue with internal links in generated mask template

### ISSUE THREAD

**Issue by SicorDev** [Gernott/mask#232]
When creating a link property in a mask element the rendering of the link in the template is generated like this:

<f:link.typolink parameter="{**data_item.tx_mask_...**}">{**data_item.tx_mask_...**}</f:link.typolink>

But this doesn't work very well for internal links. You get either only the page id or worse "t3://page?..." in the frontend as it's link title.

The simple, but yet hard to find, solution for this:

<f:link.typolink parameter="{data_item.tx_mask_...}" />

In this case the typolink view helper generates the link title correctly, even for translated multi language pages.

**Comment by nhovratov** [comment]
Resolved. Can be closed.
