### ISSUE TITLE
Problem finding template

### ISSUE THREAD

**Issue by Schmalztopf** [Gernott/mask#237]
Hello, 

I tried to install the mask extension Version 4.1.0 on typo3 9.5.1 via composer. I added fsc and mask to the root template and created an Element called BtCard. I now get the error: 

`Tried resolving a template file for controller action "Standard->BtCard" in format ".html", but none of the paths contained the expected template file (Standard/BtCard.html). The following paths were checked:`

I already tried to move the html file BtCard.html which was created automatically to a subfolder  called Standard. Has anybody got an idea what causes this problem?

Thanks 
Thomas

**Comment by Gernott** [comment]
This is solved in the Github version here (Master Branch).
Or simply check the Paths in your Extensionconfig: They need a slash at the end and check if your extension is installed or use typo3conf/ext/ instead of EXT:mask_project/

**Comment by Schmalztopf** [comment]
Yes, you pointed it exactly. Changing EXT:mask_folder to EXT:myextensionkey solved this.
Thanks
