### ISSUE TITLE
Copy Mistake with mask elements

### ISSUE THREAD

**Issue by Anjahenning** [Gernott/mask#238]
Kopiert man Seiten welche MASK Elemente enthalten, geht die Sortierung der MASK Elemente verloren, die in sich eigene Content-Elemente haben. Inhalte die unten in einer Seite dargestellt wurden, werden dann plötzlich oben angezeigt. Gib es hier ein Möglichkeit komlette Seiten z kopieren ohne die Mask Elemente in Containern immer wieder neu zu verschieben?

**Comment by nhovratov** [comment]
Hallo @Anjahenning 
passiert das nur im Zusammenhang mit gridelements? Oder was meinst du mit containern?
