### ISSUE TITLE
delete inline css style

### ISSUE THREAD

**Issue by Teisi** [Gernott/mask#239]
Please delete the generation of inline-css-style attribute (setup.txt - line 84):
lib.parseFunc_RTE {
    externalBlocks {
        blockquote.callRecursive.tagStdWrap.HTMLparser.tags.blockquote.overrideAttribs = style="margin-bottom:0;margin-top:0;"
    }
}

https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Documentation/Changelog/8.7/Breaking-80171-RemoveLibparseFunc_RTEInlineStylesFromParsedBlockquoteTag.rst

Thank you!

**Comment by vitd** [comment]
Yes, please. This is nothing but annoying in an otherwise beautifully crafted extension.
Thank you!
