### ISSUE TITLE
Adding Comments as Type in Elements

### ISSUE THREAD

**Issue by KingDumah** [Gernott/mask#240]
Hi, because Mask elements can easy become complex, it would be nice if there was some kind of comment-element. For example an small text/explanation before the repeat-element which explains how to use it and if there are some special things to consider. Or before an file-element what image ratio i need and what pixel with would be perfect.
At the moment i use the text-element with default text, but user can change that, remove it, an it seams not always clear for some users that this is just an explanation or info.

**Comment by Gernott** [comment]
Is there a possibility in TCA? I dont think so. Then it is not possible with Mask. Mask uses only TYPO3 core features.

**Comment by KingDumah** [comment]
I think i found found a way with TYPO3 core features.
[https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Columns/Index.html?highlight=description#columns-properties-description](https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Columns/Index.html?highlight=description#columns-properties-description)
With this, i can add an description directly under the label. So it should be just an Textarea in Mask, under the Label. 
In an File-Record it looks like this:
`
...
"tx_mask_videohtml5video": {
    "config": {
         "filter": [
             {
                "parameters": {
                    "allowedFileExtensions": "mp4,webm,ogg"
                }
            }
        ],
        "maxitems": "5",
        "minitems": "1"
    },
    "exclude": "1",
    "key": "videohtml5video",
    "l10n_mode": "",
    "options": "file",
    "description": "This is my Description!"
},
...
`
and in use it looks like this:
![image](https://user-images.githubusercontent.com/8233357/62704382-84eba680-b9eb-11e9-8ea2-4456e6594548.png)

The Problem is, if i change anything in my Mask-Elements in TYPO3, it removes my description.

**Comment by Gernott** [comment]
Cool, we can implement this. Are you interested in sponsoring?

**Comment by renekreupl** [comment]
I would also be happy if the function will be added soon. How can I support you?

**Comment by butu** [comment]
This is now implemented in master and will be released with the next version soon :)
