### ISSUE TITLE
Copy Elements in Repeater does not exist

### ISSUE THREAD

**Issue by wtdesign** [Gernott/mask#241]
It is possible to copy a whole Mask-Element, but not a repeater-item which is integrated in a Mask-Element. Also it isn't possible to copy repeater-items to a different repeater-item in the same Mask-Element.

**Comment by Gernott** [comment]
No, both is not possible at the moment.
These are feature request. Solutions: You can implement this by yourself (pull request) or sponsor a feature.

**Comment by nhovratov** [comment]
@wtdesign Have a look at this extension: https://github.com/kitzberger/dragon_drop
It does this only with content types not with repeating, but maybe it will be added later on.
Either way this should be handled with another extension like this imo, as Masks job should only be helping creating those elements.
