### ISSUE TITLE
Default layout of Fluid_styled_content for mask content elements

### ISSUE THREAD

**Issue by dkoether** [Gernott/mask#242]
Is it possible to use EXT:fluid_styled_contents layouts without first exporting the mask content elements with EXT:mask_export?

Thanks in advance!

**Comment by nitori** [comment]
Yes, in newer versions of mask you can tell it's using `lib.maskContentElement` for rendering content elements (see TypoScript Object Browser in Template Module). Which is very similar to `lib.contentElement` from fluid_styled_content.

_Note: This is untested, but I know I got it to work with some configuration like the following or **similar**._

You need to simply add the partials and layouts from fluid_styled_content to the mask setup, something like this:

```
lib.maskContentElement.layotRootPaths.0 < lib.contentElement.layoutRootPaths.0
lib.maskContentElement.partialRootPaths.0 < lib.contentElement.partialRootPaths.0
```
Note: no need for templatesRootPaths.
We add it with lowest priority. If you already have additional root paths configured for partials or layouts in `lib.contentElement`, you might want to add those as well to your mask configuration, but note that the mask partial/layout root paths are by default at key `10` and should not be overwritten.

In your mask templates you'd have to specify to use the fsc layout:

```
<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
      data-namespace-typo3-fluid="true">

<f:layout name="Default" />

<f:section name="Main">
    your mask template content here
</f:section>
```
You can always remove the f:layout and f:section to fall back to normal mask behaviour with that, if you don't want it to use the fsc layouts.

Note: the fsc partials usually rely on several fields from the tt_content table to work properly, like header, header_layout and header_position. So to get it to work properly you'd want to add those fields with their original purpose to your mask elements.

I _think_ you can also add an empty `<f:section name="Header" />` section to your mask template to disable headers like the `Div.html` template file in FSC does.

Note: I looked at the templates and ts setup based on TYPO3 9, so it might be different for other versions.

**Comment by dkoether** [comment]
Thank you, nitori for this extensively answer! :) Works fine!
