### ISSUE TITLE
Frontend Editing compatibility

### ISSUE THREAD

**Issue by SchmidtWebmedia** [Gernott/mask#243]
Hi,

is there a possibility to work with frontend_editing? Before and after a mask CE isn't a DropZone available. 

If this is possible maybe it could be add to documentation? Or is it possible to add this feature to mask extension :)

Thanks a lot

**Comment by Gernott** [comment]
Hi,
this is not testet yet. If you have Feedback, you are welcome.
If you want to sponsor this research or implement something or write the documentation, please get in direct contact with us.
Best regards, Gernot
