### ISSUE TITLE
IRRE-Fields with workspaces -> Double-Entries in Frontend

### ISSUE THREAD

**Issue by mjpr263** [Gernott/mask#244]
When workspaces are used in conjunction with IRRE fields (for example, accordions), entries in the frontend are output more than once. The duplicate entries are the versions.

In earlier versions of ext:mask in "ext:mask/Classes/Helper/InlineHelper.php:getInlineElements()" was checked for "pid<>-1", in the current version this where-clause is no longer present.

By adding 

`->andWhere($childTable . '.pid<>-1')`

in the query builder, the content is output correctly again.

**Comment by medarob** [comment]
We have the same problem. An official fix would be appreciated :)
