### ISSUE TITLE
4.1.0 Paths?

### ISSUE THREAD

**Issue by saschaende** [Gernott/mask#245]
I get this message:
	
Oops, an error occurred!
Tried resolving a template file for controller action "Standard->Test" in format ".html", but none of the paths contained the expected template file (Standard/Test.html). The following paths were checked:

When i export with mask_export, i do not get any message.

I included the typoscript template in my website root.

**Comment by saschaende** [comment]
I changed to typo3conf/ext/mask_project/Resources/Private/Mask/Frontend/Templates/ without EXT: and now it works.

Why?

**Comment by JohannesRegner** [comment]
@saschaende -> Thank you very much, you saved my friday evening! Had the same problem...

**Comment by saschaende** [comment]
This problem exists 6 months later?

**Comment by JohannesRegner** [comment]
I read in the closed issues, that this error should fixed with version 4.1.2. But i have the problem with version 4.1.2 also... (TYPO3 9.5.13)

**Comment by Gernott** [comment]
"EXT:extkey" Paths works only, when the extension is installed.
Only the Mask Backend support this paths without installing the Extension.
