### ISSUE TITLE
Invalid Template Resource Exception

### ISSUE THREAD

**Issue by jochla** [Gernott/mask#247]
In einem Projekt mit TYPO3 9.5, das auf de EXT:t3sbootstrap (4.1.0) aufsetzt, habe ich mit Mask (4.3.4) ein ganz einfaches Inhaltselement erstellt, das nur aus einem einfachen String-Feld für das ich das DB-Field header verwende, erstellt. Im Backend habe ich das neue Inhaltselement auf einer Seite eingesetzt und bekomme dann im Frontend diese Fehlermeldung: 
#1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException
Tried resolving a template file for controller action "Standard->Jcltestce" in format ".html", but none of the paths contained the expected template file (Standard/Jcltestce.html). The following paths were checked:

Alle Pfadeinstellungen entsprechen in beiden Extensions den Standardeinstellungen.

Gibt es hier eine Unverträglichkeit mit der EXT:t3sbootstrap?

Entschuldigt bitte, dass ich nicht in Englisch schreibe, aber dafür reicht es leider nicht... - zumindest nicht verständlich genug ;)

**Comment by jochla** [comment]
Habe die Lösung hier in den Kommentaren gefunden und auch die neue Version 4.1.2 aus dem TER installiert.

**Comment by xerc** [comment]
ps/ eine angabe zur lösung (zb. LINK) wäre wünschenswert

**Comment by xerc** [comment]
#237
#245
