### ISSUE TITLE
Unable to generate a URL for the named route "dummy" because this route was not found. 

### ISSUE THREAD

**Issue by jankammerath** [Gernott/mask#248]
When updating fields in Content Elements and saving the changes, the following Typo3 error message appears:

Unable to generate a URL for the named route "dummy" because this route was not found. 

System: Typo3 CMS 9.5.8 on Ubuntu
Mask Version: 4.1.2

Any ideas on how to resolve this?

**Comment by nhovratov** [comment]
In content elements in the mask module or in page module?
