### ISSUE TITLE
define custom cropVariants in image of mask element

### ISSUE THREAD

**Issue by Schmalztopf** [Gernott/mask#250]
Hello,

I have created an element with mask (and exported with mask_export) and I now want to provide custom crop variants for an image inside the content element. Lets say the mask element has a repeater called tx_contentelements_items and inside the repeate a content element is located (type textmedia) called tx_contentelements_image.

I know, I could provide crop variants overriding tt_content fpr textmedia with:
$GLOBALS['TCA']['tt_content']['types']['textmedia']['columnsOverrides']['assets']['config']['overrideChildTca']['columns']['crop']['config']['cropVariants']

But this would affect all textmedia elements. How would I do this in an custom element created by mask?

**Comment by wazum** [comment]
You would need a FormDataProvider and adapt the TCA dynamically when loading.
You can read more about this here: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/FormEngine/DataCompiling/Index.html

**Comment by nhovratov** [comment]
@Schmalztopf Instead of "textmedia" you can enter your mask element e.g. "tx_mask_my_element" and it will only override images in this element.

**Comment by ursbraem** [comment]
If my element is `mask_teaser` and it has a field called `tx_mask_teaser_image`, this is the config for `TCA/Overrides/tt_content.php`:

`$GLOBALS['TCA']['tt_content']['types']['mask_teaser']['columnsOverrides']['tx_mask_teaser_image']['config']['overrideChildTca']['columns']['crop']['config']
`

**Comment by ursbraem** [comment]
And here is the code to use with repeating regions:

The repeating table is `tx_mask_test_items` and the column where the asset is is `tx_mask_test_asset`. The `type` property must be omitted. So that gives us:

`$GLOBALS['TCA']['tx_mask_test_items']['columns']['tx_mask_test_asset']['config']['overrideChildTca']['columns']['crop']['config']['cropVariants'] = $testCropVariants;`

**Comment by ursbraem** [comment]
Thanks @nhovratov for your support in slack!
