### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by peterconlabz** [Gernott/mask#251]
I get the following error message:

Class TYPO3\CMS\Extbase\Object\ObjectManager * inject() */ does not exist
Problems with PHP 7.3.7 and "@TYPO3\CMS\Extbase\Annotation\Inject"?
Have you any idea?

TYPO3 9.5.9
PHP Version 7.3.7

Many thanks!

**Comment by nhovratov** [comment]
Have you tried clearing red cache? It should work.
