### ISSUE TITLE
Custom TCA settings are removed

### ISSUE THREAD

**Issue by wazum** [Gernott/mask#252]
When I edit the mask.json and add some custom TCA settings (e.g. `displayCond`, etc.) all this is lost as soon as I use the backend editor and save the mask.json again.

These settings should be preserved.

**Comment by nhovratov** [comment]
You should override tca in your own extension in Configuration/TCA/Overrides/tt_content.php.
Make sure to have mask as a dependency or suggest to ensure your extension is loaded after.
