### ISSUE TITLE
Deleting Pages not working

### ISSUE THREAD

**Issue by dangele** [Gernott/mask#255]
When I want delete a page i get this error:

Oops, an error occurred!
An exception occurred while executing 'SELECT `uid` FROM `tx_mask_seminarorte` WHERE (`pid` = ?) AND (`tx_mask_seminarorte`.`deleted` = 0)' with params [423]: Unknown column 'uid' in 'field list'.

The page i wanna delete is empty :/.

**Comment by nitori** [comment]
This sounds more like you have some TCA for the table `tx_mask_seminarorte` somewhere.

Sometimes people add TCA/Overrides to override the generated mask TCA configurations, and if you then remove that mask element (or remove the repeating element), you might end up with partial TCA configurations.

Check the "Configuration" module in your backend, to see if there actually is some partial TCA configuration for that table.
