### ISSUE TITLE
Translation of repeater in page templates doesn't work

### ISSUE THREAD

**Issue by jennywissel** [Gernott/mask#258]
When using a repeater in a page template it is possible to translate all items in the backend, but there is no access to the translated content in the frontend – the repeater always contains the default language.

Maybe this happens because the table of the repeater uses the translated page id {data._PAGES_OVERLAY_UID} in the column 'parentid'...

TYPO3 9.5.8
MASK 4.1.0

![table-repeater](https://user-images.githubusercontent.com/57901077/69054931-ec62ba80-0a0c-11ea-81db-3b29096b235a.png)

**Comment by alexanderberner** [comment]
We have the same issue. It looks like the variable `$data["_LOCALIZED_UID"]` ist not set but the variable `$data["_PAGES_OVERLAY_UID"]`. This is found in Classes/Helper/InlineHelper->getInlineElements(). If we change `_LOCALIZED_UID` to `_PAGES_OVERLAY_UID` everything works but I don't know if there are any sideffects.

**Comment by christian-forgacs** [comment]
Push.. We have the same issue... But the solution from @alexanderberner don't work in out project.
