### ISSUE TITLE
The argument "arguments" was registered with type "array", but is of type "string" 

### ISSUE THREAD

**Issue by Teisi** [Gernott/mask#259]
TYPO3 9.5.11
PHP: 7.3.7
Mask: 4.1.2

Got error in backend-module after created one mask element:

(1/1) #1256475113 InvalidArgumentException
The argument "arguments" was registered with type "array", but is of type "string" in view helper "TYPO3\CMS\Fluid\ViewHelpers\Uri\ActionViewHelper".

in ....\typo3_sources\typo3_src-9.5.11\vendor\typo3fluid\fluid\src\Core\ViewHelper\AbstractViewHelper.php line 356

My fix:
mask/Resources/Private/Backend/Templates/WizardContent/List.html Line: 102
from:
```
<f:link.action action="delete" arguments="{type:'tt_content', key:key}" class="deleteCe btn btn-default" additionalAttributes="{data-purge-url: '{f:uri.action(action: \'purge\', arguments: {type:\'tt_content\', key:key} )}', data-title: '{f:translate(key:\"tx_mask.field.titleDelete\")}', data-content: '{f:translate(key:\"tx_mask.all.confirmdelete\")}', data-button-close-text:'{f:translate(key:\"tx_mask.all.abort\")}', data-button-ok-text:'{f:translate(key:\"tx_mask.all.delete\")}', data-button-purge-text:'{f:translate(key:\"tx_mask.all.purge\")}'}"><core:icon identifier="actions-edit-delete" /></f:link.action>
```

to:
```
<f:link.action action="delete" arguments="{type:'tt_content', key:key}" class="deleteCe btn btn-default" additionalAttributes="{data-purge-url: '{f:uri.action(action: \'purge\', arguments: \"{type:\'tt_content\', key:key}\" )}', data-title: '{f:translate(key:\"tx_mask.field.titleDelete\")}', data-content: '{f:translate(key:\"tx_mask.all.confirmdelete\")}', data-button-close-text:'{f:translate(key:\"tx_mask.all.abort\")}', data-button-ok-text:'{f:translate(key:\"tx_mask.all.delete\")}', data-button-purge-text:'{f:translate(key:\"tx_mask.all.purge\")}'}"><core:icon identifier="actions-edit-delete" /></f:link.action>
```

changed in there the part:
`additionalAttributes="{data-purge-url: '{f:uri.action(action: \'purge\', arguments: \"{type:\'tt_content\', key:key}\" )}'`

added `\" ... \"` to arguments of uri.action

**Comment by kamilmaliszewski** [comment]
@Teisi do you have MacOS? We saw that for Mac Cataline this error no exist. Only for Mac Mojave. So it depends on the PHP config, it is not Mask bug I thnik

**Comment by Teisi** [comment]
@kamilmaliszewski no i have win10 :)

**Comment by Teisi** [comment]
Same Issue with PHP 7.3.9 after flush cache at the backend, second call (frame refresh) gives:
PHP Warning: Illegal string offset 'action' in C:\MAMP\htdocs\typo3_sources\typo3_src-9.5.12\typo3\sysext\extbase\Classes\Mvc\Web\Routing\UriBuilder.php line 539

----
There is really something wrong, debug of TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder on line 539 outputted with DebuggerUtility::var_dump($controllerArguments) string "button" so there is no Array there. So the params comment is ignored by Extbase?!
Change the "if ($actionName !== null) {" to:
```
if ($actionName !== null) {
    if($actionName === 'purge') {
        DebuggerUtility::var_dump($controllerArguments, "controllerArguments");
        $controllerArguments['action'] = $actionName;
        DebuggerUtility::var_dump($controllerArguments, "controllerArguments AFTER");
    } else {
        $controllerArguments['action'] = $actionName;
    }
}
```
----------------------
Test only Fluid:
no output - no parsing of the viewhelper:
{f:uri.action(action: \'purge\', arguments: {type:\'tt_content\', key:key} )}

output ok:
{f:uri.action(action:'purge', arguments: '{type:\'tt_content\',key:key}')}

output ok:
<f:uri.action action="purge" arguments="{type:'tt_content',key:key}"></f:uri.action>

--------
@kamilmaliszewski
which PHP config? Don't know what to change...

**Comment by nitori** [comment]
This is honestly not an issue with mask, but with the [fluid template engine](https://github.com/TYPO3/Fluid) in general.

The troublesome part is, that it does not allow you to not use quotations marks for nested viewhelpers. e.g. if you have uri.action viewhelpers inside of uri action viewhelpers, it could, in worst cases, look something like this:

```
<f:link.action arguments="{foo: '{f:uri.action(arguments: \'{f:uri.action(arguments: \\\'{bar: \\\\\'spam\\\\\'}\\\')}\')}'}" />
```
I'm not even 100% sure I got this right.

The way I avoid this kind of nesting is usually by wrapping it in f:alias or specifying some variables using f:variable, or in really complicated situations by using a custom ViewHelper and write some much saner PHP instead.
