### ISSUE TITLE
Wrong formatting and timezone for datetime-fields in repeated title

### ISSUE THREAD

**Issue by OlafDoering** [Gernott/mask#260]
We have some trouble with mask elements, using a datetime field as first field in a repeated group. The datetime shown in the title of the irre elements are not shown in the correct timezone and differ by 1 or 2 hours.
![mask](https://user-images.githubusercontent.com/3953886/69534061-5af9c800-0f79-11ea-9c19-827eee3acd16.JPG)

**Comment by nitori** [comment]
This is an issue with TYPO3 itself when using "dbType"=>"datetime" ("date" or "time" possibly as well) in TCA configuration (which mask does). I had trouble with that configuration before in general (not mask related) and usually don't use it, but prefer to use Unix timestamps where applicable.

**Comment by nhovratov** [comment]
There will be a new mask field for unix timestamps.
