### ISSUE TITLE
Backend preview does not work.

### ISSUE THREAD

**Issue by 9bis5** [Gernott/mask#263]
The manual says that in version 4.1.2 you should use the Backend/Previews folder for the backend preview. If I enter this in the configuration and put HTML files into it, nothing happens. Even if I put the templates in the folder Backend/Templates nothing happens. Is there a bug? What have I forgotten?

I Use TYPO3 9.5.

My configuration in the LocalConfiguration.php:

```
'mask' => [
            'backend' => 'typo3conf/ext/tmpl/Resources/Private/Extensions/Mask/Backend/Templates',
            'backendlayout_pids' => '0,1',
            'content' => 'EXT:tmpl/Resources/Private/Extensions/Mask/Frontend/Templates',
            'json' => 'EXT:tmpl/Resources/Private/Extensions/Mask/mask.json',
            'layouts' => 'EXT:tmpl/Resources/Private/Extensions/Mask/Frontend/Layouts',
            'layouts_backend' => 'typo3conf/ext/tmpl/Resources/Private/Extensions/Mask/Backend/Layouts',
            'partials' => 'EXT:tmpl/Resources/Private/Extensions/Mask/Frontend/Partials',
            'partials_backend' => 'typo3conf/ext/tmpl/Resources/Private/Extensions/Mask/Backend/Partials',
            'preview' => 'typo3conf/ext/tmpl/Resources/Private/Extensions/Mask/Backend/Previews',
        ],
```

**Comment by devxpoint** [comment]
I can confirm this issue if TYPO3 (9 or 10) is installed in a subdirectory e.g. "new_site"

This certain subfolder is missing in the path to the preview image, e.g.
https://domain.com/typo3conf/ext/my_extension/Resources/Private/Mask/Preview/keyname.png

It should be:
https://domain.com/new-site/typo3conf/ext/my_extension/Resources/Private/Mask/Preview/keyname.png

**Comment by nhovratov** [comment]
These are two completely different issues.
@devxpoint I pushed a fix for the wrong paths to v6 branch.
@9bis5 Can you try adding a trailing slash after the paths? Or maybe you have resolved it by now by yourself :)
