### ISSUE TITLE
IRRE fields not working in 4.1.2

### ISSUE THREAD

**Issue by derJake** [Gernott/mask#269]
It seems like there is a bug when processing IRRE elements for the frontend in mask 4.1.2 in conjunction with TYPO3 9.5.14-9.5.15
Instead of the repeater elements being rendered an exception is thrown, because the number of repeater elements is passed to the fluid template instead of the actual rows/objects.

**Steps to reproduce:**
- install TYPO3 ^9.5.14
- create template/require bootstrap sitepackage
- require mask
- create mask element with repeater field
- put repeater element on a page
- view said page in frontend

**Expected behaviour:**
Whatever is put into the repeater element is rendered on the page.

**Actual behaviour:**
An Exception is thrown: `(1/1) #1256475113 InvalidArgumentException
The argument "each" was registered with type "array", but is of type "integer" in view helper "TYPO3Fluid\Fluid\ViewHelpers\ForViewHelper".
` because the dataprocessor passes the number of repeated elements to the template instead of the array of repeated objects.

```
data => 
    ....
    tx_mask_repeaterfield => 2 (integer)
```

**Comment by nhovratov** [comment]
Works for me on recent v9 version. Can you verify this?

**Comment by derJake** [comment]
Yes, I couldn't reproduce it with
TYPO3 9.5.19
Mask 4.2.1
