### ISSUE TITLE
Error with TYPO3 V10 branch

### ISSUE THREAD

**Issue by ammodytes** [Gernott/mask#270]
![image (4)](https://user-images.githubusercontent.com/33286022/79218792-4f883a00-7e51-11ea-9e2d-abf2ed16a9db.png)

Hi all,

i am exploring new TYPO3 version and i wanted to install mask as usual for all my installations, i downloaded v10 branch and installed it but, when i create folder for mask templates, or when i setup path to already created folders this error happens. Any fix or easy solution?

Thanks :)

**Comment by butu** [comment]
hey ho, 

try to clear the class cache in maintenance (Rebuild PHP Autoload Information). 

best regards!
