### ISSUE TITLE
Changing json doesnt affect backend.

### ISSUE THREAD

**Issue by mr660** [Gernott/mask#271]
Renaming field eg. `tx_mask_sidebar_content` to `tx_mask_sidebar_content` doesnt work properly. After chaning json and going to be field doesnt change. It needs to be removed from backend and added there to work properly.

**Comment by butu** [comment]
You have to delete the field in the backend module of mask and then create a new field. There is no renaming option in the backend module. If you change the mask.json manually, you can do that, but there is always the chance you missed something.
