### ISSUE TITLE
Removing fields from backend doesnt remove them from sql and tca arrays

### ISSUE THREAD

**Issue by mr660** [Gernott/mask#272]
Like in title, removing any field doesnt remove it from `sql` and `tca` arrays, only from `elements`. Because of this during development and future changes json becomes bigger and bigger mess making it more and more uncomfortable to add new fields based on already used because it displays all the not used fields.

**Comment by butu** [comment]
I can't reproduce this behaviour. When you delete a field from a mask element, the field is deleted in th mask.json and therefore from sql and tca. Which version of mask and typo3 did you experience this on?
