### ISSUE TITLE
Move backend module to the bottom of admin tools category

### ISSUE THREAD

**Issue by nitori** [Gernott/mask#274]
Since TYPO3 9 LTS the install tools have been separated into several maintenance modules and one of them, the top most, is "Maintenance".

Both Mask and the Maintenance module have a red color, which leads to the (tiny) annoyance, of occasionally missclicking onto the Mask module when I want to go to Maintenance.

![2020-04-22_150700](https://user-images.githubusercontent.com/1561831/79985496-fa7ca180-84aa-11ea-9072-d92f77a3530d.png)

Like I said, it's just a tiny annoyance, but I would like it, if the Mask module position could be changed from "top" to "bottom".

Might follow up with a PR if I find the time

**Comment by butu** [comment]
Agreed and adjusted! :)
