### ISSUE TITLE
TYPO3 10.4 [LTS]

### ISSUE THREAD

**Issue by xerc** [Gernott/mask#275]
"No extension key given." [https://typo3.org/go/exception/CMS/debug/1507321291]

> **mask/ext_tables.php** line 25
`[..]\ExtensionManagementUtility::addStaticFile($_EXTKEY, [..]`

ref. https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html#best-practices-for-ext-tables-php-and-ext-localconf-php
> it is recommended to use the extension name instead of $_EXTKEY

**Comment by xerc** [comment]
"Call to undefined method TYPO3\CMS\Backend\Utility\BackendUtility::getModuleUrl()"
> @ **mask/Classes/ViewHelpers/ConfigureExtensionViewHelper.php** line 32
`$url = BackendUtility::getModuleUrl('tools_toolssettings');`

FIX; https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.3/Deprecation-85113-LegacyBackendModuleRoutingMethods.html?highlight=getmoduleurl#migration

**Comment by xerc** [comment]
Fatal error: Declaration of MASK\Mask\Domain\Model\BackendLayout::getUid()
must be compatible with TYPO3\CMS\Extbase\DomainObject\AbstractDomainObject::getUid(): ?int

> @ **mask/Classes/Domain/Model/BackendLayout.php** on line 147

**Comment by xerc** [comment]
PHP Warning: Use of undefined constant PATH_site - assumed 'PATH_site'
(this will throw an Error in a future version of PHP)

> @ **/vol1/home/mfoerster/gtai.xerc.de/packages/mask/Classes/Imaging/IconProvider/ContentElementIconProvider.php** line 142

**Comment by xerc** [comment]
PHP Warning: Use of undefined constant PATH_site - assumed 'PATH_site'

> @ **mask/Classes/Imaging/IconProvider/ContentElementIconProvider.php** line 142

**Comment by xerc** [comment]
Table 'tx_mask_domain_model_content' doesn't exist

> @ **mask/Classes/ViewHelpers/ElementCountViewHelper.php** line 42

**Comment by butu** [comment]
Hi, 

are you sure you tested the mask version for TYPO3 10? None of these erreros are in the branch typo3-10 it seems.

**Comment by xerc** [comment]
oh sorry; i was using master // are you aiming for php 7.2 or 7.3?
https://www.php.net/manual/de/json.constants.php#constant.json-throw-on-error

**Comment by butu** [comment]
minimum 7.2 but compatible with 7.3 is the goal

**Comment by xerc** [comment]
if you want to keep the CONSTANT; please add https://github.com/symfony/polyfill/pull/168/commits/82e2f0aaa5a5382712a23a0e6f2757ca79104fd2

**Comment by butu** [comment]
Right! I replaced the constant with the corresponding integer. :) Thank you!
