### ISSUE TITLE
Extension Configuration -> backend.preview does not support EXT: path

### ISSUE THREAD

**Issue by Megafry** [Gernott/mask#278]
Hi
I noticed that all path in the configuration kann also be a EXT: path, only the field backend.preview does not support that.

Can you adjust it?

TYPO3:  10.4.0
Mask Branch: typo3-10

`mask/Classes/Imaging/IconProvider/ContentElementIconProvider.php:131`

```
backend.preview (folder):
EXT:xyz_template/Resources/Public/Icons/
```

Best regards,
Megafry

**Comment by butu** [comment]
Fixed with latest commit! :)
