### ISSUE TITLE
Missing slash in the path to preview icon.

### ISSUE THREAD

**Issue by Megafry** [Gernott/mask#279]
Hi

Environment::getPublicPath returns the absolute  path without trailing slash:
this is now missing and must be added at these 2 places:

`Classes/Imaging/IconProvider/ContentElementIconProvider.php:132 and 155`

```
Environment::getPublicPath() .'/'. $this->getPreviewIconPath($key)
```

Or remove the ltrim function add the missing slash in the function getPreviewIconPath
```
return '/'. $this->extSettings['preview'] . $key . '.png';
```

Best regards,
Megafry

**Comment by butu** [comment]
Could you check if the problem persists after the latest changes :) Thanks!

**Comment by Megafry** [comment]
Works just fine, thanks for the fix
