### ISSUE TITLE
Label Overwrite does not appear

### ISSUE THREAD

**Issue by mitchiru** [Gernott/mask#28]
When I use an existing Field with a custom label, the default label still appear:

            "video": {
                "label": "Video",
                "key": "video",
                "shortLabel": "Video",
                "description": "",
                "icon": "fa-youtube-play",
                "color": "#000000",
                "columns": [
                    "header",
                    "subheader",
                    "image"
                ],
                "labels": [
                    "",
                    "Youtube Link",
                    "Cover"
                ]
            }

I use T3 7.6. and Mask 2.0.1

**Comment by mitchiru** [comment]
For the label subheader, it still shows "Anchor" instead of Youtube Link

**Comment by butu** [comment]
Hm, tested this and it showed Youtube Link as expected. Any more hints?

**Comment by mitchiru** [comment]
True, it showed up for me as well after rm -r typo3temp/* ;-)
THX!

**Comment by butu** [comment]
Nice!
