### ISSUE TITLE
Backend input fields – responsive bug

### ISSUE THREAD

**Issue by m41r** [Gernott/mask#280]
On smaller screens than 1920px width, the `Font-Awesome Icon` and `Colour` input fields have an ugly visual bug. 
see here:
![image](https://user-images.githubusercontent.com/14954406/80587259-7f6d3b00-8a16-11ea-8bd7-90cf1eb3bcd6.png)

**Comment by butu** [comment]
Thank you! I enhanced this and will release it with the next version

**Comment by m41r** [comment]
👍
