### ISSUE TITLE
Global RTE preset through pageTS is ignored by richtext-field in repeating element

### ISSUE THREAD

**Issue by Megafry** [Gernott/mask#284]
Hi

The [TcaCodeGenerator](https://github.com/Gernott/mask/blob/master/Classes/CodeGenerator/TcaCodeGenerator.php#L146)-Class set the `richtextConfiguration` to `Default` for all richtext-field in repeating elements.

This is quite annoying, do to the change [#88655](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.2/Important-88655-ChangedLoadingOrderOfRTEConfiguration.html?highlight=richtextconfiguration) (hanged loading order of RTE Configuration).

My pageTS configuration is now ignored for all repeating elements.
```
RTE.default.preset = myCustomPreset
```

Would it be possible to remove the `richtextConfiguration` option or to make it configurable?

Otherwise I have to overwrite all fields like this:
```
RTE.config.tx_mask_linklist.content.types.text.preset = myCustomPreset
```

Best regards,
Megafry

**Comment by can0199** [comment]
I have overwritten the TcaCodeGenerator class with XClass only the function setElementsTca()

`/**
     * Generates and sets the tca for all the content-elements
     *
     * @param array $tca
     * @noinspection PhpUnused
     */
    public function setElementsTca($tca): void
    {

        $fieldHelper = GeneralUtility::makeInstance(FieldHelper::class);
        $defaultTabs = ',--div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.frames;frames,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.appearanceLinks;appearanceLinks,--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:language,--palette--;;language,--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:access,--palette--;;hidden,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.access;access,--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:categories,--div--;LLL:EXT:core/Resources/Private/Language/locallang_tca.xlf:sys_category.tabs.category,categories,--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:notes,rowDescription,--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:extended';

        // add gridelements fields, to make mask work with gridelements out of the box
        $gridelements = '';
        if (ExtensionManagementUtility::isLoaded('gridelements')) {
            $gridelements = ', tx_gridelements_container, tx_gridelements_columns';
        }
        if ($tca) {

            // add new group in CType selectbox
            $GLOBALS['TCA']['tt_content']['columns']['CType']['config']['items'][] = [
                'LLL:EXT:mask/Resources/Private/Language/locallang_mask.xlf:new_content_element_tab',
                '--div--'
            ];

            foreach ($tca as $elementvalue) {
                if (!$elementvalue['hidden']) {

                    $prependTabs = '--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:general,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.general;general,';
                    $fieldArray = [];
                    $label = $elementvalue['shortLabel'] ?: $elementvalue['label']; // Optional shortLabel

                    // add new entry in CType selectbox
                    ExtensionManagementUtility::addPlugin([
                        $label,
                        'mask_' . $elementvalue['key'],
                        'mask-ce-' . $elementvalue['key']
                    ], 'CType', 'mask');

                    // add all the fields that should be shown
                    if (is_array($elementvalue['columns'])) {
                        foreach ($elementvalue['columns'] as $index => $fieldKey) {

                            // check if this field is of type tab
                            $formType = $fieldHelper->getFormType($fieldKey, $elementvalue['key'], 'tt_content');
                            if ($formType === 'Tab') {
                                $label = $fieldHelper->getLabel($elementvalue['key'], $fieldKey, 'tt_content');
                                // if a tab is in the first position then change the name of the general tab
                                if ($index === 0) {
                                    $prependTabs = '--div--;' . $label . ',' . $prependTabs;
                                } else {
                                    // otherwise just add new tab
                                    $fieldArray[] = '--div--;' . $label;
                                }
                            } else {
                                $fieldArray[] = $fieldKey;
                            }
                        }
                    }
                    $fields = implode(',', $fieldArray);

                    $GLOBALS['TCA']['tt_content']['ctrl']['typeicon_classes']['mask_' . $elementvalue['key']] = 'mask-ce-' . $elementvalue['key'];
                    $GLOBALS['TCA']['tt_content']['types']['mask_' . $elementvalue['key']]['columnsOverrides']['bodytext']['config']['richtextConfiguration'] = 'default';
                    $GLOBALS['TCA']['tt_content']['types']['mask_' . $elementvalue['key']]['columnsOverrides']['bodytext']['config']['enableRichtext'] = 1;
                    $GLOBALS['TCA']['tt_content']['types']['mask_' . $elementvalue['key']]['showitem'] = $prependTabs . $fields . $defaultTabs . $gridelements;

                    //msh start
                    // if element has option array
                    if (isset($elementvalue['options'])) {
                        // search for rte and get the index
                        $optionArrayRteIndex = array_search('rte',$elementvalue['options'],true);

                        // if rte was found
                        if ($optionArrayRteIndex !== false) {
                            //get pagets
                            $pageTsConfig = BackendUtility::getPagesTSconfig(1);
                            //get default rte preset
                            $defaultRtePreset = $pageTsConfig['RTE.']['default.']['preset'];
                            //get the field name from the field that has rte
                            $fieldRte = $elementvalue['columns'][$optionArrayRteIndex];

                            // add default rte preset for mask field that uses rte
                            $GLOBALS['TCA']['tt_content']['types']['mask_' . $elementvalue['key']]['columnsOverrides'][$fieldRte]['config']['richtextConfiguration'] = $defaultRtePreset;
                            $GLOBALS['TCA']['tt_content']['types']['mask_' . $elementvalue['key']]['columnsOverrides'][$fieldRte]['config']['enableRichtext'] = 1;
                        }
                    }
                    //msh end
                }
            }
        }
    }`


this works very well for me
