### ISSUE TITLE
Feature "Allowed content elements" doesn't work in nested content elements

### ISSUE THREAD

**Issue by olafthiel** [Gernott/mask#290]
If you are nesting a content element in a other content element (for example in a accordion) you can define "Allowed content elements". This feature doesn't work since Typo3 v9.5.15. All content elements are visible in the TCA, field "type". The problem is: users can add elements, there are not allowed.

I have found a difference for the value from `$_REQUEST["ajax"]["context"]` in `Classes/ItemsProcFuncs/CTypeList.php,` line 55:
v9.5.14: `{"config":{"appearance":{"collapseAll":"1","enabledControls":{"info":true,"new":true,"dragdrop":"1" ...`
v9.5.15: `{"config":"{\"appearance\":{\"collapseAll\":\"1\",\"enabledControls\":{\"info\":true,\"new\":true,\"dragdrop\":\"1\" ...`

A workaround, that helps me:
`$ajaxContext = json_decode($_REQUEST["ajax"]["context"]);`
`$config = json_decode($ajaxContext->config);`
`$fieldKey = str_replace("_parent", "", $config->foreign_field);`

**Comment by nabossha** [comment]
i can confirm this issue using MASK 4.1.2:
Test-scenario: downgrading from 9.5.19 to 9.5.14 solves the problem.

**Comment by nabossha** [comment]
@Gernott any chance we will see this in a 4.1.x bugfix? this affects several 9.5.x instances and i am sure there would be a lot of people happy about seeing this working again.

**Comment by nhovratov** [comment]
@nabossha Fixed in 4.2.1. Sorry it took so long!
