### ISSUE TITLE
CKEditor YAML-Configuration with MASK-Elements not possible (TYPO3 v10.4.4, MASK 5.0.0)

### ISSUE THREAD

**Issue by wtdesign** [Gernott/mask#291]
Normally I have to write the following snippet to TsConfig

`RTE.default.preset = custom1`

But now I have to write each text field to TsConfig which I have created. Seems to be a bug.

`RTE.config.tt_content.tx_mask_text2.preset = custom1`
`RTE.config.tt_content.tx_mask_text1.preset = custom1`
`RTE.config.tt_content.tx_mask_textumfluss1.preset = custom1`
`RTE.config.tt_content.tx_mask_textumfluss2.preset = custom1`

**Comment by olafthiel** [comment]
We have the same problem and our temporary solution is the following code in ext_localconf.php:

`$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['default'] = 'EXT:' . $extensionKey . '/Configuration/RTE/Custom.yaml';`

**Comment by wtdesign** [comment]
It work. Many thanks.
