### ISSUE TITLE
Return value of TYPO3\CMS\Backend\ViewHelpers\LanguageColumnViewHelper::render() must be an instance of TYPO3\CMS\Backend\View\BackendLayout\Grid\GridColumn, null returned

### ISSUE THREAD

**Issue by kosimas** [Gernott/mask#317]
hi,
after installing the mask extension, I can't use the page tree in the backend anymore.
![Screenshot_2](https://user-images.githubusercontent.com/22711600/86895654-10dae680-c105-11ea-81d1-84ba787c0976.jpg)

This error occurs when I click on a page, inside the "Page Content" menu point in the backend.

I'm using Typo3 version 10.4.3 and Mask version 5.0.0

**Comment by nhovratov** [comment]
Hi, this is a typo3 bug with the new fluid page module. See: https://forge.typo3.org/issues/91497
You have to disable this feature, if you have translations.

**Comment by kosimas** [comment]
Ok thanks. I'll close this issue!
