### ISSUE TITLE
Incorrect sorting of content elements in the Pages module after saving a content element

### ISSUE THREAD

**Issue by dondaniele** [Gernott/mask#321]
TYPO3 10.4.4
Mask 5.0.0

Hello, I have a problem.
Whenever I save a content element in the backend module of Mask, the sorting in the Pages module is completely messed up! It sorts by uid (if I remember correctly) and no longer with the sorting field.
I can only solve the problem if I uninstall the mask EXT, clear the cache under the Install Tool and activate and deactivate the "Fluid Based Page Module" and then clear the cache again. At least this way I could fix it again and again.
I don't have the error at the moment, but it will happen again as soon as I create another CE.
Uploading the mask.json directly does not lead to this error.

Does anyone have the problem? Is there a reasonable solution?

**Comment by rupasix** [comment]
It helped in my case:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/64567
