### ISSUE TITLE
Missing label in nested content elements

### ISSUE THREAD

**Issue by olafthiel** [Gernott/mask#324]
Typo3 10.4.5
Mask 5.1.0

If I create a new nested content element, for example text in an accordion, this element has no mask-labels and for typo3-labels the default value. After saving, all labels are correct and visible.

Image 1, new nested content element (before saving)

![grafik](https://user-images.githubusercontent.com/66680290/87417952-34080900-c5d1-11ea-96c6-614dc7aa45bb.png)

Image 2, nested content element (after saving)

![grafik](https://user-images.githubusercontent.com/66680290/87418168-8fd29200-c5d1-11ea-8b5e-f3ff83135c67.png)

**Comment by nhovratov** [comment]
Hi, thanks for the report. I can reproduce this.
