### ISSUE TITLE
Database tables get lost

### ISSUE THREAD

**Issue by matin73** [Gernott/mask#325]
If I upgrade to latest version 5.1 db compare tool wants to delete all database tables ...??

**Comment by nhovratov** [comment]
Hi, have you tried clear the caches in Maintenance->Clear cache?

**Comment by matin73** [comment]
yes. cleared all caches several times, also php cache

**Comment by nhovratov** [comment]
The only thing i can imagine is that the hard caches are not cleared. Can you provide more insight? Are these really all defined inline tables and custom mask fields that would get deleted?

**Comment by rupasix** [comment]
Are you sure you have ext turned on after upgrade?

**Comment by matin73** [comment]
after upgrading extension I get error:


PHP Warning: Invalid argument supplied for foreach() in /usr/local/www/xx/xx/xx/typo3conf/ext/mask/Classes/CodeGenerator/TcaCodeGenerator.php line 208

**Comment by nhovratov** [comment]
Was the upgrade successfull? This warning can only come from version 5.0.0.

**Comment by matin73** [comment]
I deletet extension now and upload it manually and installed it manually. Cleared all TYPO3 caches - same problem. s. screenshot
![grafik](https://user-images.githubusercontent.com/3177275/87552686-4e65e380-c6b2-11ea-9fd1-b10368cafdcd.png)

**Comment by nhovratov** [comment]
What's your TYPO3 version?

**Comment by matin73** [comment]
10.4.5

**Comment by rupasix** [comment]
Bindings in ext config to mask.json and fluid templates are correct? Your mask.json is fine?

**Comment by matin73** [comment]
I think I found issue - upgrading did not work as error occures (s. above). reinstalling extension also deletet path to json. After setting custom path to json again after manually installing solved the problem.
