### ISSUE TITLE
Tab.html Template missing

### ISSUE THREAD

**Issue by matin73** [Gernott/mask#329]
The Fluid template files "/typo3conf/ext/mask/Resources/Private/Backend/Partials/Forms/Fields/Tab/Tabs.html", " could not be loaded.

Tabs.html file is missing in 5.1.0 on zip package in repository

**Comment by nhovratov** [comment]
It should be there actually. Did you upload the extension as zip file?

**Comment by matin73** [comment]
I have downloaded zip file and it is missing. see screenshot
![grafik](https://user-images.githubusercontent.com/3177275/87569172-043b2d00-c6c7-11ea-979c-ddc62680b936.png)

**Comment by matin73** [comment]
Try to download from repository under https://extensions.typo3.org/extension/download/mask/5.1.0/zip/ it is missing!

**Comment by nhovratov** [comment]
Ah ok, i downloaded from github. I can confirm this is missing. I have no idea in which way they get packaged in TER. My guess is, that somehow empty files are left over.

**Comment by spoonerWeb** [comment]
I can confirm that the file (without content) is not in the TER when downloading as ZIP.
Is an empty file mandatory to run the extension?

@Gernott How do you upload your extension versions to TER? SOAP (via e.g. ter-client) or via web form on extensions.typo3.org?

**Comment by matin73** [comment]
you get error if Tab.html is no on server

**Comment by spoonerWeb** [comment]
Fixed it in the versions 5.1.0 and 5.1.1 in TER. 
Problem was that there was a check if a file has content before adding it to ZIP.
Now it includes empty files as well.
