### ISSUE TITLE
Database fields fe_group and editlock are not inserted

### ISSUE THREAD

**Issue by matin73** [Gernott/mask#332]
In latest version 5.1.1 fields are not inserted in database on inline elements - you have to run db compare manually:

ALTER TABLE `tx_mask_xx` ADD `fe_group` VARCHAR(255) DEFAULT '0' NOT NULL
ALTER TABLE `tx_mask_xx` ADD `editlock` SMALLINT UNSIGNED DEFAULT 0 NOT NULL

**Comment by nhovratov** [comment]
Thanks for the report, will be fixed as soon as possible!
