### ISSUE TITLE
can't override the element title when reusing elements in another CE 

### ISSUE THREAD

**Issue by medarob** [Gernott/mask#333]
Hi,

I created a new CE and this has (amongst others) a link element included.
Now it's possible to reuse this element in another custom CE which is great. Unfortunately it's not possible (or it doesn't work) to change the title of the element if you want to have a different text for the element shown for the 2nd CE.

For example for the initinal CE I used the link element title "Option 2.1 -> Link-Button" but for the 2nd CE I wanted to reuse the field but only with a different title "Verlinkung".
That didn't work and the title of the element in the 2nd CE was the same as in the first CE.

CE 1, link field:
![grafik](https://user-images.githubusercontent.com/33951787/87786696-b2b3af00-c83a-11ea-8e45-095ad8f6844b.png)

CE 2, same reused link field:
![grafik](https://user-images.githubusercontent.com/33951787/87786856-00c8b280-c83b-11ea-9210-25db5c8e9ab3.png)

Shown in BE of the 2nd CE:
![grafik](https://user-images.githubusercontent.com/33951787/87786157-bf83d300-c839-11ea-8b3a-1cd1adf53091.png)

I use TYPO3 9.5.19 and mask 4.1.2
I don't know if this problem still exists in mask 5.1.

**Comment by nhovratov** [comment]
Will check it on current version, thanks. Unfortunetely we can't provide fixes for older versions though.

**Comment by nhovratov** [comment]
Seems to work on current version. And you tried clearing cache?

**Comment by medarob** [comment]
Thank you for testing. Yes, I tried this aswell several times.

I will check this again when I can update the instance to v10. Good to know that this should work in the current version.

**Comment by nhovratov** [comment]
This is works definitely in mask 5 and upwards. As we can't provide any new version for v4 i will close this issue.
