### ISSUE TITLE
Bug by using the repeat field

### ISSUE THREAD

**Issue by can0199** [Gernott/mask#334]
We have created a mask element using the field "Repeat". In the repeating field we inserted a "File" field where we set only the options min and max, both to 2. In the "Repeat" field we set min to 3 and max to 4.

Now if we insert the element on a page and then set 3 elements in the repeating field everything is fine but as soon as we want to create the 4 we can't upload a file anymore because the "Create Relations" button is hidden (by inline style). This happens with all 4 elements.

If we now change the setting "max" of the repeat field to 5, the bug occurs as soon as we want to create the 5 element.

I create a Gif to see the Bug:
![demo](https://user-images.githubusercontent.com/60479637/87806240-d553c100-c856-11ea-99a8-c01b0d99ae58.gif)

**Comment by nhovratov** [comment]
Which version do you use?

**Comment by can0199** [comment]
i use the dev-master version but i have this bug also with the newest stable version i mean this is 5.1.x
 i also forgot to say i use typo3 10.4

**Comment by nhovratov** [comment]
Okay, thanks i will have a look at it.

**Comment by nhovratov** [comment]
This seems like a core bug. Someone created an issue for this on forge already: https://forge.typo3.org/issues/91808

**Comment by nhovratov** [comment]
I pushed a fix to typo3 review system: https://review.typo3.org/c/Packages/TYPO3.CMS/+/65058

**Comment by can0199** [comment]
thank you for your efforts, i will look into it on monday

**Comment by can0199** [comment]
I close this issue because it is a core issue
