### ISSUE TITLE
Error: Exception occurres while executing 'SELECT * FROM `backend_layout`

### ISSUE THREAD

**Issue by Hobokens** [Gernott/mask#339]
Hi, 
I'm just upgrading from TYPO3 9.5.20 to TYPO3 10.4.6. For testing I have installed a local server (XAMPP for Windows 7.3.17).

I have installed mask 5.1.1. without any problems. But when I click the mask  button to open it I get the following error message and the local server has gone:

'An exception occurred while executing 'SELECT * FROM `backend_layout` WHERE (((? = ?) AND (? = ?)) OR ((`backend_layout`.`pid` = ?) OR (`backend_layout`.`pid` = ?)) OR ((? = ?) AND (`backend_layout`.`pid` = ?))) AND ((`backend_layout`.`deleted` = 0) AND (`backend_layout`.`hidden` = 0) AND ((`backend_layout`.`t3ver_wsid` = 0) AND (`backend_layout`.`t3ver_oid` = 0))) ORDER BY `sorting` ASC' with params [null, 0, 0, 0, null, 0, null, 0, null]: MySQL server has gone away'

I tried to disable all backend layouts without any effect.

The new fluid based page layout module is disabled.

**Comment by nhovratov** [comment]
#285

**Comment by Hobokens** [comment]
Thx for the information
