### ISSUE TITLE
Label of IRRE elements get lost

### ISSUE THREAD

**Issue by blueamerican** [Gernott/mask#340]
TYPO3 9.5.19
mask 4.1.2

I have several mask content elements with irre elements.

For the slider i recognized, that suddenly all labels of the irre elements got lost.. "undefined" was displayed in the BE.

What could be the reason for this?

Maybe i must give a repeatable element a real unique key?
See attached screen.

**maybe the key "title" is wrong and i must change it to "item_title"?**

For title i set the lable again, the rest is still undefined.

![mask](https://user-images.githubusercontent.com/5647051/89710119-9eb62580-d980-11ea-9d08-5e094fa552b6.jpg)

**Comment by blueamerican** [comment]
here a screen from the backend html
![mask2](https://user-images.githubusercontent.com/5647051/89710267-96aab580-d981-11ea-9cba-60c1f987cd6e.jpg)

**Comment by nhovratov** [comment]
Hi @blueamerican Markus,

yes, the repeatable element must have a unique key, because mask creates an own table for each of these. The check for uniqueness is broken in mask for v9, so check if there is another element with the key "item".

**Comment by blueamerican** [comment]
ok, the repeatable Element msut be unique.

But what is with the elements IN IRRE:
e.g. title

Must this be unique too? item_title?

or can i have an element title in e.g item and in e.g. item1,..?

**Comment by nhovratov** [comment]
@blueamerican 
Your second guess is correct.
The elements in IRRE have only to be unique inside the repeatable element.
Think of it as multiple database tables can have columns with the same name.

**Comment by blueamerican** [comment]
ok, then my elements are correct.
That means for me, that this is a bug.

The behaviour is:

The labels of the IRRE eleemnts are ok.
I change one label via the mask BE module.
**All labels get lost (undefined)**

**Comment by nhovratov** [comment]
Can you reproduce this behaviour if you create a new element with the same structure? To me at least this never occured before.

**Comment by nhovratov** [comment]
Can't reproduce the bug. Please update if possible to latest mask version.
