### ISSUE TITLE
Order in "Repeater" changes

### ISSUE THREAD

**Issue by rowild** [Gernott/mask#342]
Typo3 9.5.20, Mask 4.1.2

When using different types of content elements in a Repeater, the manual ordering changes when saved. The screenshot shows fields that are numbered and should be kept in that order; however, Mask's Repeater has its own rules.

Manual sorting is also not possible.

Even though this is v4, it would be great, if this could be fixed. Thank you!

![Screen Shot 2020-08-23 at 09 22 36](https://user-images.githubusercontent.com/213803/90973463-90404000-e522-11ea-85c2-02e2142b420f.png)

**Comment by nhovratov** [comment]
Hi @rowild This was fixed in #267. There is no way to release a new version for v4 so either update or apply the fix yourself.

**Comment by rowild** [comment]
@nhovratov Thank you for pointing me to the fix! Great! (...unfortunately I need to stay with TYPO3 9)
