### ISSUE TITLE
Mask 5 BE Layout of the extension itself is mixed up

### ISSUE THREAD

**Issue by rowild** [Gernott/mask#343]
After an update from TYPo3 9.5 to 10.4 and therefore from Mask 4 to Mask 5, the backend for Mask is very mixed up (see screenshots).

Mask overview:
![Screen Shot 2020-08-23 at 10 58 31](https://user-images.githubusercontent.com/213803/90975025-f16f1000-e530-11ea-973e-5ec165f8fd74.png)

A Mask content element:
![Screen Shot 2020-08-23 at 10 57 48](https://user-images.githubusercontent.com/213803/90975031-f46a0080-e530-11ea-9dff-015beba432c4.png)

(continue to bottom)
![Screen Shot 2020-08-23 at 10 58 03](https://user-images.githubusercontent.com/213803/90975029-f3d16a00-e530-11ea-9ac9-0875945e1aea.png)

**Comment by nhovratov** [comment]
Hi @rowild , mask 5 got a complete redesign. Maybe there was some old css cache in your browser.

**Comment by rowild** [comment]
@nhovratov Hi, do you happen to have a screenshot of what Mask is supposed to look like in mobile state?

**Comment by nhovratov** [comment]
@rowild Yeah I think it's not optimized at all for mobile view.
