### ISSUE TITLE
Page Templates elements doesn't show

### ISSUE THREAD

**Issue by plojewski** [Gernott/mask#345]
Hi, I use Typo3 10.4.6 and Mask 5.1.2. When I add some fields to Page Templates, it doesn't show in page edit. Content Elements works fine, so mask.json is ok. This is the code for 'pages':

<pre>
"pages": {
        "elements": {
            "Subpage": {
                "columns": [
                    "tx_mask_page_settings",
                    "tx_mask_submenu_icon",
                    "tx_mask_hidden_header"
                ],
                "description": "dummy description",
                "key": "Subpage",
                "label": "Subpage",
                "labels": [
                    "Page settings",
                    "Submenu icon",
                    "Hide page header"
                ],
                "shortLabel": "dummy shortitle"
            },
            "SubpageAside": {
                "columns": [
                    "tx_mask_page_settings",
                    "tx_mask_submenu_icon",
                    "tx_mask_hidden_header"
                ],
                "description": "dummy description",
                "key": "SubpageAside",
                "label": "Subpage with aside",
                "labels": [
                    "Page settings",
                    "Submenu icon",
                    "Hide page header"
                ],
                "shortLabel": "dummy shortitle"
            }
        },
        "sql": {
            "tx_mask_hidden_header": {
                "pages": {
                    "tx_mask_hidden_header": "int(11) DEFAULT '0' NOT NULL"
                }
            },
            "tx_mask_submenu_icon": {
                "pages": {
                    "tx_mask_submenu_icon": "int(11) unsigned DEFAULT '0' NOT NULL"
                }
            }
        },
        "tca": {
            "tx_mask_hidden_header": {
                "config": {
                    "cols": "",
                    "default": "",
                    "items": [
                        [
                            "Disable",
                            "1"
                        ]
                    ],
                    "renderType": "checkboxToggle",
                    "type": "check"
                },
                "description": "",
                "exclude": "1",
                "key": "hidden_header",
                "l10n_mode": ""
            },
            "tx_mask_page_settings": {
                "config": {
                    "type": "tab"
                },
                "description": "",
                "key": "page_settings"
            },
            "tx_mask_submenu_icon": {
                "config": {
                    "appearance": {
                        "fileUploadAllowed": "1"
                    },
                    "filter": [
                        {
                            "parameters": {
                                "allowedFileExtensions": "svg"
                            }
                        }
                    ],
                    "maxitems": "1",
                    "minitems": ""
                },
                "description": "",
                "exclude": "1",
                "key": "submenu_icon",
                "l10n_mode": "",
                "options": "file"
            }
        }
    },
</pre>

The fields in database are created. Could you please help me?

**Comment by nhovratov** [comment]
Hi @plojewski, this was fixed quite recently: https://github.com/Gernott/mask/pull/341

**Comment by plojewski** [comment]
@nhovratov OK! When will the new revised version be released: https://extensions.typo3.org/extension/mask/ (without this bug) ?

**Comment by nhovratov** [comment]
@plojewski Hopefully as soon as possible :) I'm not in power to do it, but i can try to ask!

**Comment by plojewski** [comment]
Thank you!
