### ISSUE TITLE
Nesting like flux:grid.column

### ISSUE THREAD

**Issue by artur-grigoryan-cgn** [Gernott/mask#351]
Hi,
i just switched form flux to mask and it tried to create a container and a grid element with mask. Is it possible to create something like this (Container Column 1 and 2): 
![Bildschirmfoto vom 2020-09-22 10-46-48](https://user-images.githubusercontent.com/16120407/93862405-4930a080-fcc2-11ea-9c4b-06804afc8bf9.png)
The Content Element isn't very helpfull.
Regards

**Comment by nhovratov** [comment]
Hi @artur-grigoryan-cgn ,
mask is only a visual builder for content elements, without structural elements.
If you want to migrate from flux i can recommend [gridelements](https://github.com/TYPO3-extensions/gridelements)
