### ISSUE TITLE
not possible to use with mask created content elements if mask_export is active

### ISSUE THREAD

**Issue by bh-teufels** [Gernott/mask#352]
it is not possible to use with mask created content elements (Tab "Mask elements" missing in Create new content element)
when mask_export Extension is active. 

Versions:
Typo3 10.4.8
mask 5.1.3
mask_export 3.0.2

not sure if problem causes by mask or mask_export

**Comment by nhovratov** [comment]
Hi @bh-teufels
This is intended by the mask_export extension, as you can only use either mask elements or the exported ones.
They work very differently, so to not cause any trouble mask elements are deactivated.
