### ISSUE TITLE
translations for the backend?

### ISSUE THREAD

**Issue by TrueType** [Gernott/mask#362]
Hi,
https://github.com/Gernott/mask/blob/master/Resources/Private/Language/de.locallang_mask.xlf
Usually translations are downloaded from the translation server? In this case we have DE-language files for the backend. Please check this files and drop the <source> tags where there should be <target> tags. One does not expect that and has a hard time with it. 

greetz

**Comment by nhovratov** [comment]
Hi @TrueType ,
what is the problem exactly, you are having a hard time with?

**Comment by TrueType** [comment]
@nhovratov see the de.xlf files ... instead of <target> you have <source> there for some of the entries. I just wanted to change the header of the tab of the new content wizard(Mask-Elemente) and copied the original .xlf files to edit them. What I did not recognize was there is a <source> tag instead of an <target> tag you would expect in the translation file.

**Comment by nhovratov** [comment]
> What I did not recognize was there is a tag instead of an tag you would expect in the translation file.
Do you mean the source / target tags? What tag you would expect?

**Comment by nhovratov** [comment]
Issue is not clear enough. Closing it. You can create a new issue and describe your problem more precise.
