### ISSUE TITLE
Switch to new documentation rendering mechanism

### ISSUE THREAD

**Issue by remonator** [Gernott/mask#364]
See the autogenerated message:

_This documentation is not using the current rendering mechanism and will be deleted by December 31st, 2020. The extension maintainer should switch to the new system. Details on how to use the rendering mechanism can be found [here](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Index.html)._

**Comment by nhovratov** [comment]
Thanks, we will take care of it before December 31st, 2020!
