### ISSUE TITLE
Recurring elements from workspace are shown in live-mode

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [Gernott/mask#366]
Hi,

we have some mask-content-elements with recurring elements (purple icon) which i will call records. Whenever you add new records in workspace, these elements are shown in the frontend in live-mode! Looking at the data I can see the following:

      t3ver_id => 1 (integer)
      t3ver_wsid => 1 (integer)
      t3ver_label => 'First draft version' (19 chars)
      t3ver_state => -1 (integer)
      t3ver_stage => 0 (integer)
      t3ver_count => 0 (integer)
      t3ver_tstamp => 0 (integer)
      t3ver_move_id => 0 (integer)
	  
As you can see they are workspace-records that shouldn't appear in live-mode. I can workaround it with

`<f:if condition="({workspaceIsLive} && {item.t3ver_state} == 0) || {workspaceId} == {item.t3ver_wsid}">`

after the foreach loop but of course it's not what I want.

Not sure if this is one of the "many, many bugfixes" from your latest release or a core problem?

Thanks in advance!

TYPO3 9.5.22
Mask 4.1.2

**Comment by nhovratov** [comment]
Hi @h-e-l-l-o-w-o-r-l-d 
maybe it's this issue? https://github.com/Gernott/mask/issues/244

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hi Nikita,

Thanks for your fast reply! I was aware of that task but didn't consider it to be related with our problem, as we don't have double entries. The problem is only workspace records in live-mode.

I did a quick test and added the following to the InlineHelper.php just like seen on https://github.com/Gernott/mask/commit/95209672b872685aed66d4850b99c544c10800e0.

```
 if (BackendUtility::isTableWorkspaceEnabled($childTable)) {
            $queryBuilder->getRestrictions()->add(GeneralUtility::makeInstance(WorkspaceRestriction::class, (int)$GLOBALS['BE_USER']->workspace));
        }
```

Indeed the problem is gone. So yes, it is related! I reckon Mask 4.x won't be updated with that fix, right? If so, I'd probably prefer waiting for the switch to TYPO3 10 instead of creating an XClass.

Cheers!

**Comment by nhovratov** [comment]
Great, indeed it's not possible to add a patch for older versions for extensions.
Until you migrate to v10 you can just override mask directly.
