### ISSUE TITLE
Repeating Elements in Palette

### ISSUE THREAD

**Issue by thomas-niederberger** [Gernott/mask#369]
I added repeating elements in a palette, use the offered Source Code from the Mask element to print it out, and get the following error:
The argument "each" was registered with type "array", but is of type "integer" in view helper "TYPO3Fluid\Fluid\ViewHelpers\ForViewHelper".

If I debug the output, the repeating elements are shown but without content.

**Comment by nhovratov** [comment]
Thank you very much for the report! The new version will be released today.
