### ISSUE TITLE
Richtext-Fields switch to Text-Fields when using Tabs / Palettes

### ISSUE THREAD

**Issue by oh-li** [Gernott/mask#371]
TYPO3 10.4.9
Mask 6.0.1 and 6.10
Just trying to setup a new Mask-element using Tabs and Palettes.
What I do:
1. Adding a Tab (or a Palette)
2. Adding two Richtext-Fields
3. Saving = OK
4. Adding another Tab (or a Palette) underneath
5. Adding two more RT-fields
6. Saving
7. The last two fields stay RT the first two I added switch automatically to Text
8. This behaviour goes on, when adding mire Tabs or Palettes
Without Tabs or with other fields I didn't encounter this problem.

Just to let you know.
Anyway - thanks for this great extension.
Olli

**Comment by nhovratov** [comment]
Wow, nice catch! Seems to happen always on the second save when in a palette.
Will fix asap.

**Comment by oh-li** [comment]
Cool - that was a quick reaction.
Thanks for the info!
