### ISSUE TITLE
Missing Link Styles in RTE Field

### ISSUE THREAD

**Issue by AnnikaSchuster** [Gernott/mask#372]
Object Styles in Mask RTE are missing, so Link class is not available. In normal Content Elements they are shown.

**Comment by nhovratov** [comment]
@AnnikaSchuster May I ask you what Mask Version you are using?

**Comment by AnnikaSchuster** [comment]
Mask Version 5.1.1 and Typo3 10.4.9

**Comment by nhovratov** [comment]
Can you update to mask 6 and run the new upgrade wizard?
I suppose you are using either a custom rte style or the "full" style. In older versions of mask all rte fields got the "default" style.

**Comment by AnnikaSchuster** [comment]
i updated to 6, run the upgrad wizard and now it works! Thank you
