### ISSUE TITLE
IRRE element in workspace assigned to same colPos as parent element (v4.1.2)

### ISSUE THREAD

**Issue by StrikeAgainst** [Gernott/mask#373]
I have an issue regarding Mask version 4.1.2, which I'm forced to use since I'm stuck with TYPO3 version 9.5.22.

I've created a simple accordion element with Mask, which uses an IRRE element to display as content. Works all fine on live, but doing so in a workspace will place the IRRE element itself into the same column as the accordion. I checked the `tt_content `table and found out that the IRRE element is not assigned a `colPos` value of 999, as it would happen on live, so it seems the workspace configuration is overriding that value.

As far as I know this issue is already fixed with the newer versions, but I'm stuck with 4.1.2 for now. I don't mind fixing the issue in the local code by myself, I'm just not sure where and how. Could someone enlighten me on what I need to do?

**Comment by nhovratov** [comment]
I couldn't find exactly an old issue for the problem you are refering to. Are you using gridelements too?

**Comment by StrikeAgainst** [comment]
Yes I am, might this be the issue?

**Comment by nhovratov** [comment]
is this related to your issue? https://github.com/Gernott/mask/issues/219
There is no mention of workspaces though.

**Comment by StrikeAgainst** [comment]
Oh yeah, that's actually it. Yeah, I have no idea why it only happens with workspaces though. Anyway, this fixed it for now. I couldn't find out how to hide the additional column in the backend though, but I think it might be fine to keep it visible for now. Thank you!

**Comment by nhovratov** [comment]
It is possible with TSconfig `colPos_list`: https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/PageTsconfig/Mod.html#colpos-list
