### ISSUE TITLE
Exception when placing a 'Group' inside a 'Repeating' block

### ISSUE THREAD

**Issue by ped** [Gernott/mask#374]
TYPO3 Version: 10.4.9
Mask Version: 6.2.2

When adding a 'Group' element inside a 'Repeating' block TYP3 will throw a TypeError when trying to save the element. 

### How to reproduce: 

- Create new mask element
- Create 'Repeating' block 
- Place 'Group' element inside the block and configure everythin
- Hit 'Save'
- -> Get the error

### The error:

Upon saving TYPO3 will throw the following error: 

(1/1) TypeError
uasort() expects parameter 1 to be array, null given

### The error message:

![CleanShot 2020-11-10 at 15 34 05](https://user-images.githubusercontent.com/36962867/98687629-39504700-236a-11eb-9f2a-8fa3900474e2.png)

### The mask element:

![CleanShot 2020-11-10 at 15 35 06](https://user-images.githubusercontent.com/36962867/98687724-5c7af680-236a-11eb-85a4-6fa7ccdaafaa.png)

**Comment by nhovratov** [comment]
Somehow your field name is messed up. The table shouldn't be called `tx_mask_related_tx_mask_related_pages`, should it? I can't explain why your mask tca is empty, too.
I suspect something went wrong while creating the element (not saved correctly idk, could be a bug maybe).
Hence I suggest you rollback your mask.json to the last functioning state (if you hopefully used version control) and start over.
And one last thing: How do you have this amazing (typo3) table flip in your exception?

**Comment by ped** [comment]
I have since tried to reproduce the bug, but couldn't. 
After the bug occurred I rolled back my mask.json to the last working version, so that's also not an issue.
So I guess it was some kind of bug? I don't know for sure. It's working now, so I guess this is a non issue. 

And for the table flip exception: This is from a little chrome extension a collegue of mine wrote. 
You can find it here on the Chrome extension store -> [T3nhance](https://chrome.google.com/webstore/detail/t3nhance/abehcgeppbcjfckdoaccjfengclahbem?itemlang&hl=de&q=reload) 😄
