### ISSUE TITLE
Using field describtion throws exception

### ISSUE THREAD

**Issue by rboenischAqua** [Gernott/mask#376]
Hi, 

i'm using Mask 6.2.2,

When I create an element and add a "Description for editors" to a field, I cannot reopen the element again.
An exception is thrown:
![grafik](https://user-images.githubusercontent.com/20222455/98968036-79036400-250d-11eb-867e-bfacd4a7a58d.png)

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of MASK\Mask\Helper\FieldHelper::getLabel() must be of the type string, null returned | TypeError thrown in file /var/www/html/public/typo3conf/ext/mask/Classes/Helper/FieldHelper.php in line 71. Requested URL: https://hcqs.ddev.site/typo3/index.php?route=%%2Fmodule%%2Ftools%%2FMaskMask&token=--AnonymizedToken--&tx_mask_tools_maskmask%%5Btype%%5D=tt_content&tx_mask_tools_maskmask%%5Bkey%%5D=centraltext&tx_mask_tools_maskmask%%5Baction%%5D=edit&tx_mask_tools_maskmask%%5Bcontroller%%5D=WizardContent 

When I look at the json is in one of the appropriate place: 
`"labels": {
                    "--index--": "Text"
        }`
But the requested index here is "0".

Here is my complete json (where the elements "colored_link" and "centraltext" are affected):
`{
    "tt_content": {
        "elements": {
            "centraltext": {
                "color": "#000000",
                "columns": {
                    "0": "ct_header",
                    "--index--": "tx_mask_",
                    "1": "ct_text"
                },
                "description": "",
                "icon": "fa-align-center",
                "key": "centraltext",
                "label": "Modul: zentraler Text ",
                "labels": {
                    "--index--": "Text"
                },
                "options": {
                    "--index--": "rte"
                },
                "shortLabel": ""
            },
            "colored_link": {
                "color": "#ff00ff",
                "columns": {
                    "--index--": "tx_mask_",
                    "0": "cl_ancor",
                    "1": "cl_color"
                },
                "description": "",
                "icon": "fa-chain",
                "key": "colored_link",
                "label": "farbiger HCQS Link",
                "labels": {
                    "--index--": "Farbe"
                },
                "shortLabel": ""
            },
            "headerpicture": {
                "color": "#8000ff",
                "columns": [
                    "header",
                    "subheader",
                    "image",
                    "imageheight",
                    "tx_mask_css_classes"
                ],
                "description": "",
                "icon": "fa-image",
                "key": "headerpicture",
                "label": "Modul: Header-Bild mit Text",
                "labels": [
                    "Haupttext",
                    "Untertitel",
                    "Hintergrundbild",
                    "",
                    "zus\u00e4tzliche CSS-Klassen"
                ],
                "shortLabel": ""
            },
            "headline": {
                "color": "#000000",
                "columns": [
                    "tx_mask_headline",
                    "tx_mask_hl_id"
                ],
                "description": "",
                "icon": "fa-h-square",
                "key": "headline",
                "label": "Modul: \u00dcberschrift",
                "labels": [
                    "\u00dcberschrift",
                    "ID f\u00fcr Anker (muss auf der Seite eindeutig sein)"
                ],
                "options": [
                    "rte"
                ],
                "shortLabel": ""
            },
            "parallax": {
                "color": "#000000",
                "columns": [
                    "header",
                    "tx_mask_css_classes",
                    "image",
                    "tx_mask_height"
                ],
                "description": "",
                "icon": "fa-picture-o",
                "key": "parallax",
                "label": "Modul: seitenbreites Bild (Paralllax)",
                "labels": [
                    "interner Titel",
                    "zus\u00e4tzliche CSS-Klassen",
                    "Bild",
                    "H\u00f6he des Bildes (in Pixel)"
                ],
                "shortLabel": ""
            },
            "text2colbox": {
                "color": "#000000",
                "columns": [
                    "header",
                    "tx_mask_items"
                ],
                "description": "",
                "icon": "fa-th-large",
                "key": "text2colbox",
                "label": "Modul: Text 2-Spaltig - Boxen",
                "labels": [
                    "Titel",
                    "Inhalt"
                ],
                "options": {
                    "3": "rte"
                },
                "shortLabel": ""
            },
            "text2colfloat": {
                "color": "#000000",
                "columns": [
                    "header",
                    "tx_mask_items"
                ],
                "description": "",
                "icon": "fa-columns",
                "key": "text2colfloat",
                "label": "Modul: Text 2-Spaltig - Flie\u00dftext",
                "labels": [
                    "",
                    "Inhalt"
                ],
                "options": {
                    "3": "rte"
                },
                "shortLabel": ""
            }
        },
        "sql": {
            "tx_mask_": {
                "tt_content": {
                    "tx_mask_": "mediumtext"
                }
            },
            "tx_mask_css_classes": {
                "tt_content": {
                    "tx_mask_css_classes": "tinytext"
                }
            },
            "tx_mask_headline": {
                "tt_content": {
                    "tx_mask_headline": "mediumtext"
                }
            },
            "tx_mask_height": {
                "tt_content": {
                    "tx_mask_height": "tinytext"
                }
            },
            "tx_mask_hl_id": {
                "tt_content": {
                    "tx_mask_hl_id": "tinytext"
                }
            },
            "tx_mask_items": {
                "tt_content": {
                    "tx_mask_items": "int(11) unsigned DEFAULT '0' NOT NULL"
                }
            }
        },
        "tca": {
            "tx_mask_": {
                "config": {
                    "autoSizeMax": "",
                    "autocomplete": "0",
                    "behaviour": {
                        "allowLanguageSynchronization": "0"
                    },
                    "cols": "",
                    "default": "",
                    "enableRichtext": "1",
                    "eval": "",
                    "fileFolder": "",
                    "fileFolder_extList": "",
                    "fileFolder_recursions": "",
                    "foreign_table": "",
                    "foreign_table_where": "",
                    "is_in": "",
                    "max": "",
                    "maxitems": "",
                    "mode": "",
                    "placeholder": "",
                    "renderType": "selectSingle",
                    "rows": "",
                    "size": "",
                    "softref": "rtehtmlarea_images,typolink_tag,images,email[subst],url",
                    "type": "text",
                    "wrap": "off"
                },
                "description": "",
                "exclude": "1",
                "key": null,
                "l10n_mode": ""
            },
            "tx_mask_css_classes": {
                "config": {
                    "default": "",
                    "eval": "",
                    "is_in": "",
                    "max": "",
                    "placeholder": "",
                    "size": "",
                    "type": "input"
                },
                "description": "",
                "exclude": "1",
                "key": "css_classes",
                "l10n_mode": ""
            },
            "tx_mask_headline": {
                "config": {
                    "behaviour": {
                        "allowLanguageSynchronization": "0"
                    },
                    "cols": "",
                    "default": "",
                    "enableRichtext": "1",
                    "eval": "required",
                    "max": "",
                    "mode": "",
                    "placeholder": "",
                    "rows": "",
                    "softref": "rtehtmlarea_images,typolink_tag,images,email[subst],url",
                    "type": "text",
                    "wrap": "off"
                },
                "description": "",
                "exclude": "1",
                "key": "headline",
                "l10n_mode": ""
            },
            "tx_mask_height": {
                "config": {
                    "default": "400",
                    "eval": "int",
                    "max": "",
                    "placeholder": "",
                    "range": {
                        "lower": "",
                        "upper": ""
                    },
                    "size": "",
                    "type": "input"
                },
                "description": "",
                "exclude": "1",
                "key": "height",
                "l10n_mode": ""
            },
            "tx_mask_hl_id": {
                "config": {
                    "autocomplete": "0",
                    "behaviour": {
                        "allowLanguageSynchronization": "0"
                    },
                    "default": "",
                    "eval": "",
                    "is_in": "",
                    "max": "",
                    "mode": "",
                    "placeholder": "",
                    "size": "",
                    "type": "input"
                },
                "description": "",
                "exclude": "1",
                "key": "hl_id",
                "l10n_mode": ""
            },
            "tx_mask_items": {
                "config": {
                    "appearance": {
                        "collapseAll": "1",
                        "enabledControls": {
                            "dragdrop": "1"
                        },
                        "levelLinksPosition": "both",
                        "newRecordLinkTitle": "neuer Text",
                        "showAllLocalizationLink": "1",
                        "showPossibleLocalizationRecords": "1",
                        "showRemovedLocalizationRecords": "1",
                        "showSynchronizationLink": "1",
                        "useSortable": "1"
                    },
                    "foreign_field": "parentid",
                    "foreign_sortby": "sorting",
                    "foreign_table": "--inlinetable--",
                    "foreign_table_field": "parenttable",
                    "maxitems": "",
                    "minitems": "1",
                    "type": "inline"
                },
                "description": "",
                "exclude": "1",
                "inlineIcon": "",
                "inlineLabel": "",
                "key": "items",
                "l10n_mode": ""
            }
        }
    },
    "tx_mask_items": {
        "sql": {
            "tx_mask_item_header": {
                "tx_mask_items": {
                    "tx_mask_item_header": "tinytext"
                }
            },
            "tx_mask_item_text": {
                "tx_mask_items": {
                    "tx_mask_item_text": "mediumtext"
                }
            }
        },
        "tca": {
            "tx_mask_item_header": {
                "config": {
                    "default": "",
                    "eval": "",
                    "is_in": "",
                    "max": "",
                    "placeholder": "",
                    "size": "",
                    "type": "input"
                },
                "description": "",
                "exclude": "1",
                "inlineParent": "tx_mask_items",
                "key": "item_header",
                "l10n_mode": "",
                "label": "\u00dcberschrift",
                "order": 2
            },
            "tx_mask_item_text": {
                "config": {
                    "cols": "",
                    "default": "",
                    "enableRichtext": "1",
                    "eval": "",
                    "max": "",
                    "placeholder": "",
                    "rows": "",
                    "softref": "rtehtmlarea_images,typolink_tag,images,email[subst],url",
                    "type": "text"
                },
                "description": "",
                "exclude": "1",
                "inlineParent": "tx_mask_items",
                "key": "item_text",
                "l10n_mode": "",
                "label": "Text",
                "order": 3,
                "rte": "1"
            }
        }
    },
    "tx_mask_undefined": {
        "sql": {
            "tx_mask_item_header": {
                "tx_mask_undefined": {
                    "tx_mask_item_header": "tinytext"
                }
            },
            "tx_mask_item_text": {
                "tx_mask_undefined": {
                    "tx_mask_item_text": "mediumtext"
                }
            }
        },
        "tca": {
            "tx_mask_item_header": {
                "config": {
                    "autocomplete": "0",
                    "behaviour": {
                        "allowLanguageSynchronization": "0"
                    },
                    "default": "",
                    "eval": "",
                    "is_in": "",
                    "max": "",
                    "mode": "",
                    "placeholder": "",
                    "size": "",
                    "type": "input"
                },
                "description": "",
                "exclude": "1",
                "inlineParent": "tx_mask_undefined",
                "key": "item_header",
                "l10n_mode": "",
                "label": "\u00dcberschrift",
                "order": 2
            },
            "tx_mask_item_text": {
                "config": {
                    "behaviour": {
                        "allowLanguageSynchronization": "0"
                    },
                    "cols": "",
                    "default": "",
                    "enableRichtext": "1",
                    "eval": "",
                    "max": "",
                    "mode": "",
                    "placeholder": "",
                    "rows": "",
                    "softref": "rtehtmlarea_images,typolink_tag,images,email[subst],url",
                    "type": "text",
                    "wrap": "off"
                },
                "description": "",
                "exclude": "1",
                "inlineParent": "tx_mask_undefined",
                "key": "item_text",
                "l10n_mode": "",
                "label": "Text",
                "order": 3,
                "rte": "1"
            }
        }
    }
}`

**Comment by nhovratov** [comment]
@rboenischAqua Hi, there are a lot of placeholders like `--index--` that did not get replaced. I don't know how this could happen. This is done in JavaScript, so there possibly went something wrong. Either way I would suggest deleting `centraltext ` and `colored_link` and start over.
Just for the record: Did you do something special? Updating from older mask version? Anything would be helpful.

**Comment by rboenischAqua** [comment]
@nhovratov Hi, thanks for your reply. I updated from mask 5.1.3 and did not manually changed the mask.json.
I will delete the two affected elements and try again. If it doesn't work, I will reinstall mask and re-create all elements.

**Comment by nhovratov** [comment]
@rboenischAqua Ah ok, could be some bug from the update then, maybe JavaScript cache from old version.

**Comment by rboenischAqua** [comment]
@nhovratov After deleting the two elements and typo3temp/assets it works now.
I noticed that saving an element takes quite a long time (but this could be due to my development environment with DDEV on Win10). Maybe I changed the view too fast, so that it could not save correctly.

**Comment by nhovratov** [comment]
Ok, great! I'll close this then. If anything comes up again, feel free to create a new issue.
