### ISSUE TITLE
Workspace preview not working with normal fields

### ISSUE THREAD

**Issue by nhovratov** [Gernott/mask#377]
Hi all,

I have the same issue, but NOT with repeating elements.

Problem: Can't preview changes in the backend when I'm in workspace.

Info:

- Backend template is a copy of the frontend template.
- Only happens with non repeating fields. Changes in reapeating fields are shown.
- Live-mode is okay
- Frontend is okay.
- When I jump into the content element to edit it, the changes are shown.

With <f:debug> I can see that the initial record is delivered but not the workspace record. Can you give me a hint what could be wrong?

TYPO3 9.5.23 and Mask 4.1.3

_Originally posted by @h-e-l-l-o-w-o-r-l-d in https://github.com/Gernott/mask/issues/126#issuecomment-738752646_

**Comment by nhovratov** [comment]
@h-e-l-l-o-w-o-r-l-d
Hi, thanks for the report. Do normal content-elements work? I can't get the preview to work at all.
Post some screenshots if possible, that would be great.

**Comment by nhovratov** [comment]
In TYPO3 10 everything works fine btw. I suggest updating if possible!

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hi Nikita,

thanks for the fast reply. I forgot to mention, that native TYPO3 content elements work as expected, so it must be a mask-issue. ;)

Unfortunately updating to TYPO3 10 is not possible at the moment, as not all of the used extensions are ready for V10. But we would be happy to simply patch some mask files.

Would be glad to provide screenshots. What exactly to you need?

**Comment by nhovratov** [comment]
Hey helloworld,

I spent some time investigating, but for me even the native elements didn't work. I must admit, I never used the workspace feature. Maybe you could show me step for step how to reproduce. If you want even in slack via screenshare.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Thanks for the time you investigated. I don't use slack right now and no screen video capturing available on my laptop either. But I can record a video the old school way with a camera. :)

I don't want to get the information spread on the web, so is it okay to send the download-link to your email-address I found on your website? German okay or english?

**Comment by nhovratov** [comment]
Oh, ok thats no problem. Then send me the link! German is preferred of course :)

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Sent. :)
