### ISSUE TITLE
Nested CEs TYPO3 10

### ISSUE THREAD

**Issue by pt-webprofil** [Gernott/mask#380]
I created a nested CE. The CEs created in the repeating area are displayed individually on the overview page.
<img width="582" alt="Bildschirmfoto 2021-01-29 um 15 14 34" src="https://user-images.githubusercontent.com/34335026/106285709-133d9300-6245-11eb-9438-dfb072feacf3.png">
<img width="585" alt="Bildschirmfoto 2021-01-29 um 15 14 24" src="https://user-images.githubusercontent.com/34335026/106285765-281a2680-6245-11eb-94d2-f7a0ea039ec8.png">

TYPO3 10.4.12
Mask 6.4.1

**Comment by nhovratov** [comment]
Hmm, I cannot reproduce this behaviour. Can you open one child record and look if in colPos stands 999 ?

**Comment by florianpernter** [comment]
Hello, i'm having the same problem. Is there any solution?

**Comment by nhovratov** [comment]
@florianpernter Hi, would you like to provide a step by step list, how to reproduce?

**Comment by florianpernter** [comment]
@nhovratov i installed Mask (6.6.3) on my Typo3 (10.4.14) and got the same error as pt-webprofil as soon as i tried to create a Nested Content.
![Screenshot 2021-04-06 143201](https://user-images.githubusercontent.com/38750485/113712877-f6ab5480-96e6-11eb-94e1-b5625731c3dc.jpg)
![Screenshot 2021-04-06 144629](https://user-images.githubusercontent.com/38750485/113712880-f743eb00-96e6-11eb-8193-b40e87a2146e.jpg)

**Comment by nhovratov** [comment]
@florianpernter Any noteworthy extensions installed besides mask?

**Comment by nhovratov** [comment]
I still couldn't reproduce this behaviour. This must be happening under a certain condition I am not aware of.

**Comment by nhovratov** [comment]
@florianpernter 

Got feedback, that this doesn't happen anymore since recent releases of TYPO3/Mask.
If you think this is still an issue, please reopen and explain how to reproduce this behaviour.
