### ISSUE TITLE
Error 403 in Linkwizard when Linkfield is not empty

### ISSUE THREAD

**Issue by anderlk** [Gernott/mask#381]
Linkwizard throws up error 403, when linkfield is not empty. Start linkwizard with empty linkfield there are no problems.

![Bildschirmfoto 2021-02-02 um 22 27 53](https://user-images.githubusercontent.com/12695520/106665308-68abd400-65a6-11eb-90fa-7d1f0dff3dc4.png)

**Comment by nhovratov** [comment]
@anderlk Hi Andreas, what do you mean with empty linkfield? You mean if you set a default value?

**Comment by anderlk** [comment]
Hi @nhovratov i've tested around a bit. The point is the "http://". If the link contains an "http://" or "https://" you can't edit the link again, because the error 403 appears in the linkwizard.  Without http://, or with internal page, there is no error.

Mask version is 6.4.2 on TYPO3 10.4.1. I've updated Mask a day before in the hope that this bug would be eliminated with it.

**Comment by nhovratov** [comment]
@anderlk Hej, this is most probably not a mask bug. But you have a very old typo3 version, current version ist 10.4.12. Maybe try to update and see if this resolves your issue.

**Comment by anderlk** [comment]
Thanks for helping. Thats it. After Update it works.
