### ISSUE TITLE
 Selected "Allowed content elements" in Repeating Inline Content ignored after Update from Mask from 5.1.3 to 6.4.2

### ISSUE THREAD

**Issue by eckonator** [Gernott/mask#382]
Hello,
I have discovered a bug in the current extension version 6.x. It is noticeable in an accordion element, in which I have made a selection of possible content elements in the "Allowed Content Elements" Selectbox.

The selection is completely ignored since update from 5.1.3 to 6.4.2. The only thing that is available for selection as Ctype is the felogin. Uninstalling felogin did not bring any improvement. Downgrade to 5.1.3 was the only solution for me to fix the problem.

Tested under TYPO3 10.4.6

**Comment by nhovratov** [comment]
@eckonator Hi Markus, thanks for the report. I tried creating an element in v5 with allowed elements set and upgraded to v6. I can still select all elements. Would you mind sending me your mask.json so I can investigate the issue? E-Mail is ok.

**Comment by eckonator** [comment]
@nhovratov thanks for help - i have send you a email with the affected json.
