### ISSUE TITLE
Internal file references in RTE links not shown

### ISSUE THREAD

**Issue by maschmiede** [Gernott/mask#383]
Hey,

in our environment we've created a new mask element containing a _richtext_ attribute. The system using customer now have added a link in such a RTE field to a new internal file (pdf). Going to _fileadmin_ and having a look on the file there isn't shown a reference to that file at all (- instead of the expected 1).

Is it possible to add that feature? If not, why?

Additional: Using a normal tt_content RTE and creating a link to that file works and increases the number of references as expected. In general it should work.

==========
Environment:
- TYPO3: 10.4.11 (production mode, non-composer)
- mask: 6.4.3
- php: 7.4.14
- mySQL: 5.6.44

**Comment by nhovratov** [comment]
Thank you for the report! Fixed in v4 and v6 branch.
