### ISSUE TITLE
Unexpected content elements in repeating

### ISSUE THREAD

**Issue by plojewski** [Gernott/mask#384]
Hi, I've created mask for accordion with Content field. When I add some content (for example Text), an existing content item from another subpage is added by itself as another item in this field. Explanation in short:

Page uid 1:
Content element:
uid: 100
pid: 1
tx_mask_accordion_repeating_content_parent: 555

Page uid 2:
Content element (mask accordion repeating item):
uid: 555
pid: 2

On page uid 2 there shouldn't exists content element uid 100.

**Comment by nhovratov** [comment]
Hej Piotr,

what mask & TYPO3 version are you using?

**Comment by plojewski** [comment]
Oh sorry.. Typo3 10.4.12, Mask 6.4.3

**Comment by nhovratov** [comment]
Ok, does this happen in backend or frontend (or both) ?

**Comment by plojewski** [comment]
Both. I suspect something is wrong after copying the entire content item. For example:
- Accordion 1
- Accordion repeating belt content:
Text XYZ
Text 123

I copy and Paste Accordion and I've got:
- Accordion 1
- Accordion repeating belt content:
Text XYZ
Text 123
Text XYZ
Text 123
- Accordion 2
- Accordion repeating belt content:
Some content el attachments from other subpage

Please make sure you saved whole Accordion after adding a repeating element. Thank you.

**Comment by nhovratov** [comment]
Hm, I really have trouble to reproduce this. Everything works as it should. Is it possible for you to create a video? Or can you at least send me your mask.json?

**Comment by plojewski** [comment]
@nhovratov Thank you for your reply. I have found the cause of the problem. I just don't know if it's the fault of Mask or the other plug. This problem occurs if the **apache-solr-for-typo3 / solr** 11 plugin (https://extensions.typo3.org/extension/solr) is installed at the same time. I have a video recorded, could I send you? If so, to what e-mail? Thank you.

**Comment by nhovratov** [comment]
@plojewski Hi, yes you can send it to this email here. Thanks for investigating!

**Comment by plojewski** [comment]
@nhovratov Here? Where? :)

**Comment by nhovratov** [comment]
nikita.h@live.de

**Comment by plojewski** [comment]
OK, sent via wetransfer.com (300 MB)

**Comment by nhovratov** [comment]
Ok, I installed typo3 solr and did the exact same as you. But everything works as it should. Maybe it only occurs with a functioning solr core?

**Comment by akiessling** [comment]
Maybe you got hit by https://review.typo3.org/c/Packages/TYPO3.CMS/+/58049 ? Is the error still present?
We had the same issue with random content elements appearing in news records in a v9 instance

**Comment by nhovratov** [comment]
@plojewski Can you confirm this?

**Comment by nhovratov** [comment]
Confirmed to be solved by #428
