### ISSUE TITLE
Backend Layouts using Icon-Identifier cause Exception

### ISSUE THREAD

**Issue by kmzeitgleich** [Gernott/mask#385]
When using an Icon by Identifier instead of a path the fluid viewhelper rendering that icon will cause an exception

Example:
mod.web_layout.BackendLayouts {
    home {
        title = Home
        icon = my-cool-default-icon
....
}

When opening the mask extension
TYPO3Fluid\Fluid\Core\ViewHelper\Exception
Folder "/my-cool-default-icon/" does not exist.

The Icon is registered with the standard approach of the IconRegistry ->registerIcon() function and it works perfectly fine.

Using the old way
icon = EXT:my_ext/Resources/Public/Images/BackendLayouts/my-cool-default-icon.png does work, but seems oldschool to me

**Comment by kmzeitgleich** [comment]
Typo3 Version: 10.4.13
Mask Version: 6.4.4
PHP: 7.4.2

**Comment by nhovratov** [comment]
@kmzeitgleich 
Hi!
I'm pretty sure icon identifier is not supported there. In the docs there is only one example with the full path: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/BackendLayout/Index.html

**Comment by georgringer** [comment]
it was for sure working and I was hit by this issue also with every project but switching that to `EXT:fo/bar.svg` works in backend + in mask
