### ISSUE TITLE
Error Icon with identifier "" is not registered" in Mask Admin Tool

### ISSUE THREAD

**Issue by tieupmedia** [Gernott/mask#388]
When you try to open Admin Tools > Mask, the following error appears, if the 'icon' declaration in Backend Layouts is missing or empty:

> (1/1) #1437425804 TYPO3\CMS\Core\Exception
> 
> Icon with identifier "" is not registered"
> in [...]/public/typo3/sysext/core/Classes/Imaging/IconRegistry.php line 674

The error occurs with mask version 6.4.5 but doesn't appear in 6.4.4. Tested with TYPO3 10.4.13
It might be broken when resolving https://github.com/gernott/mask/issues/385 .?

**Comment by nhovratov** [comment]
Will be fixed asap, thank you!

**Comment by tieupmedia** [comment]
Thank you!!
