### ISSUE TITLE
Parent field in TCA

### ISSUE THREAD

**Issue by kitzberger** [Gernott/mask#389]
We're currently trying to add a copy/paste feature into our container elements we've created with mask. For TYPO3's DataHandler to update the pasted CE it needs to be able to find the "parent" field within the columns array of tt_content's TCA.

In our case it was sufficient to provide this additional TCA here:
```
// Having the parent field present in TCA is mandatory for TYPO3's DataHandler
// to be able to use those fields when updating records via /ajax/record/process
$GLOBALS['TCA']['tt_content']['columns']['tx_ourextension_accordion_items_parent'] = [
    'config' => [
        'type' => 'passthrough'
    ],
];
```

Our goal is to maybe come up with a handy viewhelper to be used within the backend templates to achieve copy/paste and if possible dragndrop functionality for our editors.

**Comment by nhovratov** [comment]
@kitzberger 
Hi Philipp, there is already a tca entry in mask for the parent table. See my attachement:

![Screenshot_2021-02-26 New TYPO3 site  TYPO3 CMS 10 4 13](https://user-images.githubusercontent.com/19343425/109286820-0d76a580-7823-11eb-81b2-012db914fce3.png)

**Comment by kitzberger** [comment]
Nice! So it's only an issue with mask 3.3, I guess. (Yes, we're stuck with this project with TYPO3 8.7)

**Comment by nhovratov** [comment]
Oh, that's a pity :D

**Comment by nhovratov** [comment]
Theoretically it should be there, too. I can't imagine there was such a big change from Version 8 to 10.

**Comment by kitzberger** [comment]
Hm, I've just checked with mask 4.x and TYPO3 9.

SQL:
```
| tx_mask_fancychildren                  | int(10) unsigned       | NO   |     | 0       |                |
| tx_mask_fancychildren_parent           | int(10) unsigned       | NO   | MUL | 0       |                |
```

TCA:
![Screenshot from 2021-02-26 11-43-03](https://user-images.githubusercontent.com/1405149/109290453-e9699300-7827-11eb-8eac-54f735be7098.png)

No `tx_mask_fancychildren_parent` in TCA ;-/

Now I'm gonna check with TYPO3 10, one sec.

**Comment by kitzberger** [comment]
@nhovratov, even with mask 6.4.6 and TYPO3 10 the "parent" field is not being generated as passthrough column in TCA ;-/

![Bildschirmfoto vom 2021-02-26 12-23-52](https://user-images.githubusercontent.com/1405149/109294592-af9b8b00-782d-11eb-951d-b1623d354327.png)

Here's a screenshot of the mask module:
![Bildschirmfoto vom 2021-02-26 12-25-38](https://user-images.githubusercontent.com/1405149/109294754-e671a100-782d-11eb-892d-f0276d6aa73a.png)

**Comment by nhovratov** [comment]
@kitzberger Ah, this field is only set in TCA for IRRE-Fields, which have an own table in the DB. What you need is the same for type content. They add a "xyz_parent" column to tt_content. So you need this field in TCA as passthrough.

**Comment by kitzberger** [comment]
> So you need this field in TCA as passthrough.

Exactly!

I guess there's no reason for not creatign that passthrough column in TCA, is there?

**Comment by nhovratov** [comment]
No there surely isn't. I guess it had no practical use till now :)

**Comment by nhovratov** [comment]
@kitzberger 
I can backport you this feature for v4 branch, but I'm afraid not for v3. If you really need this on TYPO3 8, I could offer you a paid service at a low cost.

**Comment by kitzberger** [comment]
No worries, in our legacy project we've overwritten the TCA already. It's great to have it in the future releases of mask, so we can build upon that! Thanks all lot for your efforts!
Cheers Philipp
