### ISSUE TITLE
CRITICAL inline column image with mask 6.5.0

### ISSUE THREAD

**Issue by Teisi** [Gernott/mask#390]
Get error with mask 6.5.0 (TYPO3 10.4.13) - with 6.4.6 all works fine.
mask 6.5.0 changes line 158 at StorageRepository.php

I have a palette with "tt_content.image" as a field see attachment. This seems to cause this error.
![image](https://user-images.githubusercontent.com/10898521/109676161-b8b39180-7b78-11eb-9469-a69f75c6de30.JPG)

Tue, 02 Mar 2021 16:50:23 +0100 [CRITICAL] request="7c7c64c7f95e8" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1381512761: Invalid value "" for enumeration "MASK\Mask\DataStructure\FieldType" | TYPO3\CMS\Core\Type\Exception\InvalidEnumerationValueException thrown in file C:\MAMP\htdocs\typo3_sources\typo3_src-10.4.10\typo3\sysext\core\Classes\Type\Enumeration.php in line 57. Requested URL: http://domain.localhost/favicon.ico - {"TYPO3_MODE":"FE","exception":"TYPO3\\CMS\\Core\\Type\\Exception\\InvalidEnumerationValueException: Invalid value \"\" for enumeration \"MASK\\Mask\\DataStructure\\FieldType\" in C:\\MAMP\\htdocs\\typo3_sources\\typo3_src-10.4.10\\typo3\\sysext\\core\\Classes\\Type\\Enumeration.php:57\nStack trace:\n#0 C:\\MAMP\\htdocs\\typo3_sources\\typo3_src-10.4.10\\typo3\\sysext\\core\\Classes\\Type\\Enumeration.php(191): TYPO3\\CMS\\Core\\Type\\Enumeration->__construct()\n#1 C:\\MAMP\\htdocs\\directory\\typo3conf\\ext\\mask\\Classes\\Domain\\Repository\\StorageRepository.php(162): TYPO3\\CMS\\Core\\Type\\Enumeration::cast()\n#2 C:\\MAMP\\htdocs\\directory\\typo3conf\\ext\\mask\\Classes\\CodeGenerator\\TyposcriptCodeGenerator.php(147): MASK\\Mask\\Domain\\Repository\\StorageRepository->loadInlineFields()\n#3 C:\\MAMP\\htdocs\\directory\\typo3conf\\ext\\mask\\Classes\\CodeGenerator\\TyposcriptCodeGenerator.php(108): MASK\\Mask\\CodeGenerator\\TyposcriptCodeGenerator->setLabel()\n#4 C:\\MAMP\\htdocs\\directory\\typo3conf\\ext\\mask\\ext_localconf.php(45): MASK\\Mask\\CodeGenerator\\TyposcriptCodeGenerator->generateTsConfig()\n#5 C:\\MAMP\\htdocs\\directory\\typo3conf\\ext\\mask\\ext_localconf.php(65): TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::{closure}()\n#6 C:\\MAMP\\htdocs\\typo3_sources\\typo3_src-10.4.10\\typo3\\sysext\\core\\Classes\\Utility\\ExtensionManagementUtility.php(1578): require('C:\\\\MAMP\\\\htdocs\\\\...')\n#7 C:\\MAMP\\htdocs\\typo3_sources\\typo3_src-10.4.10\\typo3\\sysext\\core\\Classes\\Utility\\ExtensionManagementUtility.php(1562): TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::loadSingleExtLocalconfFiles()\n#8 C:\\MAMP\\htdocs\\typo3_sources\\typo3_src-10.4.10\\typo3\\sysext\\core\\Classes\\Core\\Bootstrap.php(283): TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::loadExtLocalconf()\n#9 C:\\MAMP\\htdocs\\typo3_sources\\typo3_src-10.4.10\\typo3\\sysext\\core\\Classes\\Core\\Bootstrap.php(160): TYPO3\\CMS\\Core\\Core\\Bootstrap::loadTypo3LoadedExtAndExtLocalconf()\n#10 C:\\MAMP\\htdocs\\typo3_sources\\typo3_src-10.4.10\\index.php(12): TYPO3\\CMS\\Core\\Core\\Bootstrap::init()\n#11 C:\\MAMP\\htdocs\\typo3_sources\\typo3_src-10.4.10\\index.php(13): {closure}()\n#12 {main}"}

**Comment by nhovratov** [comment]
Thanks for reporting the issue! Please stay on version 6.4.6 until I found a solution.
