### ISSUE TITLE
Content not scrollable

### ISSUE THREAD

**Issue by kev1896** [Gernott/mask#391]
With smaller screens (I am working on a 13" MacBook) you are not able to scroll inside the extensions and some checkboxes and the icon list ist not reachable without zooming out.

Here is just one example:
<img width="879" alt="Bildschirmfoto 2021-03-11 um 09 41 19" src="https://user-images.githubusercontent.com/19525695/110759539-ffc31600-824d-11eb-8fd1-4741b679a291.png">

**Comment by nhovratov** [comment]
@kev1896 Hi Kevin! Yes, the responsive styling is not optimized very well.. What is your viewport width in px?

**Comment by kev1896** [comment]
Wow, that was fast, thanks for fixing!

**Comment by nhovratov** [comment]
No problem! Leave a message here, if there is still something unusable on your device.
