### ISSUE TITLE
missing *_parent field leads to exception for editors

### ISSUE THREAD

**Issue by medarob** [Gernott/mask#392]
I updated from MASK v6.4.4 (6.4.6 worked too) to v6.6 and now an editor get's the following error after editing an IRRE element inside a news record. The error occured also if the editor edits an IRRE field outside of a news record.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT `sys_language_uid`, `l10n_parent`, `l10n_diffsource`, `hidden`, `starttime`, `endtime`, `parentid`, `parenttable`, `sorting`, `tx_mask_cardaccordioncontent`, `tx_mask_cardaccordioncontent_parent`, `tx_mask_carddescription`, `tx_mask_carddownload`, `tx_mask_cardheader`, `tx_mask_cardimage`, `tx_mask_cardlink`, `t3_origuid`, `l10n_source`, `uid`, `pid`, `sys_language_uid`, `l10n_source`, `l10n_diffsource`, `l10n_parent` FROM `tx_mask_card` WHERE (`uid` = ?) AND (`sys_language_uid` <= ?) AND ((`tx_mask_card`.`deleted` = 0) AND ((`tx_mask_card`.`t3ver_wsid` = 0) OR (`tx_mask_card`.`t3ver_state` <= 0)))' with params [1520, 0]: Unknown column 'tx_mask_cardaccordioncontent_parent' in 'field list' | Doctrine\DBAL\Exception\InvalidFieldNameException thrown in file /var/www/typo3/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 79. Requested URL: ...

The field `tx_mask_cardaccordioncontent_parent` exists in `tt_content` but not in `tx_mask_card`. In `tx_mask_card` there is only the field `tx_mask_cardaccordioncontent` available.

The problem seems to effect only editors. Admins have no problems creating or saving an IRRE field. The field is also not available in the BE.

**Comment by nhovratov** [comment]
@medarob Can you check if this fix works for you?

**Comment by medarob** [comment]
Sorry for the late reply.
Yes, this has worked as far as I know.
