### ISSUE TITLE
Icon Field empty after "Flush all Caches"

### ISSUE THREAD

**Issue by thomas-niederberger** [Gernott/mask#393]
I run the TYPO3 10.4.14 and Mask 6.6.1. At the moment I "Flush all Caches" the Icon field becomes empty after I try to edit a Mask element. When I close the Mask element and reopen it again, the icon field is back on.

**Comment by nhovratov** [comment]
Hi @thomas-niederberger Thomas,

does this happen every time? I can't reproduce this. The icon is visible at all times.

**Comment by nhovratov** [comment]
Should be fixed with v7.
