### ISSUE TITLE
Labels in Content-Fields of BE Layouts are wrong

### ISSUE THREAD

**Issue by intertain** [Gernott/mask#395]
Hi,

we have backendlayouts with wrong labels shown in Backend after opening in Backend mask module (in mask.json the labels are correct). If i save, the wrong labels are written in mask.json (and right labels are overwritten). 
mask.json with correct Labels:
![image](https://user-images.githubusercontent.com/10403035/112960713-f8a07100-9144-11eb-9d2b-96f86ce33a2c.png)
Shown in Backend after opening:
![image](https://user-images.githubusercontent.com/10403035/112960904-2ab1d300-9145-11eb-8911-a67eeb281930.png)

You see, that only the field "Themen" shows the right label. I set it new! The wrong fields are old fields, which were imported via TV Converter bei WEBprofil. Can you see the the problem?

Yours,
Mike

**Comment by intertain** [comment]
Here the TCA part of the Field with label "Farbschema":
![image](https://user-images.githubusercontent.com/10403035/112962270-7dd85580-9146-11eb-8377-98632b1743c3.png)

**Comment by nhovratov** [comment]
Hi, the problem was the additional `label` field in TCA. They should be only in the element level definition in `labels`.
Gernot will send you the fixed mask.json.

Greetings
Nikita
