### ISSUE TITLE
Output as JSON for headless installation

### ISSUE THREAD

**Issue by urbanbratcoder** [Gernott/mask#399]
Hi Folks,

i am trying to cerate a headless installation. I am using mask for some projects and would like to make it work in my headless environment. So i need JSON-Output. I am using the typo3/headless extension. When i am creating a mask-element, the output is like 
```
{
   "id":246,
   "pid":1,
   "type":"mask_test",
   "colPos":2,
   "categories":"",
   "appearance":{
      "layout":"default",
      "frameClass":"default",
      "spaceBefore":"",
      "spaceAfter":""
   },
   "content":{
      "error":"Content Element with uid \"246\" and type \"mask_test\" has no rendering definition!"
   }
}
```
All i would need are the custom fields (name and value) i created within this mask element instead of the content error. And i would like to handle the JSON someway "directly" and not to fake it by the template (this would just be my last resort).
Is there an easy and smooth way to get this done?

Any hint would be great, as i am not that expert in extension coding.

Greetings, Dave

**Comment by nitori** [comment]
The headless extension provides a JSON content object to define how and which fields are emitted in the json output.
Take a look at the configurations for the default contetn elements:
https://github.com/TYPO3-Initiatives/headless/tree/master/Configuration/TypoScript/ContentElement

In the case of mask, you probably "only" need to replicate the configurations. Add one for you custom mask element, e.g.

```
# tt_content.mask_yourmaskelement =< lib.contentElementWithHeader
tt_content.mask_yourmaskelement =< lib.contentElement
tt_content.mask_yourmaskelement {
    fields {
        content {
            fields {
                tx_mask_myfield = TEXT
                tx_mask_myfield {
                    field = tx_mask_myfield
                }
            }
        }
    }
}
```
There should be more than enough examples of how to read the values for various field types.

**Comment by urbanbratcoder** [comment]
Ah, thank you very much! When the solution is so close. I looked at the ts-files. Why i didn't close the circle, i don't know either.

**Comment by saneinsane** [comment]
Is it possible to create new headless content types without having to add TS setup? This requires the default mask TS setup to return a JSON TS object in a headless setup.
Then I could use the custom Loader feature to create new headless content types without coding / deployments.
