### ISSUE TITLE
Textarea: Setting for wrap resets on load, default value should be "virtual"

### ISSUE THREAD

**Issue by cdominpxp** [Gernott/mask#402]
We are using the current version 6.6.5, and the wrap setting in a textarea resets to default ("") on loading an element in the backend module.
In TCA Documentation it says that the default setting is "virtual" and not "" so we had to overwrite it in the TCA that it does the virtual wrap in our content element.

**Comment by nhovratov** [comment]
@cdominpxp Hi, with "" it should do the virtual wrap as it falls back: `'wrap' => (string)($config['wrap'] ?: 'virtual'),`
There was a problem regarding this a few versions earlier (in 6.6.2 an lower). But it was a bit different as you describe.
This "resetting" like you describe is now fixed. I will release a new version soon. Thanks!
