### ISSUE TITLE
PHP Warning: file_exists(): open_basedir restriction in effect.

### ISSUE THREAD

**Issue by Ayronaut** [Gernott/mask#409]
The path is unfortunately shortened or is the error in the relative path specification?

File(/var/www/clients/clientxx/webxx/web/../typo3conf/ext/mask/Resources/Public/Styles/mask.css?1621517445) is not within the allowed path(s): (/var/www/clients/clientxx/webxx/web:/var/www/clients/clientxx/webxx/private:/var/www/clients/clientxx/webxx/tmp:/var/www/domain.tld/web:/srv/www/domain.tld/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/dev/random:/dev/urandom) in /var/www/clients/clientxx/webxx/web/typo3_src-11.2.0/typo3/sysext/core/Classes/Utility/PathUtility.php line 54

Many greetings

Aaron

TYPO3: 11.2.0
PHP-Version: 7.4.18
Mask: 7.0.1

**Comment by nhovratov** [comment]
Hard to tell without knowing your project structure and php.ini settings. PathUtility is trying to access `/var/www/clients/clientxx/webxx/typo3conf` as far as I can see. Is this the correct path?

**Comment by Ayronaut** [comment]
This is exactly the problem, typo3 is located in the /var/www/clients/clientxx/webxx/**web/** directory.

**Comment by nhovratov** [comment]
Well, I don't know where this might come from. Are you on composer mode? Anything other special about your setup? What's your `TYPO3_PATH_ROOT` environment variable? Where and when does this error appear exactly?

**Comment by nhovratov** [comment]
Can you show me the full stacktrace of the error?

**Comment by nhovratov** [comment]
@Ayronaut Any news on this one?

**Comment by nhovratov** [comment]
I'll close this for now. Feel free to reopen, if it is still a problem in your opinion.
