### ISSUE TITLE
be-layout from repeating elements - mask 6 vs. 7

### ISSUE THREAD

**Issue by olafthiel** [Gernott/mask#410]
hi mask-team,

there is a difference in the be-layout from repeating elements between mask 6 and 7, typo3 v10.4.16. is it possible to check this? is it a new feature or a bug? thanks.

![be-mask-6](https://user-images.githubusercontent.com/66680290/120273946-756bda80-c2af-11eb-8a27-0dc8fafec488.png)
screenshot mask 6

![be-mask-7](https://user-images.githubusercontent.com/66680290/120273958-7997f800-c2af-11eb-8f9d-7daaad794305.png)
screenshot mask 7

**Comment by nhovratov** [comment]
Hi @olafthiel,
I have never seen this before.
Can you show me what elements are inside the repeating field?

**Comment by olafthiel** [comment]
Hi @nhovratov,

I have updated mask. The view is correct now. Sorry, I can't reproduce the former view. But I did the same as last time: upgrade/downgrade mask (switch between v6 and v7), clear all the caches and restart typo3. I'll check this on an other server ...

OK, I don't have these problem on a liveserver, only with the localhost. Clearing the local browsercache was helpful. 

Thanks for your help. Please close this issue.
