### ISSUE TITLE
Input field in palette without label

### ISSUE THREAD

**Issue by akiessling** [Gernott/mask#411]
I created a simple element with an 1:n relation to a hotspot-table. 
In there, i added a palette to put the top and left offset fields next to each other.

The generated json structure however seems wrong and the fields inside the palette don't have labels

```
            "tx_mask_left": {
                "config": {
                    "behaviour": {
                        "allowLanguageSynchronization": 1
                    },
                    "eval": "required,num",
                    "type": "input"
                },
                "description": "",
                "inPalette": 1,
                "inlineParent": "tx_mask_a0075e1782347",
                "key": "left",
                "l10n_mode": "",
                "label": {
                    "hotspot": "Abstand Links in %"
                },
                "name": "string",
                "order": {
                    "hotspot": 1
                }
            },
```

The label for the field should not be nested. When i move it up and remove the `hotspot` the label shows up. 

T3 10.4.16
Mask v7.0.6

**Comment by nhovratov** [comment]
Thanks, it's fixed now!
A new save of the element is required to fix the structure.

**Comment by akiessling** [comment]
Awesome, thanks for taking care so fast!
