### ISSUE TITLE
Row size too large MySQL Error

### ISSUE THREAD

**Issue by lordnikkon** [Gernott/mask#412]
When i try to add new Content Elements the following error message appears:

Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535

Any Ideas?

mask version 7.0.9
TYPO3 version 10.4.16 and 10.4.17

![scr_M3838P_140621](https://user-images.githubusercontent.com/6539186/121908442-4f255080-cd2d-11eb-851a-172e6b573352.jpg)

**Comment by nhovratov** [comment]
Hi @lordnikkon,
this is a database error. Have a look at this: https://mariadb.com/kb/en/troubleshooting-row-size-too-large-errors-with-innodb/
There is a section "Solving the Problem".
You may need to change some SQL definitions in mask.json directly to fix it.

**Comment by lordnikkon** [comment]
Hi @nhovratov,

thank you for your answer. I am not sure I understand the solution correctly. Most of the entries are in tt_content. 

`For BLOB and TEXT columns, the DYNAMIC row format can store these columns on overflow pages. See InnoDB DYNAMIC Row Format: Overflow Pages with the DYNAMIC Row Format for more information.`

I have no idea what to do. Do you have any other suggestions?

**Comment by nhovratov** [comment]
Can you show me the structure of your tt_content table?
PhpMyAdmin->Export (only structure)

**Comment by lordnikkon** [comment]
Hi @nhovratov,

thank you for your answer. Here it is:

`
--
-- Table structure for table `tt_content`
--

CREATE TABLE `tt_content` (
  `uid` int(10) UNSIGNED NOT NULL,
  `rowDescription` text COLLATE utf8mb4_unicode_ci,
  `pid` int(11) NOT NULL DEFAULT '0',
  `tstamp` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `crdate` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `cruser_id` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `deleted` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `hidden` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `starttime` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `endtime` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `fe_group` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT '0',
  `editlock` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `sys_language_uid` int(11) NOT NULL DEFAULT '0',
  `l18n_parent` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `l10n_source` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `l10n_state` text COLLATE utf8mb4_unicode_ci,
  `t3_origuid` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `l18n_diffsource` mediumblob,
  `t3ver_oid` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `t3ver_wsid` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `t3ver_state` smallint(6) NOT NULL DEFAULT '0',
  `t3ver_stage` int(11) NOT NULL DEFAULT '0',
  `t3ver_count` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `t3ver_tstamp` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `t3ver_move_id` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `CType` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `header` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `header_position` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `bodytext` mediumtext COLLATE utf8mb4_unicode_ci,
  `bullets_type` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `uploads_description` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `uploads_type` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `assets` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `image` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `imagewidth` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `imageorient` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `imagecols` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `imageborder` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `media` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `layout` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `frame_class` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'default',
  `cols` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `space_before_class` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `space_after_class` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `records` text COLLATE utf8mb4_unicode_ci,
  `pages` text COLLATE utf8mb4_unicode_ci,
  `colPos` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `subheader` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `header_link` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `image_zoom` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `header_layout` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `list_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `sectionIndex` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `linkToTop` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `file_collections` text COLLATE utf8mb4_unicode_ci,
  `filelink_size` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `filelink_sorting` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `filelink_sorting_direction` varchar(4) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `target` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `date` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `recursive` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `imageheight` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `pi_flexform` mediumtext COLLATE utf8mb4_unicode_ci,
  `accessibility_title` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `accessibility_bypass` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `accessibility_bypass_text` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `selected_categories` text COLLATE utf8mb4_unicode_ci,
  `category_field` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `table_class` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `table_caption` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `table_delimiter` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `table_enclosure` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `table_header_position` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `table_tfoot` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `tx_impexp_origuid` int(11) NOT NULL DEFAULT '0',
  `categories` int(11) NOT NULL DEFAULT '0',
  `tx_mask_campaigns_teaser_text` mediumtext COLLATE utf8mb4_unicode_ci,
  `tx_mask_campaigns_teaser_link` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_campaigns_contact_function` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_campaigns_contact_email` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_toolbox_headimage_img` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_toolbox_quote_author` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_toolbox_quote_quote` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_tbx_clstr` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_tbx_clstr_cluster` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_tbx_clstr_ownerfunction` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_tbx_clstr_ownermail` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_tbx_clstr_ownername` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_tbx_clstr_ownertel` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_tbx_clstr_ownerwhatsapp` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_tbx_clstr_ownerimage` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_prese_head_linktofacts` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_head_color` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_prese_bigimage` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_text5050_bl` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_text5050_br` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_text5050_hl` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_text5050_hr` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_textimage5050_bigtext` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_textimage5050_file` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_textimage5050_pre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_texttexttext5050_body` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_texttexttext5050_img` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_texttexttext5050_pre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_texttexttext5050_text` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_text5050text_bl` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_text5050text_br` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_text5050text_hl` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_text5050text_hr` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_text5050text_pl` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_text5050text_pr` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_3points_hl` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_3points_hm` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_3points_hr` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_3points_il` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_3points_im` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_3points_ir` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_3points_tl` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_3points_tm` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_3points_tr` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_imagestats_image` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_imagestats_stats` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_fact_pre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_fact_text` mediumtext COLLATE utf8mb4_unicode_ci,
  `tx_mask_quote_autor` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_quote_text` mediumtext COLLATE utf8mb4_unicode_ci,
  `tx_mask_quote_inverted_autor` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_quote_inverted_text` mediumtext COLLATE utf8mb4_unicode_ci,
  `tx_mask_campaigns_contact_tel` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_campaigns_contact_image` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_campaigns_contact_whatsapp` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_facts_header_select` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tx_mask_facts_content_title_img` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_facts_headline_text_text` mediumtext COLLATE utf8mb4_unicode_ci,
  `tx_mask_facts_headline_text_image_head_image` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `tx_mask_facts_headline_text_image_head_text` mediumtext COLLATE utf8mb4_unicode_ci,
  `tx_mask_test` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tt_content`
--
ALTER TABLE `tt_content`
  ADD PRIMARY KEY (`uid`),
  ADD KEY `parent` (`pid`,`sorting`),
  ADD KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`),
  ADD KEY `language` (`l18n_parent`,`sys_language_uid`),
  ADD KEY `translation_source` (`l10n_source`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tt_content`
--
ALTER TABLE `tt_content`
  MODIFY `uid` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=40;
`

**Comment by nhovratov** [comment]
What database do you have?

**Comment by nhovratov** [comment]
The problem is that you have too many text fields in one table (tt_content), which can't be stored in one row.
Always try to reuse as many core fields as possible.
For example use a generic `tx_mask_link` field for links instead of creating a specific link for each element.

One solution in your case to squeeze in ~15 more fields is to change:
`tx_mask_campaigns_teaser_link`
`tx_mask_campaigns_contact_email`
`tx_mask_prese_head_linktofacts`
to varchar(255) instead of varchar(1024) in your mask.json (if possible).
It won't be overridden on save.

**Comment by nhovratov** [comment]
Read here for in depth explanation: https://docs.typo3.org/p/mask/mask/master/en-us/Troubleshooting/Index.html#on-save-error-row-size-too-large
