### ISSUE TITLE
Wrong fields in backend_layout_next_level hierarchy

### ISSUE THREAD

**Issue by schrob3000** [Gernott/mask#413]
TYPO3 10.4.16
mask 7.0.9

```
Home -> backend_layout_next_level = 1
└── Subpage -> backend_layout_next_level = 10
    └── Subsubpage
```
In this configuration the page properties from "Subsubpage" contains fields from layout 1 (expected: fields from layout 10)

Layout 1 properties
![Bildschirmfoto vom 2021-06-15 17-58-31](https://user-images.githubusercontent.com/1243812/122086695-3e93d980-ce04-11eb-9810-ee2423e18fb6.png)

```
Home -> backend_layout_next_level = 20 (heigher than 10)
└── Subpage -> backend_layout_next_level = 10
    └── Subsubpage
```
In this configuration the page properties from "Subsubpage" contains the correct fields from layout 10

Layout 10 Properties
![Bildschirmfoto vom 2021-06-15 18-00-04](https://user-images.githubusercontent.com/1243812/122086840-62571f80-ce04-11eb-9fe2-fbbca79ff730.png)

**Comment by nhovratov** [comment]
Thanks for the detailed issue! It's fixed now and will be released with 7.0.10.
