### ISSUE TITLE
TypeError in ajax call when no RTE presets exist.

### ISSUE THREAD

**Issue by nitori** [Gernott/mask#417]
This probably only happens if the rte_ckeditor extension has not been enabled.

It happened to me while performing an update from a version that was still using the old RTE, and when trying to use Mask I hadn't activated the new RTE yet.

An easy fix would be to have a fallback list of presets or to at least show an error to the user.

![2021-06-23_141213](https://user-images.githubusercontent.com/1561831/123095197-19b7eb80-d42e-11eb-8a94-5f996f1944ff.png)

**Comment by nhovratov** [comment]
Thanks Lars, will take care!
