### ISSUE TITLE
New element in repeating element changes to text after save

### ISSUE THREAD

**Issue by spoonerWeb** [Gernott/mask#420]
## Versions

* TYPO3 v9.5.27
* mask v4.2.2

## Description

I have a working mask element `slider` which has a repeating element with slides that contains text and image fields. When I want to add a new element (tried with checkbox and file), the element changes to a `text` element after save.
It's not possible to add a new element

## Reproduce

1. Open mask backend module
2. Select an existing mask record with repeating element
3. Add a new element inside repeating element
4. Save

### Before Save

![grafik](https://user-images.githubusercontent.com/1793083/124569741-81b2fc80-de46-11eb-93d0-c6747f710c4d.png)

### After Save

![grafik](https://user-images.githubusercontent.com/1793083/124569812-92637280-de46-11eb-99ef-8efd03037ada.png)

**Comment by nhovratov** [comment]
@spoonerWeb Hi Thomas,

the problem is, it shouldn't be allowed to add existing core fields to repeating fields.
It only works, if you click on the plus-icon (this is the bug).
By dragging the field, you can select your own key.

**Comment by spoonerWeb** [comment]
Thanks, that information helped me. 👍
