### ISSUE TITLE
CE field with same key as Page Content Field shows Tab "Content fields"

### ISSUE THREAD

**Issue by pt-webprofil** [Gernott/mask#421]
TYPO3 10.4.17
Mask 5.1.3

A CE field with same key as Page Content field shows additional Tab "Content fields" in CE. 
The image field appears twice.

![image001](https://user-images.githubusercontent.com/34335026/125242865-89aee880-e2ed-11eb-843f-ad10c3128da5.jpg)

**Comment by nhovratov** [comment]
@pt-webprofil Can you check if this also happens in Mask v6? Version 5 is not supported anymore.

**Comment by nhovratov** [comment]
Fixed in v6.
