### ISSUE TITLE
tt_content label LLL:EXT:path/to/locallang.xlf:key [mask 7.0.14]

### ISSUE THREAD

**Issue by zwenn** [Gernott/mask#422]
Hop, someone can help.

First:
The labels from mask elements in tt_content are not listed in $GLOBALS['TCA'] ['tt_content']['columns']['tx_mask_element']['label'], so I can not override these labels with TCA/Overrides/tt_content.php

<img width="460" alt="tca-no-label" src="https://user-images.githubusercontent.com/6844841/126047678-ccad6e76-27a9-47cd-bf47-1f05d91fa89e.png">

I have locallang.xlf files for translation and want to set the labels via these files.
This works fine for nested elements and palettes.

Second:
If I write LLL:EXT:path/to/locallang.xlf:key direct into the input field of the label, mask converts these statement to the vale of the key after saving.
The next time I got to this element and edit something else and save again, mask writes the value of the key of the lang file to mask.json and translation for this label does not work anymore.

<img width="943" alt="mask-json-diff" src="https://user-images.githubusercontent.com/6844841/126047593-9db4528a-6290-4c6a-873c-9fb083b197d8.png">

Thank your for helping.
Sven

**Comment by nhovratov** [comment]
Hi @zwenn,
First:
Mask sets the labels via TSconfig. This is needed for fields, which are reused in other elements so they can have different labels.

Second:
Eventhough it is not officially supported, i can see how translatable labels can easily work. And they did before!
I create a patch, so it works like before.
