### ISSUE TITLE
No output of palette description

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [Gernott/mask#425]
Hi,

like the title says... if I create a palette and fill the description field of the palette, there's no output of that description in the content element. Or am I missing something?

**Comment by jonaseberle** [comment]
Palette descriptions is [a very recent feature](https://review.typo3.org/c/Packages/TYPO3.CMS/+/62109) that is only available in v11. In the docs, v11 is represented as "master" in the "Release:" toggle.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Ok, thanks for your explanation. So it will work in V11 in mask, right?

**Comment by nhovratov** [comment]
Yes.
