### ISSUE TITLE
[FEATURE] Make palette with image(s) and without fields possible

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [Gernott/mask#426]
Hi,

It would be helpful if one could add an empty palette without fields (unfortunately mask ignores that) and with 2 attributes: description ([doesn't work at the moment](https://github.com/Gernott/mask/issues/425)) and image(s).

Use case: Explain some things about the content element, write use cases, point out difficulties and add screenshot(s) to make things clearer. f.e. how it looks in frontend.

Goal: Editors don't need to look in our manual anymore which is a time eater.

PS: I know there's the content element description already but it's not appropriate for larger explanations.

**Comment by nhovratov** [comment]
Hi @h-e-l-l-o-w-o-r-l-d,

what you are trying to accomplish is a very custom requirement. This is not something Mask can help you with.
Are you familiar with the FormEngine? You could create your own custom renderType and serve static content with information about your content element. Look at this for a first overview: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/7.3/Feature-67229-FormEngineNodeFactoryApi.html

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Thanks Nikita. Might have a look into it later.

**Comment by nhovratov** [comment]
Closing, because it's out of scope for Mask.
