### ISSUE TITLE
Jumping Content-Elements

### ISSUE THREAD

**Issue by MaSa759** [Gernott/mask#428]
Hi, 
I hope this belongs here.  There seems to be an bug, that annoys the editors, because content-elements are "jumping".
Typo3-v10.4, mask 6.x or 7.x
Let there be:
- a Mask-Element "box-loop" with repeating content
- a Mask-Element "image-box" with a file_reference that is allowed in that box-loop

Do the following:

- create 2 box-loops A and B with several boxes
- look at sys_file_reference-ID (eg.15) of one of the image-boxes of box-loop B
- make sure that there is some box-element with the same ID (e.g. 15) in box-loop A

Now the magic trick:

- edit box-loop B
- untoggle the image-box, so that file_reference (15) is loaded
- change the position (sorting) of that image-box
- save

Now for some reason the box-element with ID 15 appears in box-loop B.
Can somebody confirm?

**Comment by nhovratov** [comment]
@MaSa759 Thanks for the report. Could you send me your Mask.json so I can try to reproduce it?

**Comment by MaSa759** [comment]
solved in Typo3 v10.4.16
