### ISSUE TITLE
endless loading if no paths are configured in mask with no error

### ISSUE THREAD

**Issue by pt-webprofil** [Gernott/mask#429]
TYPO3 10.4.20
Mask 7.0.16

If I installed a fresh TYPO3 10 with Mask and I click in the Mask Backend Module "Create new content element" the "Save"-Button the loading animation appears but nothing happens.

This happens if no paths are yet stored in the Mask settings. Maybe you could display an error message here.

**Comment by nhovratov** [comment]
Yep, this not perfect right now.
It would be even better to disallow to create elements completely, if the configuration is missing or the folders/files are not created.
