### ISSUE TITLE
character limit in Mask text fields

### ISSUE THREAD

**Issue by pt-webprofil** [Gernott/mask#430]
In the older Mask versions there was the possibility of a character restriction in text fields. This function is currently missing in mask 7.

**Comment by nhovratov** [comment]
Can you be a little more specific?
Text or normal string fields?
Which option do you mean exactly? Allowed chracaters (is_in) ?

**Comment by nhovratov** [comment]
This?

![Screenshot 2021-09-06 at 17-02-56 New TYPO3 site  TYPO3 CMS 10 4 20](https://user-images.githubusercontent.com/19343425/132236265-07228e0a-9e64-4bbf-8ae1-db58ab673238.png)

**Comment by nhovratov** [comment]
This option is not available for richtexts, but String and Text have it.

**Comment by pt-webprofil** [comment]
That's correct. I thought it worked for RTE too. We have the case that we also need a character restriction for single RTE fields. So we have to look for an other way to do this.

**Comment by nhovratov** [comment]
Ok, I'll close it here, since its not possible with Mask (TCA) directly.
