### ISSUE TITLE
headlines in CE are missing when using workspaces and switching from textmedia to mask element

### ISSUE THREAD

**Issue by medarob** [Gernott/mask#431]
Hi just noticed a bug in Workspaces and not sure if that is Mask or TYPO3 Core related.

I have a Text & Media content element and switch the CType from textmedia to a mask content element.
Then all headlines from the BE options are missing except the TYPO3 core headlines.

![grafik](https://user-images.githubusercontent.com/33951787/132303973-cb60a7e7-d6f1-468b-9e99-495b750d2bc3.png)

If I create the same mask content element as a new element, the headlines are shown.
It seems to only happen when switching the CType in Workspaces.

TYPO3 10.4.20 and Mask 7.0.16, PHP 7.4

**Comment by nhovratov** [comment]
Can confirm. Does also happen outside of workspace context.
In TYPO3 v11 it seems to work though.

**Comment by nhovratov** [comment]
Fixed with 5a66e55e42265e19094405f9b24c240e310c71d5

Will be released in Mask v7.1
