### ISSUE TITLE
Link field: allowedExtensions not working

### ISSUE THREAD

**Issue by seirerman** [Gernott/mask#432]
File extensions defined in the allowedExtensions field of link field are ignored. It works fine or file fields, though.
I was expecting the file picker to show only mp4 files, but every file was selectable. 

I use a link field for videos which could either be local files (allowedExtensions = mp4) or an external URL.

We're still on TYPO3 9.5/mask 4.2.2, so I'm not sure if this has been fixed in newer versions of mask.

**Comment by nhovratov** [comment]
Thank you very much for reporting the issue!
It was indeed fixed in later versions, but I discovered another issue, which is now also fixed.

**Comment by seirerman** [comment]
Thanks a lot, that was quick!

4.2.3 works, after saving the config again.

**Comment by nhovratov** [comment]
No problem! Yes, it only works with a new save.
Starting at version v6 I added a compatibility layer, this would be too complicated for v4, because of legacy code.
