### ISSUE TITLE
Add field type *slug* to field elements

### ISSUE THREAD

**Issue by dev-stefan** [Gernott/mask#437]
Please add the field type *slug* to the fields that can be used for creating a content element.

In best case there should be the possibility to add more "custom" configuration of fields if they are not provided in the default set of available field types.

**Comment by nhovratov** [comment]
Hey @dev-stefan,

of course we can add more fields, if they are often used. I don't know why you would need a slug field for a content element though.
Maybe you should create an extension instead?

**Comment by wtdesign** [comment]
The same I am looking for. 
For example, the "content_slug" plugin is not compatible with the latest version of mask 7.0.27.
If I didn't need another plugin in the future, that would of course be even better.

**Comment by nhovratov** [comment]
@wtdesign Thanks for pointing out the extension. Will have a look at it.
