### ISSUE TITLE
wrong label in repeating content element before saving

### ISSUE THREAD

**Issue by adhena** [Gernott/mask#445]
I have an element that uses repeating content-elements to create a slider with different sliding elements (image, video etc.)

when i create a new repeated element in the backend it shows the wrong labels for certain fields at first. if i save the repeated element then the correct labels are shown.

the field in question is being used in multiple elements and it looks like it shows the label from a different element. The label is being overwritten in these cases.

label of field "image" before saving:
![image](https://user-images.githubusercontent.com/94121910/141311743-e3ef07f4-8223-40ea-a55d-844a01f59ee0.png)

label of field "image" after saving:
![image](https://user-images.githubusercontent.com/94121910/141311921-d65135ca-2b94-4171-9ccc-1f99019e4a41.png)

before we upgraded to TYPO3 v10 and Mask 7.0 we had the other issue of labels not being overwritten at all. this seems like a different problem though.

**Comment by nhovratov** [comment]
Can confirm. Thanks for the report.

**Comment by nhovratov** [comment]
Fixed on current master. Will be delivered with the next Version 7.1.0.
