### ISSUE TITLE
bug in nested elements

### ISSUE THREAD

**Issue by Finulin** [Gernott/mask#451]
after some of the last typo3 v11 source update, elements with inputType *inputLink* not working in nested elements anymore. the linkwizard are broken. maybe a typo3-bug...

**Comment by can0199** [comment]
do you use typo3 11.5.3? if so then its a core bug which is already fixed on 11.5.4 
[https://forge.typo3.org/issues/96009](url)

**Comment by nhovratov** [comment]
Closing as it's a TYPO3 bug.
