### ISSUE TITLE
Reapeat is calling two ajax requests.

### ISSUE THREAD

**Issue by dustin-webschuppen** [Gernott/mask#453]
When i got a repeat element i have some issues.

When i generate an element with repeat and have an image in that.
The Image has no max than the image got saved 2 times.
When i have a link in it and use the typo link, than opens a modal 2 times, the second modal has no z-index, so you could not wor anymore.

Do i forget something or i just the only one who has that kind of problem?

**Comment by nhovratov** [comment]
First, please provide your used TYPO3 and Mask Version.

So, you have two different issues?
- When you save an image inside a repeat field, it creates 2 file references.
- When you have a link inside a repeat field and you open the link wizard, it opens 2 modals.

Is this correct?

**Comment by dustin-webschuppen** [comment]
Oh Im sorry! 
I don't know how I could forget.

Typo v11.5.3
Mask v7.0.30

And yes, that are my issues.

**Comment by nhovratov** [comment]
Ok, thank you. It is most probably related to recent TYPO3 core changes in v11.
I will try to reproduce it and create new issues on forge, if they are not already reported there.
For the time being this issue can stay here.

Thanks again for reporting the issue!

**Comment by dustin-webschuppen** [comment]
Thank you :D

**Comment by dustin-webschuppen** [comment]
Know i got it.
The issues only is in 11.5.3
In 11.5.2 it is all fine.

**Comment by nhovratov** [comment]
Hey, it is already fixed (both) on current v11 branch. The fix will be released together with the next bugfix release.
See here: https://forge.typo3.org/issues/96009
And here: https://review.typo3.org/c/Packages/TYPO3.CMS/+/72214
