### ISSUE TITLE
Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative()

### ISSUE THREAD

**Issue by nitori** [Gernott/mask#454]
Mask 7.1

Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative() 

Backend Module doesn't load.
Above 500 Error visible in console of Browsers devtools.

Happens on non-composer TYPO3 10 Installations.

Specifically Using typo3 10.4.20 and the shipped doctrine/dbal version 2.10.4

*Update: TYPO3 10.4.21 still has dbal 2.10.4*

I guess fetchAllAssociative was added in 2.11

**Comment by Chriz74** [comment]
same with 10.4.22 non-composer version.
error in Frontend also visible.

**Comment by nitori** [comment]
As an extra Note. TYPO3 10 explicitly states dbal 2.10 as a compatible version (which is not the case for TYPO3 11). So it's probably reasonable to ensure Mask is compatible with those dbal versions as well, as long as mask has TYPO3 10 compatibility.

😺

https://github.com/TYPO3/typo3/blob/v10.4.22/composer.json#L42

**Comment by nhovratov** [comment]
Thanks for reporting the issue!
