### ISSUE TITLE
[BUG] Inherit mask page template fields

### ISSUE THREAD

**Issue by t3premium** [Gernott/mask#466]
Since mask version 7.0.31 the inheritance of new mask page template fields doesn't work right.

**Scenario**
You set a layout in the page field backend_layout_next_level for all subpages.
On the subpages itself, nothing is declared in the backend_layout filed again.

The mask page template is extended with a new tab and fields.
- New tab
- New fields

Since mask version 7.0.31 the new tab doesn't show up on the subpages. In mask version <= 7.0.30 it does.
The TYPO3 version is the same in both test scenarios.

Mask version: > 7.0.30
TYPO3 version: 11.5.5

**Comment by t3premium** [comment]
Problem seems to be in "mask/Classes/ExpressionLanguage/MaskFunctionsProvider.php" function maskBeLayout().
The reverse of code line 53 solves the issue:

`rsort($rootline);`
`//$rootline = array_reverse($rootline);`

**Comment by nhovratov** [comment]
Hi, I can't reproduce your issue. All works like expected:

- Page 1 (backend_layout=`1`, backend_layout_next_level=`2`) => Has tab Content-Fields for backend_layout=`1`
     - Page 2 (backend_layout=`""`, backend_layout_next_level=`""`) => Has tab Content-Fields for backend_layout=`2`
     - Page 3 (backend_layout=`""`, backend_layout_next_level=`""`) => Has tab Content-Fields for backend_layout=`2`

The fix in Mask 7.0.31 was correct, as it should reverse the array (look for backend layouts bottom-to-top).

Can you give me more insights about your structure? Maybe with database values for the pages.
I'm curious why you relied on a buggy behaviour.

**Comment by t3premium** [comment]
Hi,
my database values for the pages are:

- Home (backend_layout='pagets__home', backend_layout_next_level='pagets__default', tx_mask_contactperson='')
-- Page 2 (backend_layout='', backend_layout_next_level='pagets__article', tx_mask_contactperson='')
- -- Page 3 (backend_layout='', backend_layout_next_level='', tx_mask_contactperson=1) => Should have tab with new content fields for backend_layout='pagets__article'

The new field "tx_mask_contactperson" for page layout "pagets__article" is not showing up in the page options.

**Comment by nhovratov** [comment]
Is Page 3 a subpage of Page 2?

**Comment by t3premium** [comment]
Yes

**Comment by nhovratov** [comment]
Ok, will check it. Didn't test with 3 levels of nesting.

**Comment by nhovratov** [comment]
Yep, doesn't work. I get the "backend_layout_next_level" of the home page instead of Page 2.
Let's see what's wrong there..

**Comment by nhovratov** [comment]
Found it. Somehow the rootline argument is sometimes sorted correctly and sometimes in reversed order.
In case it was already reversed, calling array_reverse broke it of course.
A ksort before reversing should do the trick.

**Comment by nhovratov** [comment]
Fixed in 7.1.15
