### ISSUE TITLE
Upgrade Wizard Renaming too many files

### ISSUE THREAD

**Issue by spfeifer** [Gernott/mask#467]
I just started an TYPO3 update from 10.4 to 11.5 and updated the mask extension in that process. When i ran the upgrade wizard of mask, the uppercase-renaming was done on **every** file (yes, every file, recursively) in my document root. I think it would be nice to have a safeguard here if someone forgets to set the "content" settings. 

I think the following line is responsible for that:

https://github.com/Gernott/mask/blob/796d7c0eb27eea5f765b30b364fd7c07c5133181/Classes/Updates/ConvertTemplatesToUppercase.php#L74

$absolutePath = Environment::getPublicPath() . '/' . $settings['content'];

**Comment by nhovratov** [comment]
Oh yes absolutely, sorry for the inconvenience.
