### ISSUE TITLE
Trailing slash for BE Layouts still required

### ISSUE THREAD

**Issue by ursbraem** [Gernott/mask#472]
With TYPO3 11.5.6 and Mask 7.1.19 I experienced no backend template being rendered because of missing trailing slash in the EMConf settings for templates. 

This is consistent with the labels in the EM "(with trailing slash)" but according to https://github.com/Gernott/mask/issues/227 the slash shouldn't be necessary. 

Most robust would be to remove both instructions and necessity for trailing slash

**Comment by nhovratov** [comment]
Thanks, didn't know that with the backend preview. With my patch it doesn't matter anymore, whether there is a trailing slash or not. Will probably release it in the next minor version 7.2.0.

**Comment by ursbraem** [comment]
Super
