### ISSUE TITLE
TSConfig variables in BE preview

### ISSUE THREAD

**Issue by intertain** [Gernott/mask#473]
Hi Gernott and Team,
we developed a cool backend preview which shows the CE like in frontend view. But now we need to set a variable in TSConfig to make difference between multiple page trees. We need this variable in backend preview view. Would you be possible to update the extension to give pageTS variables (e.g. tx_mask.settings.{..}) into the preview? Would be great. We also would pay for that feature. 

Yours,
Michael from intertain

**Comment by nhovratov** [comment]
Hey Michael, it is actually pretty easy what you describe. The data row is already available. You could just make a ViewHelper, which calls `BackendUtility::getPagesTSconfig($row['pid'])` and get the needed information from there. I don't know if it is worth adding it from the Mask side, as it is a rather uncommon usecase.

**Comment by intertain** [comment]
Hi. thanks I got it and could create a Viewhelper that brings the TSConfig variables into the preview view... Thanks...
