### ISSUE TITLE
[FEATURE] Prefilling tables

### ISSUE THREAD

**Issue by ayacoo** [Gernott/mask#479]
With the type Select there is a field "foreign_table". Here you could read the tables from the TCA and output them as a select field instead of a manual input field. This prevents typing errors.

If you can roughly point me in that direction, I'd be happy to prepare a PR as well.

**Comment by nhovratov** [comment]
1. Add new API endpoint to AjaxController and `Configuration/Backend/AjaxRoutes.php`
2. Think of a new field type name and add it to `Resources/Public/JavaScript/Components/FormField.js` with the custom rendering.
3. Change the type in `Configuration/Mask/TcaFields.php` (foreign_table). Currently text.

A bit of VueJS knowledge is necessary, but I think it can be understood in the existing code.
Depending on how fancy you would want to make it, I would suggest creating an own vue js component.

Thanks for suggesting this helpful feature!

**Comment by ayacoo** [comment]
Thanks for the detailed instructions. I will try my luck ;-)
