### ISSUE TITLE
Allow to use videos for File fields

### ISSUE THREAD

**Issue by liayn** [Gernott/mask#481]
Currently one to specify the allowed extensions manually for all fields, that should divert from the system's default `$GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext']` list.

Please add an option to allow to switch this to `$GLOBALS['TYPO3_CONF_VARS']['SYS']['mediafile_ext']`, so those "video-enabled" fields use the same default system values as well.

**Comment by nhovratov** [comment]
Related to: #375

Planning to add a "Media" type, which will use `mediafile_ext` defaults.
