### ISSUE TITLE
Trimming of List for Select-Boxes and missing the use allowNonIdValues

### ISSUE THREAD

**Issue by Padina14** [Gernott/mask#482]
![Bildschirmfoto 2022-03-21 um 15 37 41](https://user-images.githubusercontent.com/63228213/159426222-1bca5ace-e0c0-44e7-b02a-206657aa2cd4.png)

**Comment by Padina14** [comment]
The space before 'tileteaser' will cause an error, if you try to use the selectbox.

Sorry.
I overread the part, that the TCA-attribute 'AllowNonIdValues' is  only useful, if the the attribute 'foreign_table is used.  https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Select/Properties/AllowNonIdValues.html'
I have not tested it. Will the value be set, if you use an foreign_table in the field-definition?

**Comment by nhovratov** [comment]
Hi, yep these should be trimmed by Mask. Will add a patch for this. By now you can simply remove the empty space manually.

As for the TCA option "AllowNonIdValues": Mask does not set it. It's really rare that someone needs this option. If you need it, you can set it in TCA Overrides.
