### ISSUE TITLE
[FEATURE] IconPicker or custom RenderType

### ISSUE THREAD

**Issue by artur-grigoryan-cgn** [Gernott/mask#488]
Hi,
it would be amazing to get an IconPicker so i the user can use icons. 
Otherwise it could help to let me choose cusom RenderTypes so i could user the bw_icon extion.
Thank you. :)

**Comment by nhovratov** [comment]
Hi,
Mask only represents the capabilities of the TCA. If you wish to use an own renderType, then you can just use an input field and override the renderType with TCA overrides.

**Comment by artur-grigoryan-cgn** [comment]
Okay, i will try this!
Is an IconPicker planned?

Danke. :)

**Comment by nhovratov** [comment]
As far as I know not. I think the best alternative right now is a select single with [selectIcons](https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/ColumnsConfig/CommonProperties/FieldWizard/SelectIcons.html#selecticons) enabled.

**Comment by madeinnature** [comment]
> 

Hi Artur,
we use bw_icons in our projects together with mask + mask_export like Nikita described as override or additional element in overrides.

**Comment by artur-grigoryan-cgn** [comment]
Hi madeinnature,
so just: 
`$GLOBALS['TCA']['tt_content']['columns']['tx_mask_icon']['config']['renderType'] = 'iconSelection';` 
in the tt_content.php? Doesn't seem to work.

**Comment by nhovratov** [comment]
Have you added mask as an extension dependency?

**Comment by artur-grigoryan-cgn** [comment]
I added Mask with `composer req mask/mask`

**Comment by nhovratov** [comment]
You need to add this also in your extension, in which you override the TCA

**Comment by artur-grigoryan-cgn** [comment]
i have added mask in composer.json of the project root and the ivs_elements. No effect.

**Comment by nhovratov** [comment]
Have you run composer update after adding it to ivs_elements? If not try that. This will update the extension loading order.

**Comment by artur-grigoryan-cgn** [comment]
yes :)

**Comment by artur-grigoryan-cgn** [comment]
Okay, now it works. I deleted the project and pullt it again. Thank you for the great help!
