### ISSUE TITLE
New Category-Field not localized in frontend

### ISSUE THREAD

**Issue by TheRealMadMesi** [Gernott/mask#489]
I tried the new category field, but it seems to have a problem with translations.
The element, as well as the category ("Sommer" -> "Estate"), was translated to Italian. But in the frontend (on the Italian page) I still get the default language of the category. 

See `title` in screenshot:
![image](https://user-images.githubusercontent.com/103029444/170450879-b8228a9c-00fb-4be1-9eaa-76bbc4f99be7.png)

**Comment by m41r** [comment]
I can confirm this behaviour... maybe we can use something like the following to accomplish this:

```php
$table = 'sys_category'; // or whatever
$item = [ /* the data array */ ];
$langUid = 1; // or whatever
$languageAspect = $this->context->getAspect('language');

$item = $this->getTyposcriptFrontendController()?->sys_page->getRecordOverlay(
    $table,
    $item,
    $langUid,
    $languageAspect->getOverlayType() === $languageAspect::OVERLAYS_MIXED
        ? '1'
        : 'hideNonTranslated'
);

return $item;
```

**Comment by nhovratov** [comment]
Thanks for the issue reporting and a possible solution. I will have a look.
