### ISSUE TITLE
Mask Caching

### ISSUE THREAD

**Issue by s1de21** [Gernott/mask#491]
Hey,

is there a way to disable the caching for one specific module without targeting the others?

Thanks

**Comment by nhovratov** [comment]
Hey.
In general normal content elements are always cached.
There is no switch to deactivate caching for one specific element.
But there are some workarounds by using COA_INT.
Depending on your usecase a plugin is maybe better suited. There you can disable caching for a specific extbase action.

I'm not an expert in caching issues though. You have a better chance by asking in the TYPO3 slack channel #typo3-cms or #random for a more sophisticated answer.
