### ISSUE TITLE
Icons in BE Page layout section missing after update from 7.1.28 to 7.2.3

### ISSUE THREAD

**Issue by medarob** [Gernott/mask#492]
After I updated from mask 7.1.28 to 7.2.3 the icons in the page layout section are missing (on the right side when you open the Mask BE modul)

7.2.3
![grafik](https://user-images.githubusercontent.com/33951787/174233177-e86f6ddb-9a65-475b-8843-827f6a11ed8c.png)

7.1.28
![grafik](https://user-images.githubusercontent.com/33951787/174233224-5146e089-0fd1-49d9-b22b-a3148dd34d7a.png)

I cleared all the caches.

**Comment by nhovratov** [comment]
Did you switch to typo3-composer-installers v4 by any chance?

**Comment by medarob** [comment]
I have not found "typo3-composer-installers".

I have in `vendor/composer/installed.php` the following:
```
'typo3/cms-composer-installers' => array(
            'pretty_version' => 'v3.1.2',
            'version' => '3.1.2.0',
```
and some packages require v1 or v2 or v3 but no package requires v4

for example

```
    "name": "typo3-console/composer-auto-commands",
    "type": "library",
    "description" : "Execute TYPO3 Console commands on 'composer install'",
    "license": "GPL-2.0-or-later",
    "require": {
        "php": "^7.0",
        "helhum/typo3-console": "^5.8.3 || ^6.0",
        "typo3/cms-composer-installers": "^1.4.2 || ^2.0 || ^3.0"
```

**Comment by nhovratov** [comment]
Okay, what do you use for the icon? An identifier or path?

**Comment by medarob** [comment]
This is the PageTs for a BE layout:

```
121 {
    title = 2 Spalten + Hauptinhalt darüber
    icon = EXT:my_ext/Resources/Public/Icons/be_layout_2col+top.gif
    config {
      backend_layout {
```

**Comment by nhovratov** [comment]
Can you debug with devtools which path can't be downloaded in the broken image?

**Comment by nhovratov** [comment]
Thanks, TYPO3 v10 was the missing hint for me. Now it's fixed.
