### ISSUE TITLE
Select field - element item appears twice after saving

### ISSUE THREAD

**Issue by medarob** [Gernott/mask#495]
I have a select field with 5 element items. (2 of them had a group which I added with the new goup functionality. Now I wanted to remove the group again. So, I removed the group and changed the option for both item to "no group" again.) Then I deleted one of the items and now the last item in the list appears twice after I save the content element.

![grafik](https://user-images.githubusercontent.com/33951787/174957993-81adf6e4-06ea-4dae-991c-cf3f83454e20.png)

When I delete the last item "Verbergen" and save the element again, a 5th item appears again with the name "Verbergen" (which is a duplicate of the 4th item).

TYPO3 10.4.30, MASK 7.2.4

**Comment by nhovratov** [comment]
Hey, thanks for the report. Sadly I can't reproduce it. I'm not sure if it's related to groups either.
Can you reproduce it with a new select field? If yes, can you list the exact steps?
Else it might be that your json structure is corrupted. Then it would be interesting how it happened and if it needs manual treatment.

**Comment by medarob** [comment]
Mh, I couldn't reproduce the issue with a new element, or any other element...
Even if I delete 2 or 3 items from the list... if I save the form I'm back to 5 items.
Furthermore, if I delete the item group and save the element, the group is back.

So it's seems like that changes in the BE are not saved for this element... 🤔

**Comment by nhovratov** [comment]
I could have a look, if you send me your json file. Something seems to be off for that element.

**Comment by medarob** [comment]
Thank you. I sent you the mask.json via slack.
