### ISSUE TITLE
issue in non-composer installation

### ISSUE THREAD

**Issue by TBschen** [Gernott/mask#496]
In a non-composer installation (TYPO3 10.4.30) I just did an update from an older mask version (7.0.25) to the current one (7.2.4).
After the update I got the following error:

`PHP Warning: include(/typo3conf/ext/mask/Classes/Domain/Service/SettingsService.php): failed to open stream: No such file or directory in /typo3_src-10.4.30/vendor/composer/ClassLoader.php line 571`

**Comment by nhovratov** [comment]
This class doesn't exist anymore in Mask. Try to regenerate the autoload folder via the Install Tool or simply delete it manually.
