### ISSUE TITLE
PSR-14 Events and Listeners

### ISSUE THREAD

**Issue by AKaravas** [Gernott/mask#497]
Hello, 

in TYPO3 10, the PSR-14 (Events & Listeners) has been introduced. There were enough times where i had to extend the mask extension for special cases. If there were Events implemented, it would have make my life way easier to extend it. 

So what i propose, is to run a poll on Slack or anywhere else you feel comfortable with , asking for cases where mask had to be extended and take the most common ones and try to implement Events for these cases. From there can more and more events be added and make the extension extremely flexible to extend its functionality.

An example would be: `AfterSaveElementEvent()` which will give the opportunity to the develop to perform some action after saving. The same could happen before saving` BeforeSaveElementEvent()`

Best regards

**Comment by nhovratov** [comment]
Hey, thanks for the feature request. I had this already on my list. The save event if needed of course, but I also have some others on my mind like changing default values.

I don't know if a poll is useful, as there are only a few active members in the Mask community, but I can try.
