### ISSUE TITLE
info-icon about the multiple usage of fields is inconsistent?

### ISSUE THREAD

**Issue by medarob** [Gernott/mask#498]
Hi,

I found the following in my mask.json:

The core field `header_layout` was placed inside a palette and the small Info-Icon was automatically added to show that the field is used in multiple other elements and changes in this element will lead to changes in the other elements as well.

![grafik](https://user-images.githubusercontent.com/33951787/176222846-f946dc6a-c5bb-41ce-98e8-f295ac4afb1b.png)

This seems to be correct, because the field is used in multiple other elements.

However, in those other elements, the Info-Icon is missing.

![grafik](https://user-images.githubusercontent.com/33951787/176223859-7782db2e-32bd-453b-b44c-8e1a00360e35.png)

Shouldn't the icon be added to every core `header_layout` field, once the field is used multiple times (even you can't really change anything in MASK) or is the Info-Icon in the core field inside the palette wrong?

You notice the same for the `header` field and it looks like that the Icon will be added to fields inside palettes but not to the same field outside of palettes?

**Comment by nhovratov** [comment]
It shouldn't be added for core fields at all. The bug is, that it is shown for core fields in palettes it seems.
