### ISSUE TITLE
Core v11 with "typo3/cms-composer-installers" v4: 500 error with preview images

### ISSUE THREAD

**Issue by liayn** [Gernott/mask#501]
Mask tries to load some `...preview/<CE-name>.png` which does not exist and causes Mask not to load at all.

I didn't investigate deeply yet, but it might also be a Core issue that's triggered here.

**Comment by liayn** [comment]
`\MASK\Mask\Imaging\PreviewIconResolver::getPreviewIconPath` is the one.
With `ResourceDoesNotExistException`:
`Tried to access a private resource file "EXT:sitesetup/Resources/Private/Extensions/mask/Previews/test.png" from fallback compatibility storage. This storage only handles public files.`

**Comment by nhovratov** [comment]
You can't use the `Private` path for public assets. You have to use `Public`.

**Comment by nhovratov** [comment]
Ok, I will have a look thanks.
