### ISSUE TITLE
Foreign table field for selectbox does not contain other mask tables

### ISSUE THREAD

**Issue by GuidoJansenPI** [Gernott/mask#504]
If I create a Mask element with multiple repeats, for every repeat there is a new DB table created.

If I create a selectbox field, those DB tables are not listed in the fields foreign table setting.
I can edit the JSON file and insert the new DB table in there and it works as intended

What I expect:
The mask tables should be listed in the foreign table field  for the selectbox

**Comment by nhovratov** [comment]
Hi @GuidoJansenPI,

yes, I disabled all hidden tables, like the generated Mask tables.
This prevents, that too many, probably non-relevant, tables are displayed.
You can enable them separately by overriding the TCA:

`$GLOBALS['TCA']['tx_mask_your_table']['ctrl']['hideTable'] = false;`

**Comment by GuidoJansenPI** [comment]
Thanks.
This ticket can be closed
