### ISSUE TITLE
Repeatingproblem - Nested Children colPos Invalid Value 999

### ISSUE THREAD

**Issue by ms-wa** [Gernott/mask#505]
Hello, 
i am using TYPO3 11.5.12 with PHP 8.0, when i want to use nested child-Elments with mask it shows the content correct in the front-end. But the backend shows "invalud value 999".
What cat i do? 

![Bildschirmfoto 2022-08-09 um 17 19 49](https://user-images.githubusercontent.com/100279082/183689601-9b5a2a25-af6d-4e91-818c-d79db4fb8df8.png)

**Comment by nhovratov** [comment]
This is strange. Mask adds allows the 999 colPos through a itemsProcFunc:
`$GLOBALS['TCA']['tt_content']['columns']['colPos']['config']['itemsProcFunc'] = 'MASK\Mask\ItemsProcFuncs\ColPosList->itemsProcFunc';`

Can you check in your TCA, if it's maybe overriden by another extension?

**Comment by ms-wa** [comment]
Youre right, 
the container-Extension overrides it: 

Does have the MASK-Extension problems with b13/container extension?
We used it in the past and we had not a problem. 
I am using container extension v1.6.1

![Bildschirmfoto 2022-08-09 um 17 37 59](https://user-images.githubusercontent.com/100279082/183696255-d08c08de-0c37-4bfd-9c54-0d986f1a4498.png)

**Comment by nhovratov** [comment]
Now I remember there was the same issue a while ago: https://github.com/Gernott/mask/issues/449
I though it was fixed, by adding container to the suggests list, so Mask will be called later.
The problem really is, that itemProcFunc can only have one user function.
I will investigate further on how this can be solved.
Thanks!

**Comment by nhovratov** [comment]
Are you using legacy or composer mode? Can you check the loading order of your extensions? Mask should be installed after container.

**Comment by ms-wa** [comment]
I am using TYPO3 in composer mode.  
Is the order of extension loading in my composer.json file?

"require": {
		"b13/container": "1.4.2",
		"friendsoftypo3/tt-address": "^6.1",
		"helhum/typo3-console": "^7.1",
		"itx/jobapplications": "^2.0",
		"mask/mask": "^7.2",
		"typo3/cms-backend": "^11.5.0",
		"typo3/cms-belog": "^11.5.0",
		"typo3/cms-beuser": "^11.5.0",
		"typo3/cms-core": "^11.5.0",
		"typo3/cms-dashboard": "^11.5.0",
		"typo3/cms-extbase": "^11.5.0",
		"typo3/cms-extensionmanager": "^11.5.0",
		"typo3/cms-felogin": "^11.5.0",
		"typo3/cms-filelist": "^11.5.0",
		"typo3/cms-fluid": "^11.5.0",
		"typo3/cms-fluid-styled-content": "^11.5.0",
		"typo3/cms-form": "^11.5.0",
		"typo3/cms-frontend": "^11.5.0",
		"typo3/cms-impexp": "^11.5.0",
		"typo3/cms-info": "^11.5.0",
		"typo3/cms-install": "^11.5.0",
		"typo3/cms-lowlevel": "^11.5",
		"typo3/cms-recordlist": "^11.5.0",
		"typo3/cms-rte-ckeditor": "^11.5.0",
		"typo3/cms-seo": "^11.5.0",
		"typo3/cms-setup": "^11.5.0",
		"typo3/cms-sys-note": "^11.5.0",
		"typo3/cms-t3editor": "^11.5.0",
		"typo3/cms-tstemplate": "^11.5.0",
		"typo3/cms-viewpage": "^11.5.0"
	},

**Comment by nhovratov** [comment]
No, the order is defined in vendor/typo3/PackageArtifact.php

It looks like this for me:

```
  array (
    'b13/container' => 'container',
    'mask/sitepackage' => 'sitepackage',
    'typo3/cms-backend' => 'backend',
    'typo3/cms-belog' => 'belog',
    'typo3/cms-beuser' => 'beuser',
    'typo3/cms-core' => 'core',
    'typo3/cms-extbase' => 'extbase',
    'typo3/cms-extensionmanager' => 'extensionmanager',
    'typo3/cms-felogin' => 'felogin',
    'typo3/cms-filelist' => 'filelist',
    'typo3/cms-fluid' => 'fluid',
    'typo3/cms-form' => 'form',
    'typo3/cms-frontend' => 'frontend',
    'typo3/cms-info' => 'info',
    'typo3/cms-install' => 'install',
    'typo3/cms-lowlevel' => 'lowlevel',
    'typo3/cms-recordlist' => 'recordlist',
    'typo3/cms-reports' => 'reports',
    'typo3/cms-rte-ckeditor' => 'rte_ckeditor',
    'typo3/cms-seo' => 'seo',
    'typo3/cms-setup' => 'setup',
    'typo3/cms-t3editor' => 't3editor',
    'typo3/cms-tstemplate' => 'tstemplate',
    'typo3/cms-workspaces' => 'workspaces',
    'mask/mask' => 'mask',
    'typo3/cms-fluid-styled-content' => 'fluid_styled_content',
  ),
```

**Comment by nhovratov** [comment]
I think it might be because of the missing suggest entry in the composer.json file. I will add a new release. Please try it out if it works for you.

**Comment by nhovratov** [comment]
You may also try to remove and install mask again to regenerate the package states

**Comment by ms-wa** [comment]
I reinstalled mask with Version 7.2.8. It works! 
Thank you @nhovratov.
