### ISSUE TITLE
All Content Elements into "Allowed contend elements"

### ISSUE THREAD

**Issue by artur-grigoryan-cgn** [Gernott/mask#506]
Hello,
is it possible to tell Mask that i want to have all content elements choosable inside a "content element"-field? If i choose all of them and create a new content element i have to update all the old ones.

![ksnip_20220811-103359](https://user-images.githubusercontent.com/16120407/184322452-e87231b8-a169-4f34-81a7-1abc129abbfd.png)

Regards 
Artur

**Comment by nhovratov** [comment]
Yes, just leave the left side empty. You just can't control the order this way.

**Comment by artur-grigoryan-cgn** [comment]
Hi, tried it but then the user can't use any CTypes:
![Screenshot_from_2022-08-12_11-10-26](https://user-images.githubusercontent.com/16120407/184324633-d8135d18-534c-4cc0-8ea5-54746e1e9860.png)

Mask v7.2.6

**Comment by nhovratov** [comment]
Hm, ok. Maybe I remember it wrong. I'll have a look.

**Comment by nhovratov** [comment]
I believe this is a bug.

**Comment by nhovratov** [comment]
Will release a new version right now.

**Comment by artur-grigoryan-cgn** [comment]
Wow! That was fast. Thank you!
