### ISSUE TITLE
[BUG] Attempt to read property "cTypes" on null

### ISSUE THREAD

**Issue by bh-teufels** [Gernott/mask#507]
With mask 7.2.9 following error appears on BE:

`An error occurred trying to process items for field "Type" (PHP Warning: Attempt to read property "cTypes" on null in /app/web/typo3conf/ext/mask/Classes/ItemsProcFuncs/CTypeList.php line 76).`

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: array_flip(): Argument #1 ($array) must be of type array, null given | TypeError thrown in file /typo3conf/ext/mask/Classes/ItemsProcFuncs/CTypeList.php in line 79.`

Typo3: 11.5.14
PHP: 8.1.2
mask: 7.2.9

with mask 7.2.8 the errors does not appear

**Comment by nhovratov** [comment]
Ah, yes I was afraid this might happen. Will release a fix asap.
