### ISSUE TITLE
Cant unfold "Repeating" when containing "Content Element"

### ISSUE THREAD

**Issue by artur-grigoryan-cgn** [Gernott/mask#509]
Hi, when i put a "Content Element" inside a "Repeating Element" i get an error when i try to unfold it.
![ksnip_20220818-174233](https://user-images.githubusercontent.com/16120407/185437902-2c1a77b1-8e51-476c-bcbd-f90a338e6b2e.png)
->
![ksnip_20220818-174536](https://user-images.githubusercontent.com/16120407/185438004-896fda7d-459a-4f6f-bcb7-69e2a87eab88.png)
 
As i remember it woked some versions before.

**Comment by nhovratov** [comment]
Hey, doing a quick test on a clean installation, no error is thrown. As I see this is TYPO3 v11, right? Can you have a look at the error logs, what the actual error is?

**Comment by artur-grigoryan-cgn** [comment]
Sure: 
Core: Exception handler (WEB): Uncaught TYPO3 Exception: array_flip() expects parameter 1 to be array, null given | TypeError thrown in file .../public/typo3conf/ext/mask/Classes/ItemsProcFuncs/CTypeList.php in line 79. Requested URL: http://typo3muster-fluid.local/typo3/ajax/record/inline/details?token=--AnonymizedToken--

**Comment by nhovratov** [comment]
There is a newer version of Mask v7.2.10. Can you try it out?

**Comment by artur-grigoryan-cgn** [comment]
While you where answering i mentioned the new version and tried it. It works now. Thanks!
Can i ask another question? 

I got the Error: "Error: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs" 

because i had too much mask fields. Is there anything what i can do to expand the row-size? I removed a some fields but i'm afraid to get it agai on day. :)

**Comment by nhovratov** [comment]
Nice!
Uh, that nasty error.. I can only recommend reading the troubleshooting guide here: https://docs.typo3.org/p/mask/mask/main/en-us/Troubleshooting/Index.html#on-save-error-row-size-too-large-mariadb
