### ISSUE TITLE
Non-reusable IRRE elements

### ISSUE THREAD

**Issue by moxface** [Gernott/mask#510]
Hello, 

I cannot reuse the content (IRRE) element. In the content elements I created earlier (mask < v7), I always used the same IRRE element (key field). But now it seems that this is no longer possible. Also the newly created IRRE element cannot be reused. Is this intentional or a bug?

Greetings Simon

**Comment by moxface** [comment]
OK I could help myself. I created a new IRRE element and adjusted it in mask.json by hand.... Not pretty, but seems to work. :-)

**Comment by nhovratov** [comment]
IRRE fields can't be shared by intention. If you adjust the mask.json file manually you are on your own, so do with care.
