### ISSUE TITLE
RTE fields can no be set as "required" in mask UI

### ISSUE THREAD

**Issue by m41r** [Gernott/mask#512]
If you add a RTE field to your content element and you want to set it as "required", you will see that there is no Tab "Validation" and so no checkbox to mark.

Do I miss something or is this not possible with RTE fields?

**Comment by nhovratov** [comment]
No, RTE fields can't be set as `required`. Only normal `text` fields.

**Comment by m41r** [comment]
ok, thanks for the clarification
