### ISSUE TITLE
Mask 6.7.5 Mask\Domain\Model\BackendLayout

### ISSUE THREAD

**Issue by frankblank** [Gernott/mask#516]
The Var $uid ist marked as int but initialized with empty string '' in Line 36 to 40

    /**
     * @var int
     * @TYPO3\CMS\Extbase\Annotation\Validate("NotEmpty")
     */
    protected $uid = '';

throws error Fatal error: Type of MASK\Mask\Domain\Model\BackendLayout::$uid must be int (as in class TYPO3\CMS\Extbase\DomainObject\AbstractDomainObject) in /var/www/html/web/typo3conf/ext/mask/Classes/Domain/Model/BackendLayout.php on line 0

**Comment by nhovratov** [comment]
Hi, Mask v6 is no longer supported. I would recommend you to update to Mask v7.
