### ISSUE TITLE
JSON-Split will create issue if you try to create repeating Element 

### ISSUE THREAD

**Issue by powermix** [Gernott/mask#517]
If you apply json-split in settings it will lead to an error upon creating Repeating Element (Only) content type .

Error : "The Table tx_mask_..... does not exist."

to solve that had to change  json-split to json

**Comment by nitori** [comment]
I got that too today, but only if the repetition is empty (no fields). Did you add a field into the repetition?

**Comment by powermix** [comment]
oh! i didn't try that so you might be correct if the repetition is empty .
