### ISSUE TITLE
Make module access configurable

### ISSUE THREAD

**Issue by sebastiande** [Gernott/mask#521]
Hi,

first, thank you for this awesome module!
I just wondered why the module in the backend is set to available for admins only. Is there a reason for this? At least for us, we have to give permission to some groups but do not want to give the whole admin rights to these groups.

```
'routeTarget' => \MASK\Mask\Controller\MaskController::class . '::mainAction',
        'access' => 'admin',
```

(https://github.com/Gernott/mask/blob/822802b12504cf3e24fd3ae909f5fb4127ea06d6/ext_tables.php)

Is this something that could be extended to also groups and maybe even users?

```
'routeTarget' => \MASK\Mask\Controller\MaskController::class . '::mainAction',
        'access' => 'admin,group,user',
```

Thank you!
Sebastian

**Comment by sebastiande** [comment]
I just tested it locally and sadly it is only possible to transform fully to 'group,user' as long as admin is part of the configuration it is not possible to configure the group access.

**Comment by nhovratov** [comment]
May I ask you why you would want to give users access to the Mask module (this is the first time I heard that)?

**Comment by sebastiande** [comment]
@nhovratov thanks for the fast reply! Actually, we are having a very large Typo3 for some special use cases to just maintain content (not a website at all) which is used by like 50 people from different companies. Some developers are allowed to create new content elements (but shouldn't be admins) and some content managers that are just using it - and we as providers of this system are also creating new content elements, managing content but also maintaining the systems - so we are the admins.

I guess this is not the standard way of using this extension and others may not have the problem allowing the user to different user groups on the other side using "group" as access makes it much more flexible as you still could only allow it for admins but also allow it for single user groups. Maybe it could just be an extension configuration to stick with the admin standard and if configured in the extension settings allow it also for groups instead of only admins?

**Comment by sebastiande** [comment]
Thank you @nhovratov !
Just one question, is there a reason to change the Backend Module only to user instead of group & user?

**Comment by nhovratov** [comment]
What you've seen is for TYPO3 v12. There has been a change that user includes both group and user. In v11 / v10 changed it to group,user.

**Comment by sebastiande** [comment]
Ok wasn't aware of that, thank you very much!
