### ISSUE TITLE
Mask Field "palettes" not working (no output)

### ISSUE THREAD

**Issue by verdure-leventic** [Gernott/mask#522]
Hello everyone, 

after using the Field "palettes" and putting my Items into 3 different "palettes" Fields, they don't show up inside the Content Element, after I looked inside the Code, the "showItem" was set wrong. My written Label isn't inside the code, I tried even with an LLL String with the thinking maybe works for now, but still LLL String isn't working. 

Am I doing something wrong? I used the Field, put my Label and included my Fields inside the Palette Field, saved, exported, done. 
Even if I write some Label directly in the Exported Code, my Fields aren't showing up, I couldn't find the palette definition with my Fields for each palette. 

![Bildschirmfoto 2022-10-04 um 16 00 22](https://user-images.githubusercontent.com/77504351/193839780-2f9b9f13-cb4b-49c8-84b8-429c77dd2256.png)

**Comment by nhovratov** [comment]
Hey, so you are using [mask_export](https://github.com/IchHabRecht/mask_export), right? This is another extension, not maintained by me. Please open an issue there. Besides, I think palettes are not supported there.
