### ISSUE TITLE
Support for Typo3 V12

### ISSUE THREAD

**Issue by ByteBandito** [Gernott/mask#525]
Thank you for this awesome plugin - it really makes typo3 easy expandable.

We would wish a small update for using mask with the new Typo3 Version 12 :-). I guess no big changes are nessesary.

Thank you!

**Comment by nhovratov** [comment]
Hey, you can use the current main branch for TYPO3 v12. Basic functionality should work already.

**Comment by nhovratov** [comment]
Update: Will release version 8.0 next week. It's only a compatibility version. Still many TCA deprecation warnings and no new features, but works :)
