### ISSUE TITLE
No backend preview after update to v8

### ISSUE THREAD

**Issue by sniepy** [Gernott/mask#527]
Hi,

as mentioned in the title I got a problem with my backend previews.
Since updating to mask v8 it appears that the backend templates are not loaded anymore.
The paths in my local configuration are still correct and the templates do exist.

Do you have any suggestions?

Best regards,
Sebastian

**Comment by nhovratov** [comment]
Which TYPO3 version are you on? v11 or v12?

**Comment by sniepy** [comment]
It's v11

**Comment by nhovratov** [comment]
Okay thanks, I will check it.

**Comment by sniepy** [comment]
Thank you!

**Comment by nhovratov** [comment]
Thanks for reporting the issue! Fixed and released a new version.

**Comment by sniepy** [comment]
Great! Thanks for your incredible work!

**Comment by PaDa19** [comment]
Hi,

I have the same problem but I am using TYPO3 12.3.0 and Mask 8.0.8. 
The function preProcess in Classes/Hooks/PageLayoutViewDrawItem never gets called.
The frontend works without a problem and I double and tripple checked the paths.

Any idea what might be the problem?

Regards,
Patrick.

**Comment by nhovratov** [comment]
Hi @PaDa19 The class `PageLayoutViewDrawItem` is not used in v12, this is the old hook for v11.  Have a look at https://github.com/Gernott/mask/blob/main/Classes/EventListeners/MaskBackendPreviewEventListener.php please.
