### ISSUE TITLE
Palette for Page Templates

### ISSUE THREAD

**Issue by plojewski** [Gernott/mask#528]
Hi there, I use Mask v7.2.13 and Typo3 v10.4.32. When I try to use Palette (with fields inside it) for Page Templates, after Save I've got an error:

`The TCA for the field "tx_mask_settings_breadcrumb_off" must not be empty.`

Could you please check it out?

**Comment by nhovratov** [comment]
Where do you use this field? `tx_mask_settings_breadcrumb_off`
Does it only happen, if you use palettes?

**Comment by plojewski** [comment]
> Does it only happen, if you use palettes?
Yes.

I define like this:
![Zrzut ekranu 2022-11-21 o 15 57 16](https://user-images.githubusercontent.com/7590893/203089735-37591d67-73ea-4b85-b533-639c51d240e8.png)

**Comment by nhovratov** [comment]
Ok, and there is nothing special about this field? No TCA overrides or some kind of stuff?

**Comment by nhovratov** [comment]
Thanks, verified and fixed.

**Comment by plojewski** [comment]
@nhovratov One more thing :( After update to v7.2.14 I've got an error now:

`The field "header" does not have a defined field type.`

**Comment by nhovratov** [comment]
Ah, ok. I feared this could happen. In my tests core fields worked. Will release a fix asap.

**Comment by nhovratov** [comment]
I will release 7.2.15 shortly, could you test it right away?

**Comment by plojewski** [comment]
ok

**Comment by plojewski** [comment]
@nhovratov Thanks again. It works fine in 7.2.15.

**Comment by nhovratov** [comment]
Thanks for testing!
