### ISSUE TITLE
Make $allowedFields configurable to extend Core fields list

### ISSUE THREAD

**Issue by twaurisch** [Gernott/mask#534]
To make some fields in the _tt_content_ table reusable, it would be nice if the variable $allowedFields could be extended. It is used in the class AjaxController in the method existingTca().

If nothing speaks against from your side two scenarios are possible for me:

1. Place the list of fields to a place where it is configurable
2. Integrate a hook to extend $allowedFields

For example, an own field background_color, should be used in a mask component. The field exists once in the DB but should be used in different contexts in different Mask components.

**Comment by nhovratov** [comment]
Hey, yes this feature is already on the roadmap. Merge requests are welcome.

**Comment by PeaceSfiSh** [comment]
Do you prefer to integrate a new 'optgroup' like 'Custom fields' or simply extending  'Core fields'.
Using 'Core fields' will be way easier to implement.

**Comment by nhovratov** [comment]
I'd like an Event to manipulate the array. Core fields can be reused of course. Maybe relabeled as "Existing fields" or something.
