### ISSUE TITLE
cropVariants in repeatable Fields

### ISSUE THREAD

**Issue by supercat1510** [Gernott/mask#535]
I try to use cropVariants in repeatable Fields - how describe in this Link: https://docs.typo3.org/p/mask/mask/main/en-us/Guides/CropVariants.html
But it just doesn't work.
In the TCA configuration, the entry "crop" simply does not appear.
If I save the structure directly in the mask.json, then it works - but the setting is gone as soon as the file is regenerated by saving.

I think the most sensible solution would be if you could select in the "Mask" at File whether you want to use the standard crop, or alternatively you can specify the required variants directly.

**Comment by supercat1510** [comment]
I add the depends and delete all caches - but nothing change

**Comment by nhovratov** [comment]
Are you in composer mode? If yes, you need to reinstall Mask so the loading order is renewed.

**Comment by nhovratov** [comment]
I'll close this as no feedback since 3 weeks. If you have still issues, you can also ask on slack.
