### ISSUE TITLE
forcing namespace for naming the fields

### ISSUE THREAD

**Issue by kszymukowicz** [Gernott/mask#536]
hi

I was just thinking if it would be a nice option to have a global switch that would force naming of fields.

Example. 

If I choose name of CE to Teaser 01 and want to add field "text" then usually it comes to `tx_mask_text`.

With X content elements each having text field we will end up with `tx_mask_text`, `tx_mask_text2`, `tx_mask_textbottom`, `tx_mask_textmy`, .....

So maybe it would be good to force naming to:
tx_mask_[name_of_ce]_[here_user_can_put_his_name]

So final naming would be:
`tx_mask_teaser_01_text`, `tx_mask_teaser_02_text`, `tx_mask_slider_text`

btw: I do not use "reuse" of fields.

**Comment by nhovratov** [comment]
Hey Krystian, thanks for your suggestion! This is indeed a problem, as every `text` field would need other options for every content element. Right now this is only possible with `label` and `description`. This is probably the main reason you want that namespace.
I'm working right now in the content blocks team for creating a system extension `content_blocks` which reuses a lot of concepts I introduced in Mask. There you have exactly what you are proposing: every content block has a namespace (vendor/package), which is prefixed for every field. I'm not sure, if it's worth to put that much effort into Mask to introduce this feature. That would need a lot of time and effort.

**Comment by kszymukowicz** [comment]
@nhovratov 
Sure not worth effort if this will be in `content_blocks`. 
Tnx for fast answer!
