### ISSUE TITLE
TYPO3 11.5.22 PHP8.1 Mask RTE Problem

### ISSUE THREAD

**Issue by ms-wa** [Gernott/mask#538]
Hello,
I get if I want to assign an RTE to a self-built element the following error:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Undefined array key "label" in ...

**Comment by nhovratov** [comment]
Hey, can you show me the full error? After "in ..." is the important part.

**Comment by ms-wa** [comment]
Oh excuse me, 

html/typo3-composer/public/typo3conf/ext/mask/Classes/Controller/AjaxController.php line 667 | TYPO3\CMS\Core\Error\Exception thrown in file /html/typo3-composer/public/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 137. Requested URL: https://testdomain.test/typo3/ajax/mask/existingTca?token=--AnonymizedToken--&table=tt_content&type=richtext

**Comment by nhovratov** [comment]
Ok interesting, this can only happen, if your core `bodytext` field has no TCA label. Do you have any TCA overrides that remove it?
The default is:
```
        'bodytext' => [
            'l10n_mode' => 'prefixLangTitle',
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.text',
            'config' => [
```

**Comment by ms-wa** [comment]
Thanks for your feedback,
It wasn't actually the mask extension. (y)

**Comment by nhovratov** [comment]
Ah, thanks. Do you want to explain what happend, so others are aware? Or was this a special case, which won't happen to anyone else?

**Comment by ms-wa** [comment]
That was the snippet: 

'header' => [
    'config' => [
        'type' => 'text',
        'cols' => 40,
        'rows' => 3,
        'enableRichtext' => true,
    ],
],

it was locates in my tt_content.php to overwrite content-elements.

I add the label-configuration like this: 

'header' => [
    'label' => 'Header',
    'config' => [
        'type' => 'text',
        'cols' => 40,
        'rows' => 3,
        'enableRichtext' => true,
    ],
],
