### ISSUE TITLE
Fields in Backend-Layouts not stored/visible in Mask module

### ISSUE THREAD

**Issue by viu-x** [Gernott/mask#539]
Hi,

TYPO3 11.5.24 (composer mode)
Mask 8.0.7

I installed the extension according to the documentation. I set the `general.backendlayout_pids` to `1` in the extension configuration. Otherwise no backend layouts are found if it is the default `0` which should find all. And using `json-split` as storage option.

I go to the Mask module and select the page layout, add a field, hit save. I get a green success message but the field disappears. Reopening the form does not bring the field back. But the field in the database is created, as is the JSON file with the configuration.

This problem does not appear if I'm using `json` mode instead of `json-split`.

https://user-images.githubusercontent.com/103430706/225951615-1ddf93e9-8d9c-4493-9032-d8e905f47ca1.mov

Best regards
Tobi

**Comment by nhovratov** [comment]
Hi Tobi, did you define the `backend_layouts_folder` in the extension configuration?

**Comment by viu-x** [comment]
Yes I did. And as mentioned earlier the JSON files have been created correctly. They even got updated after I tried adding a simpler field (like in the video).

I used the convert command to convert them to the non-split version and with that it works.

**Comment by nhovratov** [comment]
Okay, so when you save, you have a `default.json` file correct? This means Mask can store, but no read the files. I have no idea what could be the issue. Do you store them inside your local extension? Maybe some permission issue?

**Comment by nhovratov** [comment]
Is there any error in the JavaScript console, when you open the edit view?

**Comment by viu-x** [comment]
I store them in my local extension. And permissions cannot be the issue. The folders are created through your wizard and the problem exists (or now existed) only for the backend layouts. Content elements worked properly.

But now comes the strange part. After switching back to `json-split` to look for console errors, the module displayed the field I created earlier which didn't show up again. And even after deleting the `default.json` and starting from scratch it works.

Now I'm a little lost 🤷🏼‍♂️ Not the kind of errors a developer likes which suddenly disappear...

**Comment by nhovratov** [comment]
Wow, really strange. I've never encountered this error before and you are the first one to describe such a weird behaviour. Maybe you changed something else in the meantime, which you thought was unrelated. Nevertheless, if you encounter it again, alert me. I'm curious what caused this.

**Comment by stigfaerch** [comment]
I also experience this problem.
Also when I switch from json-split to json it works with the single file.
Unfortunately moving back to json-split didn't solve it for me.

**Comment by stigfaerch** [comment]
@nhovratov 
Ok, I think I found the reason why.
\MASK\Mask\Loader\JsonSplitLoader::load:
```php
        // Early return, if the content elements folder does not exist.
        $contentElementsFolder = $this->validateFolderPath('tt_content');
        if (!file_exists($contentElementsFolder)) {
            return clone $this->tableDefinitionCollection;
        }
```
As the ContentElements folder wasn't created at this point, the rest of the configuration isn't loaded as well.
