### ISSUE TITLE
Add path to backend XLF to settings

### ISSUE THREAD

**Issue by cepheiVV** [Gernott/mask#541]
Add the path to the Backend XLF files to the extension settings, so we can easily change labels:

<img width="1006" alt="Screenshot 2023-03-27 at 11 17 36" src="https://user-images.githubusercontent.com/2963482/227839888-6b4289c8-dda5-44a6-b2a2-806f3485be79.png">

Path to original;
`EXT:mask/Resources/Private/Language/locallang_mask.xlf`

Path to override file:
`EXT:sitepackage/Resources/Private/Language/locallang_mask.xlf`

**Comment by nhovratov** [comment]
Hey, in TYPO3 you can always override other xml files: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Localization/ManagingTranslations.html#custom-translations

```
$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['EXT:mask/Resources/Private/Language/locallang_mask.xlf'][]
    = 'EXT:sitepackage/Resources/Private/Language/locallang_mask.xlf';
```

**Comment by cepheiVV** [comment]
I am aware of this. It's also possible to change certain labels using TsConfig.
My suggestion here is to have an easy way to change this in the ext.mask GUI/settings, so an integrated doesn't have to touch the codebase.

**Comment by nhovratov** [comment]
Which labels do you want to change in particular? The method mentioned above is the easiest one I can think of. I could add it to the documentation, also how to use TSConfig to override labels.

**Comment by cepheiVV** [comment]
I wanted to change the `new_content_element_tab` label.

I solved my usecase with TsConfig
```
mod.wizards.newContentElement.wizardItems.mask.header = Custom label
```

**Comment by cepheiVV** [comment]
Just a suggestion, if you feel like this isn't useful in your extension, feel free to close the issue

**Comment by nhovratov** [comment]
The custom tab header is probably the most common question. Will add it definitely to the documentation. I will think about adding an extra setting for it.
