### ISSUE TITLE
TCA Generator generating "indexed array keys" which is deprecated TCA

### ISSUE THREAD

**Issue by grempa** [Gernott/mask#543]
System: Mask 8.0.8 // CMS-Core 12.03

# Problem: 

Since "Using indexed array keys" is deprecated (See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Deprecation-99739-IndexedArrayKeysForTCAItems.html) the generated mask Elements produce a lot of deprecation warnings and entries in "Migrate TCA"-Module inside the Backend. 

# Expectation / Solution

- Generator generates clean TCA for 'items'.
- OR (for compability): have just some migration wizzard / "how to migrate info" in readme, at least

Would be great to have one of these (or both :) )

**Comment by nhovratov** [comment]
Hey, thank you for early testing with TYPO3 v12! I already wrote the migration: https://github.com/Gernott/mask/commit/f9b2a897557cfbbd48e99103507cf429e2d8b29c

This will be released together with Mask 8.1 shortly after TYPO3 v12 LTS release.

**Comment by grempa** [comment]
Oh, nice! 👍 

Thanks for your work!
