### ISSUE TITLE
Mask module not rendering

### ISSUE THREAD

**Issue by tonytony60** [Gernott/mask#545]
I ma using typo3 version 12.3.0 and mask 8.0.8.
In backend mask module is not showing. see below attachment

![Screenshot - 2023-04-18T093828 596](https://user-images.githubusercontent.com/42315926/232669243-c97cc7c1-3161-4b16-adb3-fd8da9caa6b3.png)

I see error in console.

`Content Security Policy of your site blocks the use of 'eval' in JavaScript`

can you please help me? where i can wrong?

@nhovratov

**Comment by liayn** [comment]
That's not your fault. New feature in 12.3

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Feature-99499-IntroduceContent-Security-PolicyHandling.html

That needs a fix in mask.

**Comment by tonytony60** [comment]
@liayn thanks for hint. can i disable security.backend.enforce Content Security Policy temporary. Hope it's not effect other typo3 12.3 functionality.

**Comment by nhovratov** [comment]
Yes, CSP is blocking things like `new Function('return this')`, which is used in VueJs, which I can't control. So there is no other way besides to disable `security.backend.enforceContentSecurityPolicy`.

**Comment by liayn** [comment]
Can't we ship a custom CSP rule (yaml or php) to adjust the headers accordingly?

**Comment by nhovratov** [comment]
@liayn I'm not familiar with this. If you have an idea on how to fix this, could you provide a PR?

**Comment by liayn** [comment]
Did not try it yet, but I have
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Feature-99499-IntroduceContent-Security-PolicyHandling.html#extension-specific
in mind

**Comment by nhovratov** [comment]
> Did not try it yet, but I have https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Feature-99499-IntroduceContent-Security-PolicyHandling.html#extension-specific in mind

Thanks, I could solve it after learning a bit about CSP. Well, it is solved by allowing unsafe eval executions in the backend. To mitigate it, I would need to convert all remaining Fluid templates to native VueJs Templates. This is out of scope for now.
