### ISSUE TITLE
Error after saving new element without icon

### ISSUE THREAD

**Issue by Kathara** [Gernott/mask#550]
TYPO3 v12.4.1
Mask 8.1.1

When saving a new element when reloading the mask module or creating that element it results in the following error:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Cannot access property starting with "\0" | Error thrown in file [...]/vendor/mask/mask/Classes/Imaging/IconProvider/ContentElementIconProvider.php in line 31.

In my opinion either the field has to be required before saving a mask element or there has to be a check if the icon exists.

**Comment by Kathara** [comment]
Interesting, because I can recreate it with the following steps:

- creating a new mask element in mask module (called it test)
- adding an input field, set field key and label (do nothing else)
- save (no error yet)
- load mask module from module list -> it will not finish loading having the error in the sys_log (see log module)

If I change the following (MASK\Mask\CodeGenerator\TyposcriptCodeGenerator   from line 68):
```
$this->iconRegistry->registerIcon(
    $iconIdentifier,
    ContentElementIconProvider::class,
    [
        'key' => $element->key,
        'label' => $element->label,
        'icon' => $element->icon,
        'color' => $element->color,
    ]
);
```

to: 

```
if ($element->icon) {
    $this->iconRegistry->registerIcon(
        $iconIdentifier,
        ContentElementIconProvider::class,
        [
            'key' => $element->key,
            'label' => $element->label,
            'icon' => $element->icon,
            'color' => $element->color,
        ]
    );
}
```

It loads again. After adding an icon to the element in the settings it works well too. But to save the icon I have to eliminate the if-statement again otherwise it's not saved.

**Comment by nhovratov** [comment]
Nope. PHP 8.2 doesn't change anything. Is there anything else special in your setup? Which environment are you on?
If this was a general error, there would have been many reports for it already.
What is bugging me is the error message: `Cannot access property starting with "\0"`
If you search for it, it seems to be somehow related to protected properties and dynamic access to them.
For example: https://cweiske.de/tagebuch/php-property-started-nul.htm

**Comment by Kathara** [comment]
It's a dev environment, linux subsystem on windows, haven't had any problems with it so far. 

It's a new installation of TYPO3 (no upgrade).
It doesn't run with https.
I've used an extension that already has different content in it.

If I create the element with an icon, there's no problem with it and the error doesn't occur.

**Comment by nhovratov** [comment]
> If I save it without the icon, add the if-statement from above and then open the mask module again the element shows a broken page icon ("no icon found" type).

Yes, this is correct. As you don't register the Icon, the fallback broken icon symbol appears. The Mask IconProvider checks if there is a FontAwesome icon, if not, a fallback is provided with the first letter of the Element. So adding the if statement is not a real fix. We need to find the root cause, but I have no clue where to look for.

**Comment by Kathara** [comment]
Yes, I'm aware that the if-statement is not the real fix. And normally, if I'm not completely wrong, mask provides an icon that displays the first letter of the name of the element, shouldn't that be the backup instead of the broken page icon?

**Comment by nhovratov** [comment]
Look at the ContentElementIconProvider. It handles both, FontAwesome and fallback icons. Fallback icons are just displayed though CSS.

**Comment by Kathara** [comment]
And suddenly I can't recreate it anymore and the first letter icon is always displayed without the if-statement. Might be my environment after all in that case. Sorry for the inconvenience.

**Comment by nhovratov** [comment]
Really strange.

**Comment by Kathara** [comment]
If I should ever stumble on that error again, I'll try to find out what created it. My environment has some strange errors from time to time but they were very rarely reproducible. That's why I thought this one was quite strange. It might have had something to do with some caching and I might have cleared it at some point trying out stuff. In the end I restarted apache and after that it worked impeccably.
