### ISSUE TITLE
Missing labels for fields add to page templates

### ISSUE THREAD

**Issue by dkm-bb** [Gernott/mask#554]
Maybe this happened after I upgraded TYPO3 or Mask extension, but suddenly labels for new fields are not rendered. I have some page templates where the labels are shown as expected.

Tested on TYPO3 v. 12.4.1 and Mask 8.1.3

![Missing labels for fields created with mask](https://github.com/Gernott/mask/assets/16953883/45151a55-c6cf-4bf7-8d1b-0d702eb5adca)

The labels are shown in the mask.json file and looks the same as for the pages where the labels work

I'm afraid I don't have a lot more information as this.

**Comment by nhovratov** [comment]
Thanks for the report! This seems more like a TYPO3 core bug. The labels for pages (in contrast to tt_content) are generated by PageTsConfig. I will investigate this further.

**Comment by nhovratov** [comment]
Here is the core issue: https://forge.typo3.org/issues/100921

**Comment by nhovratov** [comment]
Fixed in Core, TYPO3 v12.4.2 will be released on 13.06.2023.
