### ISSUE TITLE
Remove duplicated element-label in TYPO3 v12 page module

### ISSUE THREAD

**Issue by peter-neumann-dev** [Gernott/mask#557]
The new page module introduced in TYPO3 v12 adds the header and subheader of an element by default above the backend preview template. Mask adds the label of the element before the backend preview template, but after the header. This is interrupting the content flow between headers and body of an element. Especially for Text or Text-Image elements.

![Peter Neumann 2023-05-30 at 16 07 49](https://github.com/Gernott/mask/assets/75690659/a344b5d5-bad9-4013-a50f-96da7d0567a6)

Since the new TYPO3 page module in v12 shows the label of an element by itself above the headers, I would suggest removing label from Mask for TYPO3 v12: 

![Peter Neumann 2023-05-30 at 16 18 55](https://github.com/Gernott/mask/assets/75690659/02c25053-d5a8-437b-a85e-f6b7a72e90fc)

For TYPO3 v11 the label was nice to have and also not interrupting because we rendered the headers inside the preview template. If possible, it could stay for ≤ v11.

**Comment by peter-neumann-dev** [comment]
Sounds plausible. 👍 Anyhow, since TYPO3 the standard header is now linked by default

**Comment by nhovratov** [comment]
Actually it was also rendered in TYPO3 v11 by default, but Mask overrides this with its Element label.
