### ISSUE TITLE
BUG: Nested content element relations aren't properly resolved.

### ISSUE THREAD

**Issue by alexanderschnitzler** [Gernott/mask#560]
Hi,
I found a bug with resolving nested mask elements that are of type content aka stored in tt_content with CType `tx_mask_foo`.

Let's say I have the following content elements:
- ElementList `tx_mask_elementlist`
- Element `tx_mask_element`
- OtherElement `tx_mask_otherelement`

All are stored in `tt_content`. Now I nest them like this:

ElementList has a field `tx_mask_elementlist_elements`, containing `n` elements of `CType` `tx_mask_element`.
Element has a field `tx_mask_element_otherelements`, containing `n` elements of `CType` `tx_mask_otherelement`.

Resolving the first level of relations works fine. But as soon as elements are nested any further, `\MASK\Mask\Helper\InlineHelper::addIrreToData()` is called with the wrong `CType`, the one of the parent, not the child.

https://github.com/Gernott/mask/blob/79d0f57b1af0cc76fc4a3522ebf26f23122bb9fe/Classes/Helper/InlineHelper.php#L172

This line must be `$this->addIrreToData($element, 'tt_content', $element['CType'], $originalTable);` instead.

**Comment by nhovratov** [comment]
Hey thank you very much for reporting this issue! I will test it.
