### ISSUE TITLE
EXT:container - sorting of mask CEs inside a container colPos is not possible

### ISSUE THREAD

**Issue by birgitberlin** [Gernott/mask#562]
I use mask CEs inside EXT:container containers.
It is not possible to drag and drop - or change sorting of - the mask teasers inside a container colPos.
In the backend I can cut and paste the mask CE to change the position - but in the frontend nothing happens.

TYPO3 11.5.27
EXT:container 2.2.2
EXT:mask 8.0.8, 8.1.5

EDIT: In the backend - there is no real change after leaving the page view.

**Comment by nhovratov** [comment]
Thanks, I will have a look.

**Comment by nhovratov** [comment]
Hey, I just tested it in on TYPO3 v12, Mask v8.2, Container 2.2.3 and it works just fine.
You said 

> It is not possible to drag and drop

Do you mean it doesn't work at all? Or you can drag them, but they don't move?
Also, do you use Mask backend previews? Please check if you have valid HTML and don't destroy the markup in the Page Module.

**Comment by birgitberlin** [comment]
I can drag, but the don't move.
Same behavior with cut and paste. There they seem to be moved - but only per JS. If the page view is left, they didn't.

I have no backend preview ( no Backend/Template/CExxx.html) für the mask CEs.

**Comment by nhovratov** [comment]
Hm, ok. Strange. Can you isolate the behaviour? Create a blank page with one container and put Mask Elements inside?
The thing is, there is nothing special about Mask elements. It is weird that it works for normal CEs for you.

**Comment by birgitberlin** [comment]
I will test it.
In my case, i want to change sorting of the mask elements  within a column (colPos=201), not from one to another.
Did you test that?

**Comment by nhovratov** [comment]
Yes. I understood that. I didn't test it yet on TYPO3 v11, but on v12 it works fine.

**Comment by nhovratov** [comment]
The important thing is, that the `sorting` field is updated.

**Comment by birgitberlin** [comment]
Yes, I know. 
Now I have tested again. And it works - don't know why.
May be, the composer update/autoload to mask v.8.1.5 yesterday did not take effect because of some cache in TYPO3 or on the server side.
Sorry for the effort - an THANK YOU for your great work!

**Comment by birgitberlin** [comment]
Yes, I know. 
Now I have tested again. And it works - don't know why.
May be, the composer update/autoload to mask v.8.1.5 yesterday did not take effect because of some cache in TYPO3 or on the server side.
Sorry for the effort - an THANK YOU for your great work!
