### ISSUE TITLE
Setting for save and close icon is not stored

### ISSUE THREAD

**Issue by PKuhlmay** [Gernott/mask#566]
The settings for the save and close button for a content element is not stored. Therefore the checkbox is not set, if I edit the element again.

I also get these Errors in the console:
ajax-request.js?bust=1688402128:13 Fetch finished loading: GET "https://eb-typo312-php81.ddev.site/typo3/ajax/mask/elements?token=de71b1962c8db8cdad1f55ac3abdf2c0df30ff65".
ajax-request.js?bust=1688402128:13 Fetch failed loading: GET "https://eb-typo312-php81.ddev.site/typo3/ajax/mask/loadElement?token=c532f2e72f4f85a47ef3f9023e8166e0a406e42e&type=tt_content&key=datetime".

**Comment by PKuhlmay** [comment]
I think this is not easy to solve by myself. 
You have this one inside the documentation: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Input/Properties/Max.html
And there is this one: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Datetime/Properties/Range.html

I am not sure which one to use. When I edit a datetime field in mask, I expect to get a link to the documentation for the datetime range. But when I edit a number field, I expect to get a link to the number documentation. At the moment the links which are set inside 
https://github.com/Gernott/mask/blob/23d68c591a08b0154e856d31d0886df4326afc66/Configuration/Mask/TcaFields.php#L323
are used for both fields, number and datetime.

**Comment by nhovratov** [comment]
Thanks for reporting the issue!
