### ISSUE TITLE
Links to the documentation are wrong at some places inside the mask module

### ISSUE THREAD

**Issue by PKuhlmay** [Gernott/mask#567]
The links to the documentation for some of the fields inside the mask backend module results into a 404 page.

I get errors for the links to range lower and range upper. 

![Bildschirmfoto 2023-07-03 um 18 49 24](https://github.com/Gernott/mask/assets/107543296/6f0d3e41-0a21-4edb-a56b-d58a5e986776)

The browser opens this link: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Input/Properties/Range.html#columns-input-properties-range

TYPO3 12.4.2
Mask dev-main

**Comment by PKuhlmay** [comment]
I think this is not easy to solve by myself. 
You have this one inside the documentation: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Input/Properties/Max.html
And there is this one: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Datetime/Properties/Range.html

I am not sure which one to use. When I edit a datetime field in mask, I expect to get a link to the documentation for the datetime range. But when I edit a number field, I expect to get a link to the number documentation. At the moment the links which are set inside 
https://github.com/Gernott/mask/blob/23d68c591a08b0154e856d31d0886df4326afc66/Configuration/Mask/TcaFields.php#L323
are used for both fields, number and datetime.

**Comment by nhovratov** [comment]
Yeah, they do collide. Theoretically it is possible to fix, but it would require to duplicate them 5 times for each possible type. Not worth it imo for a simple documentation link.
