### ISSUE TITLE
content fields with hidden item are rendered

### ISSUE THREAD

**Issue by medarob** [Gernott/mask#568]
Hi

Maybe that is not a mask issue but a fluid issue, or an issue at all. But I noticed the following:

I have a content field so that I can add multiple content elements.
![grafik](https://github.com/Gernott/mask/assets/33951787/754e0597-7157-4754-8c52-dac08b31db7b)

In the backend it looks like this. I deactivated some:
![grafik](https://github.com/Gernott/mask/assets/33951787/ec9b48d4-555c-40d8-aff0-d967c60fac44)

In fluid I use this:

```
            <f:if condition="{data.tx_mask_contentaz}">
                <f:for each="{data.tx_mask_contentaz}" as="data_item" iteration="i">
                    <p>{data_item}{i.index}</p>
                </f:for>
            </f:if>
```
Output in FE: 
![grafik](https://github.com/Gernott/mask/assets/33951787/611bb381-936c-46f1-9d4c-4e4a96917799)

The Problem I see:
It seems that hidden items are still rendered

I can add a condition like
```
                    <f:if condition="{data_item.hidden} !=1">
                        <p>{data_item}{i.index}</p>
                    </f:if>
```

so that I'll get the expected result and exclude all hidden elements:

![grafik](https://github.com/Gernott/mask/assets/33951787/726857fc-454b-4cae-b7e2-22d3ad1e29d9)

but I thought that this shouldn't be necessary?

If that is the way to go then I will add the condition. I just wanted to make sure it's not a bug but the intended behaviour.

TYPO3 11.5.28 / Mask 8.2.1

**Comment by nhovratov** [comment]
Hey, yes this is a current bug. I am investigating right now.
