### ISSUE TITLE
wrong preview in custom workspaces with inline field and content field element

### ISSUE THREAD

**Issue by medarob** [Gernott/mask#569]
I just noticed the following:

I have an inline field where I added a content field:

![grafik](https://github.com/Gernott/mask/assets/33951787/58e10817-3e74-4a57-a56e-2397af7c0df2)

Inside the content field I only added a custom content element which has the headline and bodytext fields.

![grafik](https://github.com/Gernott/mask/assets/33951787/71a741fc-1553-4d31-9d9f-e57ee98a6415)

In live workspace this looks like this in the BE preview:

![grafik](https://github.com/Gernott/mask/assets/33951787/65c7ea17-6d41-403e-b7c2-0a2b7c02d23a)

BE edit mode GERMAN:
![grafik](https://github.com/Gernott/mask/assets/33951787/f7fcf109-3393-4528-a244-dd0d040bc1a2)

and ENGLISH:
![grafik](https://github.com/Gernott/mask/assets/33951787/4ccf6106-d211-403c-8d3f-e03f9edada16)

so far so good.

If I switch to workspaces I get the following preview:

![grafik](https://github.com/Gernott/mask/assets/33951787/303afed5-7c95-4f45-9818-3b858145a9c1)

despite that I changed the headline and bodytext

German:
![grafik](https://github.com/Gernott/mask/assets/33951787/dba4365c-540b-41cf-b2d5-52826e30cc0e)

English:
![grafik](https://github.com/Gernott/mask/assets/33951787/442baea7-f7a5-4e45-aede-157d9b741ae8)

In the live workspace there is loren ipsum text and that text is shown in the workspace preview as well, despite that the text in the custom workspace is different and also has another headline.

My conslusion:
=> The preview in custom workspaces seems to be not working correctly (when I have an inline field and a content field element) because the text from the live workspace is shown instead.

TYPO3 11.5.29 and Mask 8.2.1

**Comment by nhovratov** [comment]
@medarob Hey, thanks for the report. Could you update to the latest 8.2.4 version and check everything again? I included a workspace fix there.

**Comment by medarob** [comment]
After the update to version 8.2.4 the preview is correct in custom workspaces 😃
