### ISSUE TITLE
Unknown column 'tx_mask_..._content_parent' in 'where clause' while running Upgrade Wizard

### ISSUE THREAD

**Issue by MatthiasRixen** [Gernott/mask#570]
I tried to execute "Migrates fields of type "Content" to new persistence structure." in the Upgrade Wizard and get the following Error:

![Unbenannt](https://github.com/Gernott/mask/assets/105218057/b42e7e53-f893-4cba-af69-d8697d456d28)

Not shure if this is a Mask Problem or TYPO3. Maybe you can help. Thanks!

**Comment by nhovratov** [comment]
Hey, this could happen if you:
1. Deleted this field in tt_content via DB Analyzer after upgrading Mask.
2. You have some leftovers in your mask.json file

First, try to identify which element and field is affected. Looks like you have a field "text_image_content".

**Comment by nhovratov** [comment]
There has to be somewhere a type `Content` field called `text_image_content`. Can you search your json files for that string?

> Doesn't use Mask the parent field as some kind of reference in the tt_content table?
Yes, the suffix "_parent" was appended to reference the parent record for nested content elements. This got changed in Mask 8.2 so a migration is needed now.

**Comment by MatthiasRixen** [comment]
Following the Config of the Mask Element:

{
    "version": "8.1.0",
    "restructuringDone": true,
    "tables": {
        "tt_content": {
            "elements": {
                "text_image": {
                    "color": "#000000",
                    "colorOverlay": "#000000",
                    "columns": [
                        "header",
                        "tx_mask_text_image_content",
                        "tx_mask_text_image_image",
                        "tx_mask_text_image_alignment",
                        "tx_mask_text_image_bgcolor"
                    ],
                    "columnsOverride": {
                        "tx_mask_text_image_alignment": {
                            "config": {
                                "default": "alignment_1",
                                "fieldWizard": {
                                    "selectIcons": {
                                        "disabled": 1
                                    }
                                },
                                "items": [
                                    {
                                        "description": "",
                                        "group": "",
                                        "icon": "",
                                        "label": "Text links \/ Bild rechts",
                                        "value": "alignment_1"
                                    },
                                    {
                                        "description": "",
                                        "group": "",
                                        "icon": "",
                                        "label": "Bild links \/ Text rechts",
                                        "value": "alignment_2"
                                    }
                                ],
                                "renderType": "selectSingle"
                            },
                            "fullKey": "tx_mask_text_image_alignment",
                            "key": "text_image_alignment",
                            "type": "select"
                        },
                        "tx_mask_text_image_bgcolor": {
                            "config": {
                                "default": "none",
                                "fieldWizard": {
                                    "selectIcons": {
                                        "disabled": 1
                                    }
                                },
                                "items": [
                                    {
                                        "description": "",
                                        "group": "",
                                        "icon": "",
                                        "label": "Ohne",
                                        "value": "none"
                                    },
                                    {
                                        "description": "",
                                        "group": "",
                                        "icon": "",
                                        "label": "Dunkelblau",
                                        "value": "color_4"
                                    },
                                    {
                                        "description": "",
                                        "group": "",
                                        "icon": "",
                                        "label": "Blau",
                                        "value": "color_1"
                                    },
                                    {
                                        "description": "",
                                        "group": "",
                                        "icon": "",
                                        "label": "Orange",
                                        "value": "color_2"
                                    },
                                    {
                                        "description": "",
                                        "group": "",
                                        "icon": "",
                                        "label": "Gr\u00fcn",
                                        "value": "color_7"
                                    },
                                    {
                                        "description": "",
                                        "group": "",
                                        "icon": "",
                                        "label": "Pink",
                                        "value": "color_8"
                                    },
                                    {
                                        "description": "",
                                        "group": "",
                                        "icon": "",
                                        "label": "Lila",
                                        "value": "color_9"
                                    },
                                    {
                                        "description": "",
                                        "group": "",
                                        "icon": "",
                                        "label": "Hellblau",
                                        "value": "color_6"
                                    }
                                ],
                                "renderType": "selectSingle"
                            },
                            "fullKey": "tx_mask_text_image_bgcolor",
                            "key": "text_image_bgcolor",
                            "type": "select"
                        },
                        "tx_mask_text_image_content": {
                            "cTypes": [
                                "mask_header",
                                "header",
                                "text",
                                "mask_text",
                                "mask_link",
                                "mask_contact"
                            ],
                            "config": {
                                "appearance": {
                                    "collapseAll": "1",
                                    "enabledControls": {
                                        "delete": 1,
                                        "dragdrop": 1,
                                        "hide": 1,
                                        "info": 1,
                                        "localize": 1,
                                        "new": 1,
                                        "sort": 1
                                    },
                                    "expandSingle": 0,
                                    "levelLinksPosition": "both",
                                    "showAllLocalizationLink": 1,
                                    "showNewRecordLink": 1,
                                    "showPossibleLocalizationRecords": 1,
                                    "useSortable": 1
                                },
                                "foreign_sortby": "sorting",
                                "overrideChildTca": {
                                    "columns": {
                                        "colPos": {
                                            "config": {
                                                "default": 999
                                            }
                                        }
                                    }
                                }
                            },
                            "fullKey": "tx_mask_text_image_content",
                            "key": "text_image_content",
                            "type": "content"
                        },
                        "tx_mask_text_image_image": {
                            "config": {
                                "appearance": {
                                    "elementBrowserEnabled": 1,
                                    "enabledControls": {
                                        "delete": 1,
                                        "dragdrop": 1,
                                        "hide": 1,
                                        "info": 1,
                                        "localize": 1,
                                        "sort": 0
                                    },
                                    "fileByUrlAllowed": 1,
                                    "fileUploadAllowed": 1,
                                    "useSortable": 1
                                },
                                "maxitems": "1",
                                "minitems": "1"
                            },
                            "fullKey": "tx_mask_text_image_image",
                            "key": "text_image_image",
                            "type": "media"
                        }
                    },
                    "description": "Text + Bild mit ausw\u00e4lbarer Ausrichtung und Hintergrundfarbe",
                    "descriptions": [
                        "",
                        "",
                        "",
                        "",
                        ""
                    ],
                    "icon": "",
                    "iconOverlay": "",
                    "key": "text_image",
                    "label": "Text-Bild",
                    "labels": [
                        "Name (in der Webseite nicht sichtbar)",
                        "Inhalt",
                        "Bild",
                        "Ausrichtung",
                        "Hintergrundfarbe"
                    ],
                    "shortLabel": "",
                    "sorting": 26
                }
            },
            "sql": {
                "tx_mask_text_image_alignment": {
                    "tt_content": {
                        "tx_mask_text_image_alignment": "varchar(255) DEFAULT '' NOT NULL"
                    }
                },
                "tx_mask_text_image_bgcolor": {
                    "tt_content": {
                        "tx_mask_text_image_bgcolor": "varchar(255) DEFAULT '' NOT NULL"
                    }
                },
                "tx_mask_text_image_content": {
                    "tt_content": {
                        "tx_mask_text_image_content": "int(11) unsigned DEFAULT '0' NOT NULL"
                    }
                },
                "tx_mask_text_image_image": {
                    "tt_content": {
                        "tx_mask_text_image_image": "int(11) unsigned DEFAULT '0' NOT NULL"
                    }
                }
            },
            "tca": {
                "header": {
                    "coreField": 1,
                    "fullKey": "header",
                    "key": "header",
                    "type": "string"
                },
                "tx_mask_text_image_alignment": {
                    "config": {
                        "type": "select"
                    },
                    "fullKey": "tx_mask_text_image_alignment",
                    "key": "text_image_alignment",
                    "type": "select"
                },
                "tx_mask_text_image_bgcolor": {
                    "config": {
                        "type": "select"
                    },
                    "fullKey": "tx_mask_text_image_bgcolor",
                    "key": "text_image_bgcolor",
                    "type": "select"
                },
                "tx_mask_text_image_content": {
                    "cTypes": [
                        "mask_header",
                        "header",
                        "text",
                        "mask_text",
                        "mask_link",
                        "mask_contact"
                    ],
                    "config": {
                        "foreign_table": "tt_content",
                        "type": "inline"
                    },
                    "fullKey": "tx_mask_text_image_content",
                    "key": "text_image_content",
                    "type": "content"
                },
                "tx_mask_text_image_image": {
                    "config": {
                        "minitems": ""
                    },
                    "fullKey": "tx_mask_text_image_image",
                    "key": "text_image_image",
                    "type": "media"
                }
            }
        }
    }
}

**Comment by nhovratov** [comment]
Okay, I guess the Update is not necessary then. I will improve the Wizard so it checks, whether these fields actually exist.

**Comment by nhovratov** [comment]
This is only needed, if you have upgraded Mask from < 8.2 and added the Content field there.

**Comment by MatthiasRixen** [comment]
I just recently Updated Mask from 8.2.2 to 8.2.4. Backend Report is telling me that the Installation is not fully completed ...

**Comment by nhovratov** [comment]
Yes, the "updateNecessary" check is flawed. It only checks for existence of a type Content field. In addition is also should check if the db columns exist.

**Comment by MatthiasRixen** [comment]
Thank you! Really appreciate!

**Comment by nhovratov** [comment]
> Thank you! Really appreciate!

Thanks! I just released v8.2.5. Now it should be all fine.
