### ISSUE TITLE
collision between FontAwesome 4 and 5 in backend

### ISSUE THREAD

**Issue by medarob** [Gernott/mask#571]
For a while now, the following problem exists:
When you have two extensions and each one uses a different FontAwesome version in the backend.

**example:**
Mask still uses FontAwesome 4. (I just noticed the usage of the extension `friendsoftypo3/fontawesome-provider` in the system and it seems it is required by mask)
We have another extension installed which uses FA5: https://github.com/DirkPersky/typo3-rte-ckeditor-fontawesome

If I chose an icon for a mask element the following will be shown on pages, which have an RTE field:
![grafik](https://github.com/Gernott/mask/assets/33951787/48367410-ac11-4de7-9dc2-d045ac8a7b30)

This should be the circle icon.

It seems that the icon unicode value has changed (and probably also the syntax) in FA5.
So, FontAwesome 5 is now used in the backend because of the other extension.

**Solution/Suggestion**
Is it possible to add an option in the mask configuration to choose the FontAwesome version which should be used in the backend, so that mask supports FA5 (and maybe FA6 for the future)?

I know, that this happens only if two or more extensions with different versions of FontAwesome are used.

**Comment by medarob** [comment]
ok, that seems to be a duplicate of https://github.com/Gernott/mask/issues/485 ?

**Comment by nhovratov** [comment]
Yes, seems like it.

**Comment by nhovratov** [comment]
Closing as of duplicate.
