### ISSUE TITLE
mod.wizards.newContentElement.wizardItems.mask has no effects on TYPO3 12

### ISSUE THREAD

**Issue by stephangrass** [Gernott/mask#573]
mod.wizards.newContentElement.wizardItems.mask seems not to work under TYPO3 version 12. It is not possible to create modifications of the Content Element Wizard for Mask.

**Comment by nhovratov** [comment]
Hey @stephangrass what exactly does not work? Remember to set Mask as a dependency, if you try to override stuff.

**Comment by stephangrass** [comment]
For example
mod.wizards.newContentElement.wizardItems.mask.show =
will not work.
I have set mask as require in my composer.json

**Comment by nhovratov** [comment]
This works without pronlems in my dev installation. Are you sure your TsConfig is loaded? Check the PageTsConfig Module "Active PageTsConfig"

**Comment by stephangrass** [comment]
Hmmm. TsConfig is loaded.
mod.wizards.newContentElement.wizardItems.menu.show =
mod.wizards.newContentElement.wizardItems.special.show = 
works ...

**Comment by nhovratov** [comment]
Ok, can you tell me what you are trying to set specifically?

**Comment by stephangrass** [comment]
I will resort the complete newContentElement.wizard

Something like this:

`mod.wizards.newContentElement.wizardItems {
    common {
        elements {
            mask_text < mod.wizards.newContentElement.wizardItems.mask.elements.mask_text
            mask_textbild < mod.wizards.newContentElement.wizardItems.mask.elements.mask_textbild
            div < mod.wizards.newContentElement.wizardItems.special.elements.div
            shortcut < mod.wizards.newContentElement.wizardItems.special.elements.shortcut
        }
        show := addToList(mask_text, mask_textbild, div, shortcut)
    }
    mask.show =
    menu.show =
    special.show = removeFromList(div,shortcut)
}`

**Comment by nhovratov** [comment]
I tried the exact config and it works in my instance. My guess is that your loading order is not correct, so your sitepackage is loaded before Mask. Can you confirm this in your PackageStates / PackageArtifact ?

**Comment by stephangrass** [comment]
No. Mask is loaded before my sitepackage. Strange ...

**Comment by nhovratov** [comment]
Do you use mabye the new global page.tsconfig inclusion method? I can reproduce it with that.

**Comment by stephangrass** [comment]
Oh, yes, i use this method ... Ok ... Thanks ...

**Comment by nhovratov** [comment]
Yeah, with the classic inclusion you are good to go. Thanks for fast feedback and sorry for the late response to your issue.
