### ISSUE TITLE
Row limit tt_content

### ISSUE THREAD

**Issue by PaDa19** [Gernott/mask#574]
Hello,

I have build a lot of mask elements and have now reached the row limit of the tt_content table. I already changed the field size for the text fields from varchar(255) to varchar(60) a while back but now I hit the limit again.

Three possible solutions come to mind:
1. Reuse fields as much as possible to save space in tt_content
2. Wrap all fields in each Mask element inside a recurring content element so that the actual fields will be saved in a separate table
3. Change all varchars to Textfields

Both have some drawbacks.

Has anyone else hit the row size limit and found a better solution?

Thanks,
Patrick.

**Comment by PaDa19** [comment]
Thanks for your reply. I saw in the docs that this is now available and will give it a try during the weekend.

**Comment by nhovratov** [comment]
Closing this issue. All available information about this issue can be found in the documentation.
