### ISSUE TITLE
Expose new mask columns to TYPO3 Database Analyser

### ISSUE THREAD

**Issue by ghedeonn** [Gernott/mask#576]
Hello, 

I have realised that because the "tt_content" and "pages" new mask columns are created manually, there is no "ext_tables.sql" that has all the new columns, which makes the "Maintenance->Analyse Database Structure" function to always recommend to remove those columns.

It would be nice if this problem can be solved.

One possible solution to this could be updating/maintaining the "ext_tables.sql" file with the new fields, so TYPO3 will not try to remove them, each time it is analysing the database.

<img width="1021" alt="Screenshot 2023-08-03 at 11 09 58" src="https://github.com/Gernott/mask/assets/2467647/026a4d5c-1199-4310-afd2-6e0ecee2ef6a">

Thank you,
Sabrin

**Comment by nhovratov** [comment]
As there was no response for almost 2 months, I'm closing this issue. If you still have issues, feel free to create another issue or ask help on Slack.
