### ISSUE TITLE
Images in CType "image" not sortable any more

### ISSUE THREAD

**Issue by devxpoint** [Gernott/mask#582]
In a mask element, I use the TYPO3 standard CType "image" wort "sort" enabled and add some images as usual.
But the images are not sortable anymore. (Version 8.2.6)

![Firefox_Screenshot_2023-08-21T06-29-39 530Z](https://github.com/Gernott/mask/assets/4798067/e1c0e1e0-be2c-42d1-9417-5208ff040ffe)

![Firefox_Screenshot_2023-08-18T10-44-52 281Z](https://github.com/Gernott/mask/assets/4798067/84a5d38e-cf1d-45e7-b2aa-252f0fd45ab3)

Is this a bug or missed I something?

**Comment by devxpoint** [comment]
Hi, that icons title says "show in all views", but if I click on it, nothing happens.
Console/network view is empty. Hmm...

**Comment by nhovratov** [comment]
Ok, thank you. I will test it on TYPO3 v11.5. In v12 it looks good. It has probably something to do with the new feature introduced in Mask 8.1, where you can now override core fields TCA.

**Comment by nhovratov** [comment]
Found the bug, fixed in 8.3.1. Thank you for reporting the issue!

**Comment by devxpoint** [comment]
Great, now it works :)
