### ISSUE TITLE
Error when Restructuring fields

### ISSUE THREAD

**Issue by ReneReiterer** [Gernott/mask#584]
I just enabled the override shared fields feature and got the message "Restructuring of fields needed!". When i click on the buton "Restructure Mask definitions" nothing happens. When i look in the console i get this error 

![image](https://github.com/Gernott/mask/assets/90260812/11a298eb-c996-42d5-824c-72fec597eb31)

When i open the link Mask is trying to call in another tab i get this typo3 error: 

![image](https://github.com/Gernott/mask/assets/90260812/2433cbf6-5c93-4731-bf6c-2d416aca9501)

i am running Typo3 v12.4.4 with Mask version 8.2.6

**Comment by ReneReiterer** [comment]
Updating to 8.3.1 doesnt fix the error

**Comment by nhovratov** [comment]
Hi Rene, thanks for trying out the new feature. Could you send me your json file(s), so I can debug it locally?

**Comment by ReneReiterer** [comment]
Hey, 

sure thing, this the one you want right? 

http://jsonblob.com/1146740054919340032

**Comment by nhovratov** [comment]
Yes, perfect thanks. I will try to reproduce the error and fix it if necessary.

**Comment by nhovratov** [comment]
Thank you for reporting the issue, I could solve it. Fixed in the now released v8.3.2 version.
