### ISSUE TITLE
Fatal Error in combination with EXT:flux

### ISSUE THREAD

**Issue by rfuehricht** [Gernott/mask#585]
Hi!

I asked in EXT:flux for help but it seems that this might rather be an issue in EXT:mask (see: https://github.com/FluidTYPO3/flux/issues/2132).

When editing a content element, this error is shown:

<img width="939" alt="Screenshot 2023-09-05 at 15 04 57" src="https://github.com/Gernott/mask/assets/144118058/968b7636-18a8-46ea-888c-3f19229e4814">

Mask introduces two itemsProcFuncs and calls previously set itemsProcFuncs using this code:

`
GeneralUtility::callUserFunction(
                $params['config']['m_itemsProcFunc'],
                $params,
                $this
            );
`

As stated in the issue I created for EXT:flux, the third parameter should not be `$this`, but rather the parent object calling the itemsProcFunc. 

So, I propose to add a second parameter to the itemsProcFunc an pass it in the `callUserFunction`call:

`public function itemsProcFunc(&$params, $parentObj): void`
...

`
GeneralUtility::callUserFunction(
                $params['config']['m_itemsProcFunc'],
                $params,
                $parentObject
            );
`

**Comment by nhovratov** [comment]
Hi, thanks for the issue reporting. Fixed it like you suggested. Will release a new version soon.

**Comment by nhovratov** [comment]
@rfuehricht Can you verify, that this fixes the issue for you? I'll wait with the release until I have a "go" from you, as I didn't setup the flux extension in my development environment to test it.

**Comment by rfuehricht** [comment]
Hi!

I can confirm, that the fix solves the issue.

Thank you very much.

**Comment by nhovratov** [comment]
@rfuehricht Thank you for verifying! Mask 8.3.3 is released now.

**Comment by NamelessCoder** [comment]
Thanks for the quick fix @nhovratov ;)
