### ISSUE TITLE
Icons are not displayed inside new content element wizard

### ISSUE THREAD

**Issue by PKuhlmay** [Gernott/mask#591]
Shouldn't the icons be displayed inside the new content element wizard?

I have the following settings inside my content element:
![Bildschirmfoto 2023-09-18 um 15 44 18](https://github.com/Gernott/mask/assets/107543296/79a54b5b-788b-43ae-8952-703cb13502ad)

I assumed to see the same icon inside the wizard:
![Bildschirmfoto 2023-09-18 um 15 44 03](https://github.com/Gernott/mask/assets/107543296/422668e2-bcee-4cd9-a955-19b72c3a492f)

TYPO3 12.4.6
mask v8.3.5

**Comment by nhovratov** [comment]
Duplicate: https://github.com/Gernott/mask/issues/551
