### ISSUE TITLE
Backend preview template: disabled image is shown in backend preview

### ISSUE THREAD

**Issue by medarob** [Gernott/mask#592]
I have the following custom history timeline element

![grafik](https://github.com/Gernott/mask/assets/33951787/8b9cbc85-e370-4db3-9c06-b895233267de)

When I add an image but disable/hide it, then the image is still shown in the backend preview.
```
<f:if condition="{data.tx_mask_historieeintraegejahr}">
      <f:for each="{data.tx_mask_historieeintraegejahr}" as="data_item">
         <f:if condition="{data_item.tx_mask_historieeintrag}">
            <f:for each="{data_item.tx_mask_historieeintrag}" as="data_item_item">
               <f:if condition="{data_item_item.tx_mask_historiebild}">
                   <f:then>
                      <f:image image="{data_item_item.tx_mask_historiebild.0}" />
                   </f:then>
                   <f:else>
                       <img class="img-fluid" src="{f:uri.resource(path:'Images/history_default.jpg', extensionName: 'MyExtension')}" />
                   </f:else>
                </f:if>
            </f:for>
         </f:if>
      </f:for>
</f:if>
```

I added a fallback but the fallback image is not shown in the backend preview if the image is disabled. Only when I delete the image, this works.

**What I expected:**
Disabled images shouldn't be shown in the backend template.
Shouldn't they be treated like a deleted image?

Everything works in the frontend template, regardless if I just disable the image or delete it from the element.

TYPO3 11.5.31 and Mask 8.3.5

**Comment by nhovratov** [comment]
This is expected behaviour for the backend. The restriction fields are not applied in the whole backend context. Otherwise you wouldn't be able to edit hidden records.

My suggestion: Either check yourself for the hidden field and don't render it, or add special styling for hidden images.
