### ISSUE TITLE
Is there a way to pass a value to a content field?

### ISSUE THREAD

**Issue by ReneReiterer** [Gernott/mask#594]
if i have a content fieldtype and output them the normal way 

`<f:cObject typoscriptObjectPath="lib.tx_mask.content">{data_item.uid}</f:cObject>`

is there a way i could pass the "child" some value? like a variable i set in the parent?

**Comment by nhovratov** [comment]
You could pass something via `data="{fruit: 'banana'}"` and then access it via TypoScript:

```
tt_content.mask_myelement {
    variables {
        fruit = TEXT
        fruit.field = fruit
    }
}
```
(disclaimer: didn't test it)

Links:
- https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Fluid/UsingTypoScriptCObjectViewHelper.html#cobject-viewhelper
- https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/ContentObjects/Fluidtemplate/Index.html#variables

**Comment by ReneReiterer** [comment]
Thanks for the Info, 
i think i found a solution that would work,

if i edit the lib.tx_mask.content to look like this: 

`lib.tx_mask.content = RECORDS
lib.tx_mask.content {
    tables = tt_content
    source.data = field:uid
    dontCheckPid = 1
}`

it works with the data attribute

and to access the custom value i pass it, i can just access the "parentRecord" variable

![image](https://github.com/Gernott/mask/assets/90260812/a5a03491-6dfc-4f65-91e0-a68d222334aa)

even though this works, its not backwards compatible, so it only works if you use the data attribute and give it the uid that way.
couldnt figure out how to make it work with both at the same time

**Comment by nhovratov** [comment]
There is also a way without TypoScript involved: You could extract the Fluid Template of your child Content Element into a partial and then render it manually inside your "root" Element. You just need to pass `{data_item}` to the partial as the `{data}` variable like: `<f:render partial="ChildContentElement" parameter="{data: data_item}"`/>

**Comment by ReneReiterer** [comment]
True, that would work too
