### ISSUE TITLE
Reloading mask configuration from another extension

### ISSUE THREAD

**Issue by ReneReiterer** [Gernott/mask#595]
I have a extension that should be able to change certain values in the mask.json configuration file, depending on user input. 
problem is, to have the changes reflect, i have to go into mask and save a content element, otherwise it just shows the old value. 

Is there a way to do this programatically? so you dont have to do it manually?

**Comment by nhovratov** [comment]
There is a whole API for persistence of the mask.json file:

`MASK\Mask\Loader\JsonLoader->write()` and `MASK\Mask\Loader\JsonLoader->load()`

The transmission object is the `MASK\Mask\Definition\TableDefinitionCollection`. Depending on user input, you can change values down to `MASK\Mask\Definition\TcaFieldDefinition->realTca` and pipe it back to the write method.

**Comment by nhovratov** [comment]
If you need further help, please come to Slack #ext-mask.
