### ISSUE TITLE
Removed database entries of the content field.

### ISSUE THREAD

**Issue by nitsan-technologies** [Gernott/mask#596]
I have faced major issues after upgrading from TYPO3 v11 To TYPO3 v12.

My issue is all the content was removed from the content field after upgrading my project.
Can you please check the below screenshot and help me for the same?

Field: https://prnt.sc/f1Tbb4R-9I48
Removed data: https://prnt.sc/XmV2xgtzVr8l
TYPO3 v11 Data: https://prnt.sc/4NL-GfOk9VnW

Thanks in advance 🙏

**Comment by nhovratov** [comment]
Hey, check your Upgrade Wizard. There was a change in persistence of type `Content` fields.

```
// composer mode
vendor/bin/typo3 mask:restructureOverrideFields

// classic mode
typo3/sysext/core/bin/typo3 mask:restructureOverrideFields
```

**Comment by nitsan-technologies** [comment]
Hello @nhovratov

Thanks For the quick help 🙏 

I have already checked the whole documentation as you have shared and followed these points.

- We have already followed this step but have not resolved this issue.
- On my site, one module data is gone after upgrading to the TYPO3 Version 12. https://prnt.sc/TVpcWrbvU6Fk
- I have used the content field in Page property https://prnt.sc/TVpcWrbvU6Fk, https://prnt.sc/LuupdMXyN-77
- There is something wrong with the page property data also.

Thanks Again.

**Comment by nhovratov** [comment]
@nitsan-technologies 
I just tested the same constellation with a Content field on the page table in TYPO3 v11 and updated to v12. After running the upgrade wizard, the relation was restored correctly.

I have no idea, what went wrong in your installation. What you need to do, is to check the database tt_content table.
There should be a colum called `tx_mask_faq_parent`, which points to the uid of the page record.

This was changed to three new columns:
- tx_mask_content_parent_uid (value of  `tx_mask_faq_parent`)
- tx_mask_content_role (name of the field. In your case `tx_mask_faq`)
- tx_mask_content_tablenames (The parent table. In your case `pages`)

The migration wizard does just that. Have a look. As long as you didn't delete `tx_mask_faq_parent`, you should be able to restore the relation.

**Comment by nhovratov** [comment]
@nitsan-technologies were you able to resolve the problem?

**Comment by nitsan-technologies** [comment]
@nhovratov 
Thanks For the follow-up.

I have checked your last comment and Implemented all the points in my project.

Something wrong with my specific project. so I have created a new upgrade wizard class.
**See here for your understanding** > https://prnt.sc/s8iA6ElLUy0K
**File Path** > Classes>Updates>MigratePageFaq.php

Based on your last comment everything is working well with another project and setup but the issue occurs on my specific project.

Now Issue is resolved with our custom solution.

If you have any idea about this issue in the future please connect with me. really I want a better solution 🥲 

I appreciate your dedication and Quick Support.

Thanks Again!

**Comment by nhovratov** [comment]
Thanks for coming back and posting your solution! I will have an eye on this. For now, I'll close this one as I can't see anything wrong in my migration wizard.
