### ISSUE TITLE
icon file not displayed

### ISSUE THREAD

**Issue by stephangrass** [Gernott/mask#598]
I wanted to assign an icon file to a repetition field via the icon path. However, this does not work. The icon is not displayed. 
I integrated it through EXT:myextension/Resources/Public/Icons/icon.svg. The result: <img src="/typo3/" ...

**Comment by nhovratov** [comment]
Hi @stephangrass, I will have a look thanks. Could you answer these questions please:
- TYPO3 version
- Mask version
- composer mode / classic mode

**Comment by stephangrass** [comment]
Ah, ok.
TYPO3 12, Composer, Mask 8.3.5

**Comment by nhovratov** [comment]
Hey, I just tested it and it works for me. Did you add the Public folder, after you installed your extension? I could be possible, that your Public folder ist not published yet in _assets. You can just run `composer install` again and it should create it automatically.

**Comment by stephangrass** [comment]
I'm truly sorry for the trouble. I mistakenly used "my-extension" instead of "my_extension" as the extension key. Sometimes, you can't see the forest for the trees.

**Comment by nhovratov** [comment]
Happens to all of us, no problem :)
