### ISSUE TITLE
Undefined array key

### ISSUE THREAD

**Issue by dennismetz** [Gernott/mask#599]
When I disable a backend user I get the following error message:

PHP Warning: Undefined array key "tree" in ...vendor/mask/mask/Classes/ExpressionLanguage/MaskFunctionsProvider.php line 48

TYPO3 12.4.7
PHP 8.1.23
Mask: 8.3.5

**Comment by nhovratov** [comment]
Thanks for reporting, I will have a look.

**Comment by nhovratov** [comment]
Thank you again for the bug report. Fixed in v8.3.6.
