### ISSUE TITLE
mask and fluidcontent 

### ISSUE THREAD

**Issue by werkraum-admin** [Gernott/mask#6]
In my current project I encountered following problem: 
setup:
Typo3 CMS 7.6 LTS
fluidcontent 7.6
flux, vhs, fluidcontent_core etc
mask 1.1.1

Problem:
I created a gridelement with flux and some content elements with mask. When I created a new CE inside a grid the ce disappeared. So I started tracking the cause of this problem.
Inside maskutility.php I changed the following:
(setElementsTca)
line 408 : 
$defaultTabs = ",--div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.access,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.visibility;visibility,--palette--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:palette.access;access,--div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.extended,--div--;LLL:EXT:lang/locallang_tca.xlf:sys_category.tabs.category,categories,--div--;LLL:EXT:flux/Resources/Private/Language/locallang.xlf:tt_content.tabs.relation, tx_flux_parent, tx_flux_column, tx_flux_children;LLL:EXT:flux/Resources/Private/Language/locallang.xlf:tt_content.tx_flux_children";

Now everything works fine for me :)

**Comment by butu** [comment]
Moved to https://forge.typo3.org/issues/76420
