### ISSUE TITLE
Palette for Content Elements

### ISSUE THREAD

**Issue by rov-sf** [Gernott/mask#600]
Hi,

i got the same error message like in **Palette for Page Templates**  #528 , when i put palettes into a content element.
We are using 7.2.16 (because of the exporter).

Greetings
Robert

**Comment by nhovratov** [comment]
Hi Robert, the fix is included in v7.2.16. I wonder how you still get this error. Could you provide some more details / conext?

**Comment by rov-sf** [comment]
<img width="430" alt="Bildschirmfoto 2023-10-20 um 16 09 58" src="https://github.com/Gernott/mask/assets/92857218/f42c3e4b-2a80-4725-94ed-87bf18892d7e">

When i replace the "Button Tracking" tab with a palette, i get the same Error as in #528 
Also the description field for tabs are not rendered.

**Comment by nhovratov** [comment]
What exactly is the error message?

> The TCA for xy must not be empty

What is xy in your case?

> Also the description field for tabs are not rendered.

Tabs don't have a description in TYPO3. This is an error of Mask to show a description field. This can be used for internal notes, though.

**Comment by rov-sf** [comment]
> What exactly is the error message?

[ InvalidArgumentException ]                                                              
The TCA for the field "tx_mask_sf_button_secondary_tracking_category" must not be empty. 

> Tabs don't have a description in TYPO3. This is an error of Mask to show a description field. This can be used for internal notes, though.

I just saw it and thought it is a working feature :)

**Comment by nhovratov** [comment]
Ok, do you use the JsonSplitLoader (json-split) functionality?
Does the error only happen in page templates?

**Comment by rov-sf** [comment]
> Ok, do you use the JsonSplitLoader (json-split) functionality?

We are using the `JsonLoader`

> Does the error only happen in page templates?

This error Occurs in "Content Elements". We don't use "Page Templates" with custom fields.

**But i tested it:**
When i put a palette into an `Page Template` i will get this error: 
`The TCA for the field "tx_mask_5af573f85c1b3" must not be empty.`
When i go back to Mask, the palette has vanished and when i try to override, the exeception above will be triggered again.

<img width="468" alt="Bildschirmfoto 2023-10-23 um 18 06 20" src="https://github.com/Gernott/mask/assets/92857218/108e9116-7850-4e51-9504-9a3b032ae52f">

**Comment by nhovratov** [comment]
Closing as there was no feedback for 1 month.
