### ISSUE TITLE
Broken Mask Configuration Backend

### ISSUE THREAD

**Issue by fallefreundig** [Gernott/mask#604]
A couple weeks ago I’ve upgraded a TYPO3 10 installation to TYPO3 11 and as part of this maintenance I’ve upgraded Mask to version 8, too. There was not a task in the Upgrade Wizard like this: https://docs.typo3.org/p/mask/mask/main/en-us/Upgrade/Index.html#from-v8-0-x-or-lower

The frontend was doing fine as well as adding or editing any of the existing Mask content elements. 
Today, I wanted to edit a Mask module, but the view is broken. The saving button is also not working, since it’s just showing the loading animation forever. 

![Bildschirmfoto 2023-11-10 um 14 24 31](https://github.com/Gernott/mask/assets/7280223/dcbc1f14-249c-40f8-82fd-cd70fa5d8350)
![Bildschirmfoto 2023-11-10 um 14 24 46](https://github.com/Gernott/mask/assets/7280223/2f0321d8-cd4e-4922-b0e2-e19e62177f8f)

Is my problem related to the Upgrade Wizard? I’m not even sure if the bug is related to the recent upgrade, since I haven’t changed anything within the Mask configuration for a longer time. 

I’m more than happy for any suggestions or help!

**Comment by nhovratov** [comment]
Hi, first of all you should download the german language pack for Mask, as there are missing labels everywhere.
Some questions:
- At which version of Mask did you update? You were on TYPO3 v10, so it can be v5, v6 or v7.
- Did you update TYPO3 and Mask before that? Is the initial version of the installation older than TYPO3 v10?
- Do you have the original Mask json file? If yes, you can send it to me, and I will have a look if there is anything broken.

**Comment by fallefreundig** [comment]
Thank you so much for your super quick response. :) 

- The language packages are up to date, but the labels are not showing up in the source code.
- I’ve updated from version 7.2.15.
- TYPO3 10 was the initial version of the website. The initial Mask version was 6.4. 
- Since it’s a non profit I’m volunteering for, I’ve tried to keep it up to date from time to time. 
- I’m using Git, if that is any help. I should also have a backup from the old database. (I just hope, there would be an easier workaround, since there’s lots of new content already)
- Attached, you’ll find the old and the current .json-file. Anything suspicious, like the false restructuringDone comment?

[OLD_mask.json](https://github.com/Gernott/mask/files/13320047/OLD_mask.json)
[LATEST_mask.json](https://github.com/Gernott/mask/files/13320048/LATEST_mask.json)

**Comment by nhovratov** [comment]
works without problems on my development environment:

![Screenshot 2023-11-10 at 15-04-53 Mask DEV TYPO3 CMS 11 5 32](https://github.com/Gernott/mask/assets/19343425/59a78edb-fb9b-40a3-aa8c-93367c514628)
![Screenshot 2023-11-10 at 15-04-47 Mask DEV TYPO3 CMS 11 5 32](https://github.com/Gernott/mask/assets/19343425/5746483e-1e86-4d7c-97a0-a407a20258dd)

**Comment by nhovratov** [comment]
There is something else ill on your installation. Are there any console errors which might hint something?

**Comment by fallefreundig** [comment]
Well, thank you. Could it be related to this migration task, I’ve mentioned earlier?

There is only an error when clicking the Save-Button:

> TypeError: Cannot read properties of undefined (reading 'iconPicker')
    at ii.getPostElement (AmdBundle.js?bust=1699626849:20:27543)
    at ii.save (AmdBundle.js?bust=1699626849:20:26478)
    at on (AmdBundle.js?bust=1699626849:7:19353)
    at HTMLButtonElement.n (AmdBundle.js?bust=1699626849:7:9284)
    at Ar.o._wrapper (AmdBundle.js?bust=1699626849:7:53238)

**Comment by nhovratov** [comment]
> Well, thank you. Could it be related to this migration task, I’ve mentioned earlier?

I don't think it has something to do with the migration task, as it works in my installation without any migration.

Sorry, I've never encountered this error so far. Does anything else work fine in your TYPO3 instance?
The Mask backend seems not to work at all. But it's unrelated to the json file.
Why are all labels missing? This is not normal.

**Comment by fallefreundig** [comment]
Everything else is working perfectly. No errors, no issues adding new content, nothing. 
Re-installing Mask didn’t help either, of course.

I guess, for now the website is just not scalable anymore. :-(

**Comment by fallefreundig** [comment]
Thank you anyway very much for your effort!

**Comment by nhovratov** [comment]
I wish I could help somehow. As it is a non-profit site, I could offer you free support. You can contact me on Slack or via E-mail (in german) if you want.

**Comment by nhovratov** [comment]
Resolved.

The website in question defined:

```
module.tx_mask {
    view {
        templateRootPaths.0 = fileadmin/templates/mask/Resources/Private/Backend/Templates/
        partialRootPaths.0 = fileadmin/templates/mask/Resources/Private/Backend/Partials/
        layoutRootPaths.0 = fileadmin/templates/mask/Resources/Private/Backend/Layouts/
    }
}
```
which broke the Mask backend module.
Removing this fixed the issue.
