### ISSUE TITLE
AllowedFileExtensions seemingly not applied

### ISSUE THREAD

**Issue by nitori** [Gernott/mask#606]
TYPO3 11.5.31
Mask 8.3.7

It looks like the "allowedFileExtensions" option in "assets" field Configuration is not applied correctly.

Mask Configuration with reused "assets" core field:
![image](https://github.com/Gernott/mask/assets/1561831/2dfacc47-34c5-4966-a415-b72c80858574)

Result when creating mask element:
![image](https://github.com/Gernott/mask/assets/1561831/cf7241bf-d2bc-41be-94c7-fc3566b37ef2)

Resulting Configuration
![image](https://github.com/Gernott/mask/assets/1561831/d9fba3c6-e5a8-4a2e-a5d5-b4ab56a661d4)

TYPO3 12 seems to have the same issue (same mask version)
![image](https://github.com/Gernott/mask/assets/1561831/dcbdbdf8-1f05-4541-a93e-429297922de7)

Though it looks like "media" works just fine.

Greetings
Nitori

**Comment by nhovratov** [comment]
Hey, these are the "online media helpers". You need to deactivate them in the general tab:

![Screenshot 2023-11-29 at 11-28-38 Nikita Hovratov LIVE TYPO3 CMS 12 4 8](https://github.com/Gernott/mask/assets/19343425/edbc7114-9c8a-44c2-81a3-03131944f008)

**Comment by nitori** [comment]
That was it. Thanks.
