### ISSUE TITLE
Is it possible to define custom fluid template path for each element ? 

### ISSUE THREAD

**Issue by dacapoo** [Gernott/mask#609]
To the best of my knowledge, the extension settings currently allow the modification of global template, layout, and partial paths exclusively.

Is there a method to specify the fluid template path for each element individually? I've examined the mask.json element, and I couldn't find any property responsible for defining the path to the fluid template.

**Comment by nhovratov** [comment]
The paths are generated automatically relative to the extension settings. If you want another path for a single Mask element, you need to override the `FLUIDTEMPLATE` TypoScript object. This can be found in `tt_content.mask_{my_element}.templateRootPaths`.

Also, have a look into this guide: https://docs.typo3.org/p/mask/mask/8.3/en-us/Guides/FluidStyledContent.html
It's not directly related to your issue, but gives a bit of insight, how Mask works.

**Comment by dacapoo** [comment]
Thank you so much for the help @nhovratov !

**Comment by dacapoo** [comment]
Thank you so much for the help @nhovratov !
