### ISSUE TITLE
Parent Fields get deleted on Typo3 10

### ISSUE THREAD

**Issue by danielDigitalArt** [Gernott/mask#612]
Typo3 10.4.23
Mask Version 7.1.17 & 7.2.16

When using the Database Analyser it wants to delete some parent fields in the tt_content table:
![image](https://github.com/Gernott/mask/assets/25100967/5e370709-f12c-44a7-a6c0-e67d0317a835)

While i was doing an upgrade to Typo3 11 i cleaned up the Database with the Analyser before the update, my recommendation is to not delete any fields or tables at this stage, because these Fields are later used in typo3 11 and Mask Version 8.3.7 on an update in the Upgrade wizard, which then fails like so:
```
An exception occurred while executing 
'UPDATE `tt_content` SET 
	`tx_mask_content_parent_uid` = `tx_mask_inhalt_parent`, 
	`tx_mask_content_tablenames` = ?, 
	`tx_mask_content_role` = ? 
WHERE 
`tx_mask_inhalt_parent` <> ?'
```

When i found the Element which was using this Mask Element i found that the contents were lost. And the Upgrade Wizard can not finish this task.

After reverting back to the old Database Version (Backup from typo3 10.4.23 before any changes) i was able to let the upgrade wizard run through the full process, because i now did not let it remove any tables or fields, so the Upgrade Wizard is happy now.

**Comment by nhovratov** [comment]
Yes, this is a general advise to not delete any fields or tables during a TYPO3 update process if you are unsure.

**Comment by danielDigitalArt** [comment]
I Agree, the thing is the system was not touched for a long time, thus i found the Database changes coming from the last update process i did about 2 years ago, so normally i would have removed these fields back then.
It seems to me like the Fields were removed a long time ago and now mask needs these fields in order to update properly.

**Comment by nhovratov** [comment]
The persistence was changed in Mask v8.1, see: https://docs.typo3.org/p/mask/mask/8.3/en-us/Upgrade/Index.html#from-v8-0-x-or-lower

**Comment by nhovratov** [comment]
@danielDigitalArt This can't be. The change is only in Mask >= v8.1
The only reason the fields would be removed is if you deleted the field.

> Add a note to the Upgrade guide, to section 7, where it states that users should not let the Database Analyzer delete any fields with a Name like "tx_mask_***_parent"

I can add a note, good idea.

**Comment by nhovratov** [comment]
Closing due to lack of feedback. If you still need help, please reopen the issue.
