### ISSUE TITLE
Bug(?): field type "inline (repeating) contains "content"

### ISSUE THREAD

**Issue by mkoehlersg** [Gernott/mask#615]
TYPO3 v12.4.8
Mask: v8.3.8

I've created a mask element that contains a field type "inline" which contains field type "content".
<img width="351" alt="Bildschirmfoto 2024-01-26 um 11 02 40" src="https://github.com/Gernott/mask/assets/144663570/c0d5d64f-2b64-404c-8d5b-3c9da26bcae6">

I've inserted my new element on a page
<img width="781" alt="Bildschirmfoto 2024-01-26 um 11 15 42" src="https://github.com/Gernott/mask/assets/144663570/8aa95dc2-bd1a-41c3-a03c-75180454b7cc">

The elements from "content" are visible and editable inside the main content section of a page after saving my element.

<img width="715" alt="Bildschirmfoto 2024-01-26 um 11 03 03" src="https://github.com/Gernott/mask/assets/144663570/f0996a58-6eac-469e-8ea0-2f6144ba64ef">

"Element: Text" just appeared above my created mask element "Akkordeon" after saving (the position of created content is pretty random - it could also appear at the top of my page).

Is there a misconfiguration or a bug? 
Please help! Thanks!

**Comment by nhovratov** [comment]
@mkoehlersg Please check the `colPos` value of the nested Content Element. It should be 999. Also check, whether you have disabled the `colPos` field for the editor. If this is the case, the element will be saved with colPos 0 and everything breaks.

**Comment by mkoehlersg** [comment]
@nhovratov saved my life! Thank you so much :) 

- closed
