### ISSUE TITLE
Undefined array key "foreign_match_fields" 

### ISSUE THREAD

**Issue by bh-teufels** [Gernott/mask#616]
TYPO3 12.4.10
PHP 8.3.2 (appears on 8.2 also)
mask 8.3.8

Error Log:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: MASK\Mask\Definition\TableDefinitionCollection::loadField(): Argument #2 ($fieldName) must be of type string, null given, called in [...]/vendor/mask/mask/Classes/ItemsProcFuncs/CTypeList.php on line 56 \| TypeError thrown in file [...]/vendor/mask/mask/Classes/Definition/TableDefinitionCollection.php in line 193.

Core: Error handler (BE): PHP Warning: Trying to access array offset on null in [...]/vendor/mask/mask/Classes/ItemsProcFuncs/CTypeList.php line 47

Core: Error handler (BE): PHP Warning: Undefined array key "foreign_match_fields" in [...]/vendor/mask/mask/Classes/ItemsProcFuncs/CTypeList.php line 47

**Comment by nhovratov** [comment]
@bh-teufels Looks like you use field type "Content". Could you show me your json file(s)? One more question: Did you upgrade from an older version or did this happen on a new installation?

**Comment by bh-teufels** [comment]
yes uses field type "content". 
updated from TYPO3 11 to TYPO3 12

I  don't had any CE in Maks. I had already exported these to own Extensions using maks_export. But keep the mask Extension. To resolve the Problem i uninstalled maks. so i cant provide the json.

**Comment by bh-teufels** [comment]
okay so nothing which you can intercept with isset or something to provide running into this error?
then this can be closed because in this case I no longer use mask

**Comment by nhovratov** [comment]
I think this can be fixed, but is really an edge-case. So keep this ticket open.
