### ISSUE TITLE
Unable to render image tag

### ISSUE THREAD

**Issue by HansDump** [Gernott/mask#622]
Hi there,
when I try to open the BE module an error occurs:
_Unable to render image tag: File /blubb/public/_assets/a19a52d18aa5fcd2da308163624eb166/Icons/Extension.svg does not exist._
My typo url looks like this: https://devserver.com/blubb/public

When I debugged the image rendering Viewhelper which tries to render f.e. the following
`{f:uri.image(src: 'EXT:mask/Resources/Public/Icons/MaskUkraine.svg')}`
the asset handling isn't matching the correct path because of the relative path of my installation.
So it seems it tries to resolves the following: https://devserver.com/blubb/public/blubb/public/_assets/a19a52d18aa5fcd2da308163624eb166/Icons/Extension.svg

However, if you replace f.e.
{f:uri.image(src: 'EXT:mask/Resources/Public/Icons/MaskUkraine.svg')} 
with
{f:uri.resource(extensionName: 'Mask', path: 'Icons/MaskUkraine.svg')}
and the replace f:image with
<img src="{f:uri.resource(...)}"> (https://docs.typo3.org/other/typo3/view-helper-reference/12.4/en-us/typo3/fluid/latest/Uri/Resource.html)
it would work. And not just for me.

**Comment by nhovratov** [comment]
Your suggestion seems correct, will change it to f:uri.resource as the image should not be processed anyway.

**Comment by HansDump** [comment]
Thank you :)

**Comment by HansDump** [comment]
Hey,
sorry but it's me again :)
I installed your master with the changes, cool, thank you.
But now there is another issue which occurs when I open your module:
In your AjaxController in line 347 the retrieveFileOrFolderObject-Function (which is the same function the ImageViewhelper uses) is used to render the Backend Layout Icons. So for me the same error shows up as above.

**Comment by nhovratov** [comment]
How exactly did you setup TYPO3? It's not really clear for me what you mean by: https://devserver.com/blubb/public

**Comment by nhovratov** [comment]
Ah ok. This could also be a real TYPO3 bug. Normally f:image should be aware of this just as f:uri.resource.

**Comment by HansDump** [comment]
I think so too :/
