### ISSUE TITLE
media core field ignores allowedFileExtensions in palette

### ISSUE THREAD

**Issue by angu-dev** [Gernott/mask#628]
If I am in the mask element configuration and set a media-core field, explicit file extensions can be defined which are permitted for the upload.

However, if this field is placed within a palette, the specified configuration is ignored, as can be seen in my screenshots.

Is this a known behavior or am I missing something?

![image](https://github.com/Gernott/mask/assets/76621993/3883cd55-ef8f-483b-9742-38e70d542c2b)
![image](https://github.com/Gernott/mask/assets/76621993/e80f1dfe-ef29-44a1-9adf-15c66c2a9991)

**Comment by nhovratov** [comment]
@angu-dev Hi, you found a  bug, thanks for reporting!
