### ISSUE TITLE
Elements can not be activated in translations

### ISSUE THREAD

**Issue by StirnxXx** [Gernott/mask#632]
Hello everyone,

I have a weird issues in which the mask content elements can not be activated on translated pages. 
As soon as I click on save, to save the page, the switch resets and show the element is, once again, deactivated.

We are running on Typo3: 11.5.36 and Mask: v8.3.9

Thanks for your time!

Kindest regards
Eike

**Comment by nhovratov** [comment]
Hi, thanks for opening the issue. This sounds like a TYPO3 bug, not Mask. Could you provide some more details, maybe with screenshots. I'm not sure on which view you are referring to. Page Module, or nested Content Elements.

**Comment by StirnxXx** [comment]
Hi,

thanks for the reply.

Here is the Screenshot you asked for.
I drew a red circle around the switch which we usually use to activate the element.
Activating it and saving it results in being inactive again. The content elements inside this element can be activated without an issue.

<img width="1272" alt="Bildschirmfoto 2024-06-26 um 16 43 43" src="https://github.com/Gernott/mask/assets/24636394/f70def0d-0b53-4185-90bc-3a5d1818de5f">

Kindest Regards 
Eike

**Comment by nhovratov** [comment]
Thanks, this is a known bug in TYPO3. You need to use the activate checkbox in the "Zugriff" tab instead.

**Comment by nhovratov** [comment]
You can also try this in TCA/Overrides:

```
$GLOBALS['TCA']['tt_content']['columns']['hidden']['config']['items][0]['invertStateDisplay'] = false;
$GLOBALS['TCA']['tt_content']['columns']['hidden']['config']['renderType] = 'check';
$GLOBALS['TCA']['tt_content']['columns']['hidden']['label'] = 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.disable';

**Comment by StirnxXx** [comment]
Thanks a lot.
 I already thought it might be a known bug, but I just was not able to finde it.
You helped me a lot!

Have a great day.

Kindest Regards
Eike
