### ISSUE TITLE
TYPO3 13.4 Compatibility

### ISSUE THREAD

**Issue by olelinkfactory** [Gernott/mask#639]
Hello Team,

Are there any planned dates for the release of the TYPO3 13.4 compatible version?

Thank you for any updates.

**Comment by olelinkfactory** [comment]
Thank you for your fast response.

**Comment by linawolf** [comment]
Mask works great in a complex multisite project in TYPO3 13.4.0

I am missing site sets for TypoScript inclusion however. Would you like a PR?

**Comment by nhovratov** [comment]
@linawolf Of course I won't say no to contribution :)

**Comment by ByteBandito** [comment]
> Mask works great in a complex multisite project in TYPO3 13.4.0
> 
> I am missing site sets for TypoScript inclusion however. Would you like a PR?

What is the trick?
The main branch with Mask 8.3.11 creates a http500 error.... 

Help :-)

**Comment by nhovratov** [comment]
@ByteBandito Please create a new issue with the exact error.
