### ISSUE TITLE
Named parameter $tx_mask_content_parent_uid overwrites previous argument

### ISSUE THREAD

**Issue by olelinkfactory** [Gernott/mask#640]
Hello,

When we tried to test the mask TYPO3 13 compatible version in the "main" branch, we encountered the following error for the "Repeating" elements: The repeating elements are not expanded, and clicking on each element returns an "Error undefined" popup.

Also, when checking the install tool upgrade wizard and database analyser, got the following error. Please take a look at the attachment.

![mask_error](https://github.com/user-attachments/assets/32c2df43-22c7-4490-8991-b046275ca39f)

It would be great if you could provide an update on this issue as soon as possible.

Thank you.

**Comment by nhovratov** [comment]
Hi, thanks for testing and creating this issue. I will have a look into this as soon as I can.

**Comment by nhovratov** [comment]
Tested on main TYPO3 branch and it works:

![Screenshot 2024-09-05 at 20-28-06 Seiteninhalt Kein Titel auf Seite Home bearbeiten · Mask DEV TYPO3 CMS 13 3 0-dev](https://github.com/user-attachments/assets/451be881-6452-457e-8591-b953a85210be)

Could you please provide your Mask configuration?

**Comment by olelinkfactory** [comment]
Hello,

Thank you for the update. I placed my mask configuration there also, I am getting the same error. Maybe there is some issue with the mask.json file. Please see the attached configuration file.

Thank you for your support.

[mask.json](https://github.com/user-attachments/files/16902968/mask.json)

**Comment by olelinkfactory** [comment]
Hello,

Did you get a chance to look at this issue? Any updates would be really appreciated.

Thank you.

**Comment by nhovratov** [comment]
Still, I can't reproduce it:

![Screenshot 2024-10-11 at 17-38-18 Seiteninhalt Kein Titel auf Seite Home bearbeiten · Mask DEV TYPO3 CMS 13 4 0-dev](https://github.com/user-attachments/assets/19d486b9-5517-4be0-bbd7-061e9e139e79)

Please use a current TYPO3 version, or wait until next week when LTS is released. If it still happens then, I will have another look.

**Comment by olelinkfactory** [comment]
Hi @nhovratov 

Thank you. Let me check with the LTS version and give you an update soon.

**Comment by olelinkfactory** [comment]
Hi @nhovratov 

This is to inform you that, the reported issue is not reproduced with TYPO3 13.4 LTS. Thank you for your support.

**Comment by nhovratov** [comment]
@olelinkfactory Thanks for the feedback!
