### ISSUE TITLE
Issue With TYPO3 V13.2 

### ISSUE THREAD

**Issue by arunnitsan** [Gernott/mask#642]
Hello @nhovratov 

Could you please check this issue?

I have faced 2 issues with my project in TYPO3 v13.2.1.

Please check following the screencast.

[Database-analize.webm](https://github.com/user-attachments/assets/b0e6f9d8-37f6-4781-947f-2f2025d4dda5)
[Content-field.webm](https://github.com/user-attachments/assets/52832ae2-3c2c-44a8-ac8e-b27b0eb09df0)

Thanks in Advance!

**Comment by nhovratov** [comment]
Please wait until LTS is released next week and try again. I won't support obsolete TYPO3 versions. The current version is v13.3.

**Comment by arunnitsan** [comment]
Hey @nhovratov 
Greetings!

Thanks for the quick support.

I have updated TYPO3 v13.3.1 and my issues are resolved. 🙏 

Thanks again!
