### ISSUE TITLE
TYPO3 V13 Compatibility Issue ends with HTTP ERROR 500

### ISSUE THREAD

**Issue by ByteBandito** [Gernott/mask#646]
Typo3 13.4.0
Mask 8.3.11

After installing Mask via Extension-Manager system gets inoperateble with an http 500 error and the following lines in /typo3temp/var/log/*.log:

Tue, 05 Nov 2024 15:37:44 +0100 [CRITICAL] request="d504da4c6854c" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB: BE): Error, code #0, file /var/www/html/typo3conf/ext/mask/ext_localconf.php, line 42: Class "MASK\Mask\Enumeration\FieldType" not found - {"mode":"WEB","application_mode":"BE","exception_class":"Error","exception_code":0,"file":"/var/www/html/typo3conf/ext/mask/ext_localconf.php","line":42,"message":"Class \"MASK\\Mask\\Enumeration\\FieldType\" not found","request_url":"https://xxxx.de/typo3/","exception":null}

Any suggestions are highly appreciated.
Patrick

**Comment by nhovratov** [comment]
@ByteBandito There is no compatible version in TER. Either use composer and require `dev-main` or manually git clone the extension into typo3conf/ext/mask. A compatible v13 version will be release later this year.
