### ISSUE TITLE
Add dark mode for Backend Module for TYPO3 13

### ISSUE THREAD

**Issue by nitori** [Gernott/mask#648]
TYPO3 13 now has a dark mode, but the mask module doesn't seem to have anything yet, so it makes it look a bit odd:

![image](https://github.com/user-attachments/assets/cf754d85-7df8-4d5f-b4b5-5e4447973e88)

It seems the backend module is not using any (or only very few) of the TYPO3 Backend CSS variables.

Greetings
Nitori

**Comment by nhovratov** [comment]
+1  Help wanted!
