### ISSUE TITLE
Very quickly growing deprecation logs due to Enumeration used in TYPO3 13

### ISSUE THREAD

**Issue by nitori** [Gernott/mask#650]
The log entries in question are:

```txt
Sat, 16 Nov 2024 17:29:18 +0100 [NOTICE] request="178744505b1af" component="TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Class TYPO3\CMS\Core\Type\Enumeration used by enumeration MASK\Mask\Enumeration\FieldType will be removed in TYPO3 v14.0. Use native enums instead. in /html/typo3-composer/vendor/typo3/cms-core/Classes/Type/Enumeration.php line 194 
Sat, 16 Nov 2024 17:29:18 +0100 [NOTICE] request="178744505b1af" component="TYPO3.CMS.deprecations": Core: Error handler (BE): TYPO3 Deprecation Notice: Class TYPO3\CMS\Core\Type\Enumeration used by enumeration MASK\Mask\Enumeration\FieldType will be removed in TYPO3 v14.0. Use native enums instead. in /html/typo3-composer/vendor/typo3/cms-core/Classes/Type/Enumeration.php line 48 
```

A single (uncached) page reload caused the `typo3_deprecation*` log file to grow by nearly 1MB in my case.

**Comment by nhovratov** [comment]
TODO: Migrate MASK\Mask\Enumeration\FieldType to native PHP enum. This is possible now, as min PHP version is 8.1.

**Comment by nitori** [comment]
I tried a bit, but those enums are used *a lot* as array keys, but php enums cannot be used as array keys sadly. So all those cases would have to be rewritten:

e.g. this
```php
    private const STOP_RECURSIVE_VALUES_BY_TYPE = [
        FieldType::SELECT => [
            'config.itemGroups',
        ],
        FieldType::SLUG => [
            'config.generatorOptions.replacements',
        ],
    ];
```
would need to be instead:
```php
    private const STOP_RECURSIVE_VALUES_BY_TYPE = [
        FieldType::SELECT->value => [
            'config.itemGroups',
        ],
        FieldType::SLUG->value => [
            'config.generatorOptions.replacements',
        ],
    ];
```
Which is a bit clunky honestly.

The `Tab` enum is *only* used like that. In that case you can probably get away with removing the extends from the Tab class.

**Comment by nhovratov** [comment]
> Which is a bit clunky honestly.

This is ok, it doesn't have to win a beauty contest.

If you're on it, feel free to refactor it like you want. But don't spend too much time on it. If it works, that's enough. I don't think the code will be touched anymore.
