### ISSUE TITLE
Raise PHP dependency to 8.2 for v9

### ISSUE THREAD

**Issue by fjacobi** [Gernott/mask#654]
Hej, 

`mask/Classes/Definition/TcaFieldDefinition.php` is using a syntax feature of PHP 8.2

https://github.com/Gernott/mask/blob/main/Classes/Definition/TcaFieldDefinition.php#L41

https://wiki.php.net/rfc/fetch_property_in_const_expressions
https://www.php.net/manual/en/language.enumerations.expressions.php

**Comment by nhovratov** [comment]
Can't remember anymore, why I removed the tests for PHP 8.1. Might be because of other dependencies..
