### ISSUE TITLE
String values for radio items

### ISSUE THREAD

**Issue by cweiske** [Gernott/mask#656]
When adding a radio buttons field, mask only allows integers as field values.
TYPO3 itself [allows integers or strings](https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/Radio/#confval-radio-items):
> `value` (integer or string)
> The value stored in the database.

It would be nice if mask would also allow strings.

----

I have this problem with mask 8.3.10, but the changelog does not indicate that this behavior changed up to 9.0.4.

**Comment by nhovratov** [comment]
@cweiske The reason why this is not allowed: legacy.
Mask always used an `int` database field for type radio. So strings cannot be persisted.
Please use type select instead. This probably won't be fixed anymore.
