### ISSUE TITLE
clear cache don't work on every place

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#84]
At my presentaion at T3C Dresden with the current Git-Master (new clear cache included), it doesn't worked all the time.

**Comment by IchHabRecht** [comment]
Can you give some more information what was not working?

**Comment by Gernott** [comment]
Have a look at this video: 
2 Minutes from position 49:00 to 51:00
You see my workflow and the errormessage at the end.

**Comment by Gernott** [comment]
Hmmmm, the videolink is gone.
The frontendcache does not get flushed.
Clearing the Backendcache works fine.

**Comment by IchHabRecht** [comment]
The patch is indeed just for flushing the backend cache, not the frontend cache. I don't want the user to flush frontend cache silently if not necessary.
