### ISSUE TITLE
Packagist mails errors

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#85]
Don't know why. Missing version?

**Comment by IchHabRecht** [comment]
Where is the mail? What error is mentioned? Anything?

**Comment by Gernott** [comment]
mask/mask failed to update, invalid composer.json data

The mask/mask package of which you are a maintainer has
failed to update due to invalid data contained in your composer.json.
Please address this as soon as possible since the package stopped updating.

It is recommended that you use `composer validate` to check for errors when you
change your composer.json.

Below is the full update log which should highlight errors as
"Skipped branch ...":

[Composer\Repository\InvalidRepositoryException]: Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches

Reading composer.json of mask/mask (v3.0.1)
Importing tag v3.0.1 (3.0.1.0)
Reading composer.json of mask/mask (v3.0.0)
Importing tag v3.0.0 (3.0.0.0)
Reading composer.json of mask/mask (v2.1.0)
Importing tag v2.1.0 (2.1.0.0)
Reading composer.json of mask/mask (v2.0.1)
Skipped tag v2.0.1, tag (2.0.1.0) does not match version (2.0.0.0) in composer.json
Reading composer.json of mask/mask (v2.0.0)
Importing tag v2.0.0 (2.0.0.0)
Reading composer.json of mask/mask (v1.1.4)
Importing tag v1.1.4 (1.1.4.0)
Reading composer.json of mask/mask (v1.1.3)
Importing tag v1.1.3 (1.1.3.0)
Reading composer.json of mask/mask (v1.1.2)
Skipped tag v1.1.2, tag (1.1.2.0) does not match version (1.1.1.0) in composer.json
Reading composer.json of mask/mask (v1.1.1)
Importing tag v1.1.1 (1.1.1.0)
Reading composer.json of mask/mask (v1.1.0)
Importing tag v1.1.0 (1.1.0.0)
Reading composer.json of mask/mask (v1.0.1)
Importing tag v1.0.1 (1.0.1.0)
Reading composer.json of mask/mask (backendLayouts)
Importing branch backendLayouts (dev-backendLayouts)
Reading composer.json of mask/mask (exportImport)
Importing branch exportImport (dev-exportImport)
Reading composer.json of mask/mask (master)
Importing branch master (dev-master)
Skipped branch master, Invalid package information: 
License "GPL-2.0+" is a deprecated SPDX license identifier, use "GPL-2.0-or-later" instead

Reading composer.json of mask/mask (revert-44-fix-fluid-templates)
Importing branch revert-44-fix-fluid-templates (dev-revert-44-fix-fluid-templates)
Reading composer.json of mask/mask (2.1.1)
Importing branch 2.1.1 (2.1.1.x-dev)
Reading composer.json of mask/mask (3.0.2)
Importing branch 3.0.2 (3.0.2.x-dev)

**Comment by IchHabRecht** [comment]
As stated in the email, you need to switch license information in your composer.json (use "GPL-2.0-or-later" instead).

**Comment by Gernott** [comment]
Old ticket - no error since long time. Thank you Nicole ;)
