### ISSUE TITLE
Adding content elements breaks FE output

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#87]
From: Marcel Marty
Old Link: https://forge.typo3.org/issues/82925
Details:
Description

Steps to reproduce the error:

FE-Output:
1. Create FLUID-Template with <f:cObject typoscriptObjectPath="lib.content "/>
2. Integrate output with lib.content < styles.content.get

Mask Element Template:
1. Create new mask element "TEST"
2. Add "Repeating" Element
3. Add "Content" Element into Repeating
4. Save

Mask in Frotend
1. Add Mask Element "TEST"
2. Add one or multiple content elemtents

FE output works if cache is empty or cleaned. On second page view, the lib.content is empty until next cache clean. Seems that lib.tx_mask.content conflicts with styles.content.get

Installed version is 3.0.2
TYPO3 8.7.8

**Comment by butu** [comment]
Can't be reproduced.
