### ISSUE TITLE
Translation Backend Preview Content Element

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#88]
From: Stefan Schoner + Walter Kruml
Old Link: https://forge.typo3.org/issues/78157 + https://forge.typo3.org/issues/82895
Details:
1) When I translate a mask element no custom backend preview is shown.. I have used a repeating section and a custom preview template.
2) I have a mask CE with sections. CEs inside the sections are not shown in the backend layout on translated sites.
![bildschirmfoto 2017-11-01 um 16 49 49](https://user-images.githubusercontent.com/1930849/35528480-3e506db4-052e-11e8-90a2-495c67287db1.png)
![pasted image at 2016_10_06 11_13 am](https://user-images.githubusercontent.com/1930849/35528484-3e6a540e-052e-11e8-923e-9280303a7182.png)

**Comment by Gernott** [comment]
From: Andriy Khamuliak
Old Link: https://forge.typo3.org/issues/81962
Details:
Preview of IRRE is not working in not default languages because of bug in InlineHelper line 145

```
  // If this method is called in backend, there is no $GLOBALS['TSFE']
        if (isset($GLOBALS['TSFE']->sys_language_uid)) {
            $sysLangUid = $GLOBALS['TSFE']->sys_language_uid;
            $enableFields = $GLOBALS['TSFE']->cObj->enableFields($childTable);
        } else {
            $sysLangUid = 0;
            $enableFields = " AND " . $childTable . ".deleted = 0";
        }
```

First of all there is a case when TSFE will be initialized for backend previews also. So I would recommend to adjust this condition.

Also in case of not default language preview $sysLangUid is always 0, so there is no data from IRRE. To fix this you need to use 'sys_language_uid' from $data array.

possible solution:

```
        // If this method is called in backend, there is no $GLOBALS['TSFE']
        if (TYPO3_MODE == 'FE' && isset($GLOBALS['TSFE']->sys_language_uid)) {
            $sysLangUid = $GLOBALS['TSFE']->sys_language_uid;
            $enableFields = $GLOBALS['TSFE']->cObj->enableFields($childTable);
        } else {
            $sysLangUid = $data['sys_language_uid'];
            $enableFields = " AND " . $childTable . ".deleted = 0";
        }
```

**Comment by opaque01** [comment]
Works for me!
Thx.

**Comment by Gernott** [comment]
@opaque01 - would you like to make a pull request? Then we can migrate it easy into Mask.
