### ISSUE TITLE
Mask icons not found

### ISSUE THREAD

**Issue by mitchiru** [Gernott/mask#9]
I get a lot of missing images, when selecting the content element:

my.dev/typo3/icon%20=%20../fileadmin/MaskIcons/ce_myelement.png not found.

its with Maskt 1.1.2 and TYPO3 6.2.17

**Comment by butu** [comment]
Could you resolve this problem? We cannot reproduce in our projects.

**Comment by mkoitka** [comment]
Might not be the same problem @mitchiru has, but that happens for us when having a TYPO3 project in a subdirectory of a domain.

test.local/project/ -> Icons are not found
test.local/ -> Icons are found

It should suffice to prefix the rendering of the image source with ...
 _\TYPO3\CMS\Core\Utility\GeneralUtility::getIndpEnv('TYPO3_SITE_URL')_

**Comment by butu** [comment]
Moved to https://forge.typo3.org/issues/76419
