### ISSUE TITLE
Translation of Content Elements don't work

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#92]
From: Heiko Bihlmaier
Old Link: https://forge.typo3.org/issues/81149
Details:
I have a mask element with a content element. When I try to translate this in copy mode, the field in the foreign language is empty.
The checkbox "Localize Records when Content Element is localized" worked, but then I have the content element twice in the page. one time in the mask element and one time in the page.

**Comment by jwohlfeil** [comment]
Had the same issue, seems to be fixed in 1.1.4. Version before was 1.1.2...

**Comment by butu** [comment]
This is not a mask problem, but a problem of the typo3 core.
