### ISSUE TITLE
Content-Fields tab not visible in page edit (from workspace)

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#93]
From: Rafal Brzeski
Old Link: https://forge.typo3.org/issues/80259
Details:
This behaviour appears only on workspace module,
Content-Fields tab (added by Mask) is not visible in page edit until publishing the page.

To reproduce this bug, do the following:

1. Open Draft mode in Workspace module
2. Add new page in draft mode
3. Try to edit something in Tab Content-Fields from page edit
4. There is no Tab Content-Fields...
5. Publish that new created page
6. Try to edit something in Tab Content-Fields,
6. Tab Content-Fields is visible

**Comment by nhovratov** [comment]
works on current version
