### ISSUE TITLE
Workspace preview of irre elements

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#94]
From: Philip Heidenreich
Old Link: https://forge.typo3.org/issues/79527
Details:
When I create repeating elements, they won't show up in workspace preview.
The workspace overlays are created correctly in the database, but i can't see them on the frontend page.

Possible fix: InlineHelper.php -> getInlineElements()

```
// and recursively add them to an array
while ($element = $GLOBALS["TYPO3_DB"]->sql_fetch_assoc($sql)) {
    $GLOBALS['TSFE']->sys_page->versionOL($childTable,$element);
    if (is_array($element)) {
        $this->addIrreToData($element, $name, $cType);
        $this->addFilesToData($element, $name);
        $elements[] = $element;
    }
}
```

**Comment by butu** [comment]
This was already added :)
