### ISSUE TITLE
EXT:extensionkey syntax not working in Extensionmanager settings

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#98]
From: Gernot Ploiner
Old Link: https://forge.typo3.org/issues/80955
Details:
If you change the path in the Mask-Extension settings to a TYPO3 path like 'EXT:myext' ist doesn't work. Mask generates the folder /EXT:myext/ in the website root directory.

**Comment by nabossha** [comment]
is there any update on this isse? experiencing this as well..
