### ISSUE TITLE
selectbox with foreign_table - selected option is not shown correctly in the backend

### ISSUE THREAD

**Issue by Gernott** [Gernott/mask#99]
From: Jasper Topütt
Old Link: https://forge.typo3.org/issues/80847
Details:

When I create a select box with data from a foreign_table it first seems to work correctly.
I can choose the Records I need and it is saved correctly to the database.
But when I reopen the content element in the typo3 backend, allways the first value of the listbox is selected.
(typo3 7.6.16, mask 2.1.1)

**Comment by Gernott** [comment]
update: with typo3 8.7 and the current Mask version from github it's working fine when i select from any other table than tt_content (e.g. tx_mask_...).

But when i try to select anything from tt_content (even without where clause) i get an exception error like this in the backend "An exception occurred while executing 'SELECT `uid` FROM `tt_content` WHERE (`tx_mask_content_parent` = ?).... Unknown column 'tx_mask_content_parent' in 'where clause'"

**Comment by pascal20997** [comment]
I run into the same issue using TYPO3 8.7 and mask 3.0.2.

I´m trying to select the childs of my mask element with
foreign table: `tt_content`
foreign_table_where: `AND tt_content.tx_mask__content62_parent=###THIS_UID###`

Result is the following exception:
>An exception occurred while executing 'SELECT `uid` FROM `tt_content` WHERE
>(`tx_mask__default46_parent` = ?) AND (`tt_content`.`t3ver_wsid` IN (?, ?)) AND
>(`tt_content`.`pid` <> ?) AND (`tt_content`.`deleted` = 0) ORDER BY `sorting` ASC' with params
>[14998, 0, 0, -1]: Unknown column 'tx_mask__default46_parent' in 'where clause'

Do you have a workaround?
